import type { Guide } from "./guides";

/** Extra guides for specific shoppers. Keep the voice of the core set. */
export const MORE_GUIDES: Guide[] = [
  {
    slug: "energy-drinks",
    title: "Energy drinks are a soda with a job",
    kicker: "Caffeine is not a free pass",
    lede: "A 200 mg can is a tool, not a breakfast. Sugar, sweeteners, and a marketing department do not make it a vitamin.",
    minutes: 4,
    image: "/images/beverages.jpg",
    aisle: "beverages",
    persona: ["shop", "parent", "gym"],
    relatedBarcodes: ["012000001258", "5449000000996"],
    relatedIngredients: ["e951", "e950", "e150d"],
    sections: [
      {
        heading: "Read the milligrams",
        body: "Coffee is honest: a mug, a number you roughly know. Many cans hide two coffees plus sugar or a sweetener stack. Teens and a 300 mg ‘focus’ drink are a mismatch. If you train, caffeine has a dose. The rest of the can is a soda.",
      },
      {
        heading: "Zero is not clean",
        body: "Aspartame, sucralose, acesulfame K, caramel colour, phosphoric acid. A zero can still scores poorly on processing. Water, sparkling water, unsweetened tea: the keep. The can is a sometimes.",
      },
      {
        heading: "The afternoon crash",
        body: "If the can is how you start the day, the recipe is using you. Swap the daily one for coffee or tea. Keep a can for the 4 a.m. drive, not for homework.",
      },
    ],
  },
  {
    slug: "plant-milks",
    title: "Plant milk is a recipe, not a cow",
    kicker: "Oat, almond, soy — three jobs",
    lede: "A carton can be two ingredients or fourteen. The picture of oats does not tell you which.",
    minutes: 4,
    image: "/images/dairy.jpg",
    aisle: "dairy",
    persona: ["shop", "gut", "weight"],
    relatedBarcodes: [],
    relatedIngredients: ["sugar", "e412", "e407"],
    sections: [
      {
        heading: "Soy is the protein",
        body: "If you left dairy and still want protein in the pour, soy is the one that shows up on the label. Almond is mostly water. Oat is often starch and oil, which is why barista cartons foam and why they can score like a light dessert.",
      },
      {
        heading: "The barista trap",
        body: "Gums, added oils, dipotassium phosphate, flavour. Fine in a coffee shop cup. A daily litre of it is a processed drink. Look for: oat, water, salt. Or soy, water. Sweetened chocolate almond is a milkshake.",
      },
      {
        heading: "Kids",
        body: "Under five, plant cartons are not a casual swap for milk unless a clinician said so. For everyone else: scan the carton. The disc already read the gums.",
      },
    ],
  },
  {
    slug: "gut-emulsifiers",
    title: "What emulsifiers do in a gut",
    kicker: "Smooth ice cream, quieter research",
    lede: "Carboxymethylcellulose, polysorbate 80, carrageenan: they keep a sauce from splitting. They also show up in studies on the lining of the gut. Pattern, not panic.",
    minutes: 5,
    image: "/images/guide-nova.jpg",
    aisle: "snacks",
    persona: ["gut", "shop"],
    relatedBarcodes: [],
    relatedIngredients: ["e407", "e433", "e466"],
    sections: [
      {
        heading: "Why they exist",
        body: "A factory needs a dressing that still looks like dressing after six months on a truck. Emulsifiers do that job. Your kitchen uses egg yolk and a whisk. The warehouse uses a number.",
      },
      {
        heading: "The cautious read",
        body: "We mark the industrious ones moderate. Ice cream, processed sauces, some plant milks, some ‘healthy’ bars. If your gut is already loud — IBS, a flare — a week of short lists is a cheaper experiment than a new powder.",
      },
      {
        heading: "What to do in the aisle",
        body: "You do not have to memorise E-numbers. Scan. If the extras list is a paragraph, pick the neighbour with five words. That is the whole guide.",
      },
    ],
  },
  {
    slug: "glp1-grocery",
    title: "Shopping on a GLP-1",
    kicker: "Smaller stomach, honest food",
    lede: "If a shot is doing the appetite, the cart still has to do the protein, fibre, and fluids. Ultra-processed ‘diet’ food is the trap.",
    minutes: 5,
    image: "/images/protein.jpg",
    aisle: "protein",
    persona: ["weight", "gym"],
    relatedBarcodes: [],
    relatedIngredients: ["e955", "e960", "sugar"],
    sections: [
      {
        heading: "Protein first, then fibre",
        body: "A smaller meal has to earn its place. Yogurt, eggs, fish, tofu, a short-list cottage cheese. Bars with three sweeteners are a candy that learned the word protein. Fibre — oats, beans, fruit with skin — is how you stay regular when food is slower.",
      },
      {
        heading: "Skip the ‘lite’ aisle",
        body: "Fat-free pudding, zero cookies, protein chips. They exist to sell a feeling. On a GLP-1 you cannot afford empty volume that still processes like junk. Scan it. If the disc is red, it is not a helper.",
      },
      {
        heading: "Liquids",
        body: "Nausea plus a cola is a bad afternoon. Water, broth, unsweetened tea. Electrolyte drinks are a tool when you cannot eat, not a daily soda replacement — read the sugar.",
      },
    ],
  },
  {
    slug: "kids-lunchbox",
    title: "The lunchbox, without the cartoon",
    kicker: "If it needs a mascot",
    lede: "Pouches, gummies, ‘baked’ chips, juice boxes. The lunchbox became a vending machine. A few swaps and it looks like food again.",
    minutes: 4,
    image: "/images/snacks.jpg",
    aisle: "snacks",
    persona: ["parent"],
    relatedBarcodes: ["009800830039", "028400064057"],
    relatedIngredients: ["e102", "e129", "e951", "sugar"],
    sections: [
      {
        heading: "Dyes and behaviour",
        body: "We flag azo dyes (yellow 5, yellow 6, red 40 and friends) because the evidence on some children is not a vibe. EU packets already print a warning. Scan a neon snack. If the extras light up, there is a beige neighbour.",
      },
      {
        heading: "Juice is a soda",
        body: "A box of juice is teaspoons without the fizz. Water, milk, or a piece of fruit. Gummies that claim to be fruit are candy. Granola bars that claim to be breakfast are cookies.",
      },
      {
        heading: "What actually survives a backpack",
        body: "Cheese, a boiled egg, leftover chicken, an apple, plain yogurt, crackers with a short list. The cartoon aisle is designed to lose this argument on the shelf. Win it at home, once, then repeat.",
      },
    ],
  },
  {
    slug: "seed-oils",
    title: "Seed oils, without the conspiracy",
    kicker: "Dose and the rest of the recipe",
    lede: "Internet sermons treat canola like a poison. The packet treats it like a solvent for ultra-processed food. Both miss the boring middle: how much, and what it came with.",
    minutes: 4,
    image: "/images/condiments.jpg",
    aisle: "condiments",
    persona: ["shop"],
    relatedBarcodes: ["3017620422003"],
    relatedIngredients: ["palm-oil"],
    sections: [
      {
        heading: "The honest part",
        body: "A home sauté in rapeseed or sunflower is not a scandal. A factory fryer that also adds flavour, emulsifier, and sugar is the pattern we score. Olive oil and cold-pressed options still win on the planet mark and usually on the list.",
      },
      {
        heading: "Where it hides",
        body: "Biscuits, chips, cheap sauce, frozen breaded anything. If seed oil is ingredient two after refined starch, you are not cooking. You are buying a warehouse recipe. Scan it.",
      },
      {
        heading: "What we do not do",
        body: "We do not ban an oil because a thread said so. We score the pack in front of you. Short list, olive or butter in a real kitchen: keep. A doughnut’s frying medium is not your salad dressing.",
      },
    ],
  },
  {
    slug: "electrolytes",
    title: "Electrolytes are not a personality",
    kicker: "Sweat, illness, then stop",
    lede: "Sodium, potassium, a little sugar to pull water in. A neon bottle with sucralose is a sports-drink costume.",
    minutes: 3,
    image: "/images/beverages.jpg",
    aisle: "beverages",
    persona: ["gym", "shop"],
    relatedBarcodes: [],
    relatedIngredients: ["e951", "e955", "sugar"],
    sections: [
      {
        heading: "When they earn a place",
        body: "Long heat, a stomach bug, a hard session you actually soaked through. Then a simple formula helps. Desk work in air-con does not.",
      },
      {
        heading: "Read the sugar and the dyes",
        body: "Classic sports drinks are sugar water with salt — honest, if you ran. ‘Zero’ versions add sweeteners and often a dye. Coconut water is a fruit juice with potassium, not magic. Scan the bottle.",
      },
    ],
  },
  {
    slug: "retinol-actives",
    title: "Retinol and the actives shelf",
    kicker: "More is not kinder",
    lede: "Vitamin A derivatives work. They also irritate, and they are the first thing we flag in pregnancy. Strength is a choice, not a personality.",
    minutes: 4,
    image: "/images/skincare.jpg",
    aisle: "skincare",
    persona: ["beauty", "pregnancy"],
    relatedBarcodes: [],
    relatedIngredients: ["retinol", "fragrance"],
    sections: [
      {
        heading: "The hierarchy",
        body: "Retinyl palmitate is mild. Retinol is the common bottle. Tretinoin is a prescription. More conversion, more effect, more peel. If your face is already loud, start lower and skip fragrance in the same routine.",
      },
      {
        heading: "Pregnancy",
        body: "Leave-on vitamin A is a skip while pregnant. Set the profile. We will stop you on the serum, not after a forum thread. A bland moisturiser and mineral SPF are the whole cabinet you need.",
      },
      {
        heading: "The rest of the bottle",
        body: "A 0.3% retinol in a base of essential oils and alcohol is a stunt. Scan the full list. The active is one line. The extras decide whether you can wear it.",
      },
    ],
  },
  {
    slug: "hair-wash",
    title: "What’s in a shampoo",
    kicker: "Foam is not a nutrient",
    lede: "Sulfates clean. Silicones slip. Fragrance sells the cap. Your scalp did not ask for a perfume that sits until the next wash.",
    minutes: 3,
    image: "/images/hair.jpg",
    aisle: "hair",
    persona: ["beauty"],
    relatedBarcodes: [],
    relatedIngredients: ["fragrance", "sls"],
    sections: [
      {
        heading: "Sulfates are a tool",
        body: "SLS and SLES foam because they are good at lifting oil. Fine for most scalps, a bit much for a stripped or colour-treated one. ‘Sulfate-free’ is not automatically gentler — it often swaps in other surfactants and more perfume.",
      },
      {
        heading: "What we flag",
        body: "Fragrance in a leave-on serum, some preservatives, and the usual high-concern extras. A rinse-off wash is less of a story than a night cream. Still: if your scalp itches, the perfume is the first thing to drop. Scan it.",
      },
    ],
  },
  {
    slug: "makeup-list",
    title: "Makeup is still a formula",
    kicker: "Colour, then the extras",
    lede: "A lipstick is wax, oil, pigment. Some are calm. Some carry the same preservatives and fragrance we flag in a cream, sitting on your mouth all day.",
    minutes: 3,
    image: "/images/makeup.jpg",
    aisle: "makeup",
    persona: ["beauty"],
    relatedBarcodes: [],
    relatedIngredients: ["fragrance", "e171"],
    sections: [
      {
        heading: "Leave-on, again",
        body: "Foundation and lip are closer to skincare than to a rinse-off. Parabens, formaldehyde-releasers, and heavy fragrance matter more here than in a hand soap. Mineral tints with a short list exist.",
      },
      {
        heading: "Glitter and titanium",
        body: "We score what we can read. A shrinking list is a keep. If the brand will not print INCI in a type you can scan, that is information too.",
      },
    ],
  },
  {
    slug: "toothpaste-aisle",
    title: "Toothpaste is a mouthful of extras",
    kicker: "Fluoride first, stripes later",
    lede: "The job is fluoride and a clean. Whitening peroxides, triclosan leftovers, and a mint so strong it needs a warning are optional.",
    minutes: 3,
    image: "/images/oral.jpg",
    aisle: "oral",
    persona: ["beauty", "parent"],
    relatedBarcodes: [],
    relatedIngredients: ["triclosan", "fragrance"],
    sections: [
      {
        heading: "Kids",
        body: "A pea of fluoride paste, spit, done. Character pastes that taste like dessert train swallowing. Skip triclosan. Skip a rainbow of dyes in something they might eat.",
      },
      {
        heading: "Whitening",
        body: "Peroxide strips and pastes can sting. Charcoal is theatre. If your gums are already unhappy, a calm fluoride paste is the keep. Scan the tube — extras still count in a rinse-off that lives in your mouth.",
      },
    ],
  },
  {
    slug: "alcohol-aisle",
    title: "Drinks that are not ‘just alcohol’",
    kicker: "The mixer is the recipe",
    lede: "Beer, wine, a simple spirit: we can read those. A can of pre-mix is often soda with a percentage attached.",
    minutes: 3,
    image: "/images/alcohol.jpg",
    aisle: "alcohol",
    persona: ["shop"],
    relatedBarcodes: [],
    relatedIngredients: ["sugar", "e150d", "e951"],
    sections: [
      {
        heading: "The can",
        body: "Hard seltzer, alcopop, a ‘vodka soda’ with flavour. Sugar or sweeteners, colour, a fruit name that never met a fruit. Scan it like a soft drink, because that is the rest of the recipe.",
      },
      {
        heading: "What the number cannot do",
        body: "Healthie does not grade a hangover or a liver. It grades the pack. A short-list beer and a neon can will not look the same, and they should not.",
      },
    ],
  },
  {
    slug: "sleep-gummies",
    title: "Sleep gummies are still candy",
    kicker: "Melatonin plus a dessert",
    lede: "A milligram of hormone in a pectin sweet, with flavour, colour, and a bedtime story. The gummy is doing more marketing than chemistry.",
    minutes: 3,
    image: "/images/vitamins.jpg",
    aisle: "vitamins",
    persona: ["shop", "parent"],
    relatedBarcodes: [],
    relatedIngredients: ["e102", "sugar", "e129"],
    sections: [
      {
        heading: "Dose first",
        body: "More melatonin is not kinder. Many gummies overshoot what a adult needs, and kids’ products are a special kind of messy. If you use it, a plain tablet is easier to dose than a sweet you might eat two of.",
      },
      {
        heading: "The candy problem",
        body: "Sugar, syrup, dyes, ‘natural flavour’. You would not eat that at 11 p.m. as a snack and call it medicine. Scan the bottle. If the extras look like a pick-and-mix, pick the boring tablet.",
      },
    ],
  },
  {
    slug: "under-the-sink",
    title: "Under the sink",
    kicker: "Clean is not the same as perfume",
    lede: "A dish soap that smells like an orchard is still a surfactant plus fragrance. The plate did not need the orchard.",
    minutes: 3,
    image: "/images/household.jpg",
    aisle: "household",
    persona: ["shop", "parent"],
    relatedBarcodes: [],
    relatedIngredients: ["fragrance"],
    sections: [
      {
        heading: "Rinse-off still counts",
        body: "You rinse plates. You do not always rinse the air, a baby’s high chair, or your hands after. Fragrance, some preservatives, and the usual high-concern extras still show up. Unscented, a short INCI, no colour: the keep.",
      },
      {
        heading: "‘Natural’ bleach",
        body: "A plant drawing on a spray bottle is not a composition. Scan it. If we cannot read a list, we will not invent a green disc.",
      },
    ],
  },
  {
    slug: "collagen-powders",
    title: "Collagen is a protein powder with better lighting",
    kicker: "Skin claims, kitchen reality",
    lede: "Hydrolysed collagen is protein. It is not a facelift in a tub. Flavoured versions often pick up sweeteners, gums, and a vanilla that never saw a pod.",
    minutes: 3,
    image: "/images/vitamins.jpg",
    aisle: "vitamins",
    persona: ["beauty", "gym"],
    relatedBarcodes: [],
    relatedIngredients: ["e955", "e960", "e407"],
    sections: [
      {
        heading: "Unflavoured is the test",
        body: "If the tub is collagen and nothing else, you are buying protein. Stir it into something you already eat. The moment it tastes like a milkshake, read the rest of the list.",
      },
      {
        heading: "Hair, skin, nails",
        body: "We do not score Instagram. We score extras. A ‘beauty’ collagen with sucralose and dye is a supplement that learned makeup. Food first: meat, fish, dairy, soy, eggs. Then a tub if you want one.",
      },
    ],
  },
  {
    slug: "sodium-quietly",
    title: "Salt, quietly",
    kicker: "The milligrams you do not taste",
    lede: "Bread, ham, sauce, a ‘healthy’ soup. Salt is not only the shaker. It is how a factory makes bland starch interesting.",
    minutes: 3,
    image: "/images/meat.jpg",
    aisle: "meat",
    persona: ["shop", "weight"],
    relatedBarcodes: [],
    relatedIngredients: ["e250", "e621"],
    sections: [
      {
        heading: "Where it hides",
        body: "Cured meat, cheese, bread, ketchup, noodles, a broth carton. One ham sandwich can be a day’s salt before lunch. We already pull the nutrition box for this. Open Why this number.",
      },
      {
        heading: "MSG and friends",
        body: "Monosodium glutamate is salt plus a savoury trick. We mark it. It is not a poison story. It is a sign the recipe is chasing flavour without cooking. A tomato, garlic, and time still work.",
      },
    ],
  },
  {
    slug: "where-the-fiber-went",
    title: "Where the fibre went",
    kicker: "The missing half of breakfast",
    lede: "Most supermarket breakfasts are starch and sugar with the bran sold separately as a supplement. Fruit with skin, oats, beans: still cheaper.",
    minutes: 3,
    image: "/images/breakfast.jpg",
    aisle: "breakfast",
    persona: ["gut", "weight", "shop"],
    relatedBarcodes: ["0810589032602", "099482513931"],
    relatedIngredients: ["sugar"],
    sections: [
      {
        heading: "Cereal is a dessert",
        body: "If the box needs a cartoon or a ‘protein’ banner, look at fibre per 100 g. Under 6 g and a pile of sugar is a cookie. Granola is often worse. Plain oats still win.",
      },
      {
        heading: "The easy adds",
        body: "Beans at lunch, berries, a pear, rye bread with a short list. Fibre is not a powder first. It is a plant you can still recognise. Scan the box when you are unsure — nutrition is half the disc.",
      },
    ],
  },
  {
    slug: "chocolate-aisle",
    title: "Chocolate is allowed. The bar is a recipe.",
    kicker: "Cocoa, sugar, the third thing",
    lede: "A 70% bar with cocoa, sugar, cocoa butter is a treat with a short list. A ‘protein’ chocolate or a spread with palm oil is a different object.",
    minutes: 3,
    image: "/images/chocolate.jpg",
    aisle: "chocolate",
    persona: ["shop", "parent"],
    relatedBarcodes: ["3017620422003"],
    relatedIngredients: ["palm-oil", "e322", "sugar"],
    sections: [
      {
        heading: "The keep",
        body: "Cocoa mass, sugar, cocoa butter, maybe vanilla, maybe lecithin. Darker usually means less sugar. Milk chocolate can still be honest. Kids’ bars with a toy are candy.",
      },
      {
        heading: "The walk-away",
        body: "Palm oil as a cocoa-butter stand-in, PGPR, a rainbow of extras. Nutella is a lesson, not a breakfast. Scan the spread and the bar side by side — same aisle, different lives.",
      },
      {
        heading: "How to shop it",
        body: "Cocoa, sugar, cocoa butter. If the third thing is palm oil or a toy, it is candy. Darker usually means less sugar, not a vitamin. Scan the bar.",
      },
    ],
  },
  {
    slug: "ice-cream-freezer",
    title: "Ice cream vs the frozen dessert",
    kicker: "Cream, or a chemistry set",
    lede: "Dairy, sugar, maybe egg. That is ice cream. Air, gums, flavour, and ‘frozen dairy dessert’ is a different legal object.",
    minutes: 3,
    image: "/images/icecream.jpg",
    aisle: "icecream",
    persona: ["shop", "parent"],
    relatedBarcodes: [],
    relatedIngredients: ["e407", "e412", "e471"],
    sections: [
      {
        heading: "The three-ingredient tub",
        body: "It exists. It costs more because cream costs more. A supermarket brick that never melts quite right is full of the emulsifiers from the gut note. Fine as a Saturday. Not a nightly vitamin.",
      },
      {
        heading: "Kids’ novelties",
        body: "Shapes, dyes, a biscuit that never saw butter. The freezer aisle is two aisles, like the other freezer. Sort by score. The beige tubs rise.",
      },
      {
        heading: "How to shop it",
        body: "Cream, milk, sugar, maybe egg. If the list is a paragraph of gums, it is a frozen dessert. Fine on a Saturday. Scan the tub before it is a weekly habit.",
      },
    ],
  },
  {
    slug: "the-bread-counter",
    title: "Bread, if it is still bread",
    kicker: "Flour, water, salt, time",
    lede: "A supermarket loaf can be a bun recipe: sugar, emulsifier, palm, a preservative so it lasts until next month. Real bread goes stale.",
    minutes: 3,
    image: "/images/bakery.jpg",
    aisle: "bakery",
    persona: ["shop", "gut"],
    relatedBarcodes: [],
    relatedIngredients: ["e471", "e282", "sugar"],
    sections: [
      {
        heading: "The 10-second list",
        body: "Flour, water, salt, yeast or sourdough. Seeds if you like. Sugar in the first five is a bun. Calcium propionate keeps it ‘fresh’ — we mark it. If it lasts two weeks, it is not because of your cupboard.",
      },
      {
        heading: "Wholegrain is not a halo",
        body: "A brown loaf with caramel colour is a trick. Fibre on the nutrition box is the check. Scan it. The disc already did the brown-versus-beige argument.",
      },
      {
        heading: "How to shop it",
        body: "Flour, water, salt, time. If it lasts two weeks, that is the preservative talking. Buy a loaf that goes stale, or scan the supermarket one and pick the shorter list.",
      },
    ],
  },
  {
    slug: "creatine-plain",
    title: "Creatine is not a protein bar",
    kicker: "Monohydrate, water, done",
    lede: "The supplement with actual evidence is a boring white powder. The gummies, the ‘complex’, the fruit punch: extras on a molecule that did not ask for them.",
    minutes: 3,
    image: "/images/protein.jpg",
    aisle: "protein",
    persona: ["gym"],
    relatedBarcodes: [],
    relatedIngredients: ["e955", "e102"],
    sections: [
      {
        heading: "Buy dull",
        body: "Creatine monohydrate. Unflavoured. A scoop in something you already drink. Loading phases and patented blends are mostly theatre. If the tub is loud, the list will be too.",
      },
      {
        heading: "Gummies",
        body: "Same problem as sleep gummies: a milligram in a candy. Sugar, dye, flavour, a dose you cannot split. Scan it. Then buy the tub that looks like a science cupboard.",
      },
    ],
  },
  {
    slug: "sensitive-skin",
    title: "Sensitive skin is a short list",
    kicker: "Fragrance is the first cut",
    lede: "If your face stings, the cabinet is too interesting. Water, glycerin, a bland emulsifier, maybe niacinamide. Not a twelve-oil ‘barrier’ serum.",
    minutes: 3,
    image: "/images/skincare.jpg",
    aisle: "skincare",
    persona: ["beauty"],
    relatedBarcodes: [],
    relatedIngredients: ["fragrance", "linalool", "limonene"],
    sections: [
      {
        heading: "Turn the profile on",
        body: "Sensitive skin in You flags fragrance and the usual irritants on every scan. Do that once. Then the aisle gets quieter without a new personality.",
      },
      {
        heading: "What ‘hypoallergenic’ is not",
        body: "A word on the front. The back is still a formula. Essential oils are not gentler because they are plants. Scan the bottle. If extras glow, leave it.",
      },
    ],
  },
  {
    slug: "allergens-on-pack",
    title: "Allergens: the pack still wins",
    kicker: "We help. We do not replace the label.",
    lede: "Set milk, nuts, gluten, the rest. We stop you in the aisle when the recipe we have matches. Factory lines change. The printed pack is still the legal document.",
    minutes: 3,
    image: "/images/guide-score.jpg",
    persona: ["parent", "shop"],
    relatedBarcodes: [],
    relatedIngredients: ["milk", "gluten", "peanut"],
    sections: [
      {
        heading: "What Healthie can do",
        body: "If the Open Food Facts record or our catalog lists an allergen, and you ticked it in You, we put a stop on the product page. That is the point of the profile.",
      },
      {
        heading: "What we cannot do",
        body: "A missing record, a recipe change last Tuesday, a ‘may contain’ that never made it into the database. If you have a serious allergy, read the pack in your hand. We are a lamp, not a clinician.",
      },
      {
        heading: "Set it once",
        body: "You → allergens. Milk, gluten, peanut, the rest. Then every scan carries the stop. Sign in and the next phone is the same lab.",
      },
    ],
  },
  {
    slug: "cereal-aisle",
    title: "Breakfast cereal is a dessert with a bowl",
    kicker: "The first meal, or the first sugar",
    lede: "A box can be oats and a pinch of salt, or a children’s cartoon with more sugar than a biscuit. The milk does not cancel the recipe.",
    minutes: 4,
    image: "/images/breakfast.jpg",
    aisle: "breakfast",
    persona: ["parent", "shop", "weight"],
    relatedBarcodes: ["0810589032602"],
    relatedIngredients: ["sugar", "e102", "e551"],
    sections: [
      {
        heading: "The teaspoon test, again",
        body: "Four grams is a teaspoon. If the box is 12 g of sugar in 30 g of cereal, that is dessert before 8 a.m. Granola is often worse — oil and honey until it clusters. Scan the box. Oats still win.",
      },
      {
        heading: "Kids’ boxes",
        body: "Mascots, dyes, a toy. The EU already warns on some colours. We flag them. A beige flake with fibre is not a personality, and it is a better weekday.",
      },
      {
        heading: "How to shop it",
        body: "Oats, unsweetened flakes, a handful of fruit. If you want crunch, toast your own. The wall of boxes is designed to lose this argument. Win it with the disc.",
      },
    ],
  },
  {
    slug: "coffee-creamers",
    title: "Coffee creamers are not dairy",
    kicker: "The mug’s invisible dessert",
    lede: "A splash a day is a weekly dessert if the bottle is sugar, oil, and flavour. Milk or a short-list oat is a different mug.",
    minutes: 3,
    image: "/images/coffee.jpg",
    aisle: "dairy",
    persona: ["shop", "weight"],
    relatedBarcodes: [],
    relatedIngredients: ["sugar", "e471", "e407", "palm-oil"],
    sections: [
      {
        heading: "What it actually is",
        body: "Water, sugar, sunflower or palm oil, flavour, gums, a colour. Italian Sweet Cream is a pudding for coffee. Dairy cream is cream. Oat ‘barista’ is a recipe — scan it.",
      },
      {
        heading: "The daily dose",
        body: "Two tablespoons, twice a day, is how a quiet bottle becomes a habit the nutrition box never showed you. If the disc is red, use milk, or drink the coffee black for a week and notice.",
      },
      {
        heading: "How to shop it",
        body: "Milk, a splash of half-and-half, unsweetened soy. Flavoured creamers are a soda with better lighting. Scan the bottle once.",
      },
    ],
  },
  {
    slug: "sunscreen-filters",
    title: "Sunscreen is a filter, not a vibe",
    kicker: "Mineral or chemical — read the INCI",
    lede: "SPF is the job. The rest of the bottle is a leave-on cosmetic we score like any other cream: fragrance, endocrine filters, sprays.",
    minutes: 5,
    image: "/images/sun.jpg",
    aisle: "sun",
    persona: ["beauty", "parent", "pregnancy"],
    relatedBarcodes: [],
    relatedIngredients: ["oxybenzone", "octinoxate", "avobenzone", "fragrance"],
    sections: [
      {
        heading: "The keep",
        body: "Zinc oxide, titanium dioxide, a bland cream. Fragrance-free. That is the bottle we would put on a child and on a pregnant belly. Chemical filters can be fine — avobenzone is a workhorse — but oxybenzone and octinoxate are the ones we mark harder.",
      },
      {
        heading: "Sprays and ‘reef safe’",
        body: "Sprays are hard to dose and easy to inhale. ‘Reef safe’ is a marketing sentence, not a lab. We score the filters we can see. Scan the bottle. The disc does not care about the turtle on the front.",
      },
      {
        heading: "How to shop it",
        body: "A cream you will actually wear. Mineral if your skin or your values want it. No perfume. Reapply. The score is the formula, not the tan.",
      },
    ],
  },
  {
    slug: "deodorant-aisle",
    title: "Deodorant is not a detox",
    kicker: "Aluminium, fragrance, the armpit",
    lede: "Stopping sweat is a salt. Stopping smell is a perfume or an acid. ‘Natural’ crystals and essential-oil sticks are still a formula. Scan them.",
    minutes: 4,
    image: "/images/body.jpg",
    aisle: "body",
    persona: ["beauty", "shop"],
    relatedBarcodes: [],
    relatedIngredients: ["aluminum-chlorohydrate", "fragrance", "triclosan"],
    sections: [
      {
        heading: "Aluminium is a choice",
        body: "Antiperspirant salts work. We mark them moderate because they are a leave-on aluminium on thin skin, not because a thread said they cause a disease we do not claim. If you want deodorant without the salt, that is a smell product — usually fragrance-heavy.",
      },
      {
        heading: "The ‘natural’ stick",
        body: "Baking soda burns some people. Essential oils are fragrance. A crystal is a salt. None of this is automatically gentler. Sensitive underarms: short list, low perfume. Scan it.",
      },
      {
        heading: "How to shop it",
        body: "Decide if you need to stop sweat or just smell. Then read the extras. Triclosan does not belong in a daily stick. Fragrance is the first cut if you react.",
      },
    ],
  },
  {
    slug: "kombucha-gut-soda",
    title: "Kombucha is a soda with a story",
    kicker: "The gut aisle’s fizz",
    lede: "A fermented tea can be a short list. Most bottles on the fridge shelf are sugar, flavour, and a probiotic claim. Scan before you call it medicine.",
    minutes: 4,
    image: "/images/beverages.jpg",
    aisle: "beverages",
    persona: ["gut", "shop", "weight"],
    relatedBarcodes: ["5449000000996"],
    relatedIngredients: ["sugar", "e330"],
    sections: [
      {
        heading: "What fermentation actually did",
        body: "Tea, sugar, a culture. Some sugar is eaten. What remains is still sugar. Live cultures may or may not survive the warehouse. A shot of sauerkraut brine is a more honest ferment.",
      },
      {
        heading: "Hard seltzer’s cousin",
        body: "Juice, flavour, 8 g of sugar, a wellness word. Gut sodas and ‘prebiotic’ colas are the same trick as vitamin water. If you like the taste, fine. Do not pay a supplement price for a soda score.",
      },
      {
        heading: "How to shop it",
        body: "Tea, culture, low sugar. Or water. Scan the bottle. If the extras and the teaspoons look like a cola, it is a cola.",
      },
    ],
  },
  {
    slug: "ultraprocessed",
    title: "Ultra-processed, in one aisle minute",
    kicker: "If your gran would not cook it",
    lede: "NOVA 4 is not a moral grade. It is a recipe with cosmetic additives — flavour, colour, emulsifier — built to be eaten fast. The disc already weights it.",
    minutes: 4,
    image: "/images/guide-nova.jpg",
    persona: ["shop", "parent", "weight", "gut"],
    relatedBarcodes: ["5449000000996", "009800830039", "3017620422003"],
    relatedIngredients: ["e471", "e621", "natural-flavour"],
    sections: [
      {
        heading: "The practical test",
        body: "Could you make a version in a normal kitchen with food you recognise? Bread, yogurt, cheese: often yes. A neon snack, a reconstituted nugget, a protein puff: no. That is the split.",
      },
      {
        heading: "Not all processing is the enemy",
        body: "Frozen peas, tinned tomatoes, pasteurised milk. Those are preservation. Ultra-processed is when the recipe needs a flavour lab. We score the pack, not the freezer.",
      },
      {
        heading: "How to shop it",
        body: "You do not have to memorise NOVA. Scan. If the extras list is a paragraph, pick the neighbour with five words. That is the whole method.",
      },
    ],
  },
  {
    slug: "olive-oil",
    title: "Olive oil, if it is still olives",
    kicker: "Extra virgin vs the blend",
    lede: "A tin of extra virgin is a fruit juice. A bottle of ‘light olive oil’ or a seed-oil blend with an olive leaf on the label is a different cupboard.",
    minutes: 3,
    image: "/images/condiments.jpg",
    aisle: "condiments",
    persona: ["shop"],
    relatedBarcodes: [],
    relatedIngredients: ["palm-oil"],
    sections: [
      {
        heading: "The keep",
        body: "Extra virgin, a harvest date, a dark bottle. Bitter and peppery is a good sign. It is still a fat — the score is not a licence to drink it — but it is food.",
      },
      {
        heading: "The blend",
        body: "‘Olive oil’ without extra virgin is often refined. Vegetable oil with 15% olive for the photograph is a seed oil. Scan cooking sprays too — propellant and lecithin are a different object.",
      },
      {
        heading: "How to shop it",
        body: "One decent extra virgin for finishing, a cheaper honest one for heat if you want. Ignore the leaf on a blend. The list is three words or it is a story.",
      },
    ],
  },
  {
    slug: "bottled-water",
    title: "Bottled water is a package, not a spring",
    kicker: "Evian is one thing. A vitamin water is not.",
    lede: "Plain water in a bottle scores like water. Flavour, sweetener, ‘electrolytes’, and a mountain on the label are a soda with better lighting.",
    minutes: 3,
    image: "/images/beverages.jpg",
    aisle: "beverages",
    persona: ["shop", "gym", "parent"],
    relatedBarcodes: ["3274080005003", "012000001258"],
    relatedIngredients: ["e951", "e330", "sugar"],
    sections: [
      {
        heading: "The keep",
        body: "Water. Maybe minerals the spring already had. Evian is the example in this lab because the list is honest. Tap is usually fine. A bottle is a convenience, not a personality.",
      },
      {
        heading: "The costume",
        body: "Alkaline, electrolyte, vitamin, ‘focus’. Scan it. If there is sucralose or sugar, you bought a drink. If there is a dye, you bought a drink with a costume.",
      },
      {
        heading: "How to shop it",
        body: "Tap, a bottle you refill, or a still spring water with one ingredient. Sports drinks are for sweat you can name, not for a desk.",
      },
    ],
  },
  {
    slug: "protein-shakes",
    title: "Protein powder is a tool, not a personality",
    kicker: "Whey, a scoop, then stop",
    lede: "A tub of whey or a plain soy isolate can earn a place. A mass-gainer shake with sugar, oils, and a cartoon is a meal-replacement dessert.",
    minutes: 4,
    image: "/images/protein.jpg",
    aisle: "protein",
    persona: ["gym", "weight"],
    relatedBarcodes: [],
    relatedIngredients: ["e955", "e102", "e551"],
    sections: [
      {
        heading: "Buy dull",
        body: "Whey concentrate or isolate, unflavoured or a short flavour list. Soy if you do not do dairy. Mix it with milk or water you already drink. The ‘dessert’ flavours are where the extras live.",
      },
      {
        heading: "Ready-to-drink",
        body: "Cartons in the fridge aisle are often sucralose, carrageenan, and a texture lab. Fine as a delay. Not cleaner than a yogurt. Scan the carton.",
      },
      {
        heading: "How to shop it",
        body: "Food first: eggs, yogurt, fish, tofu, a tin of beans. Powder for the gap. If the tub looks like a nightclub, the list will too.",
      },
    ],
  },
  {
    slug: "probiotic-pills",
    title: "Probiotic pills are not a yogurt",
    kicker: "A claim in a capsule",
    lede: "A live culture in food is a recipe you can scan. A billion-CFU bottle is a supplement with a warehouse behind it. We score the pack we can see.",
    minutes: 4,
    image: "/images/vitamins.jpg",
    aisle: "vitamins",
    persona: ["gut", "shop"],
    relatedBarcodes: [],
    relatedIngredients: ["e464"],
    sections: [
      {
        heading: "Food still wins",
        body: "Yogurt with a short list, kefir, sauerkraut. You can see what you are eating. A capsule may help a specific strain after antibiotics — that is a clinician’s sentence, not an aisle one.",
      },
      {
        heading: "What we can score",
        body: "Sweeteners in gummies, dyes, a ‘proprietary blend’. The CFU number on the front is not a score. If the gummy looks like candy, it scores like candy.",
      },
      {
        heading: "How to shop it",
        body: "If your gut is loud, start with the emulsifier note and a week of short lists. Pills after that, with a name on the strain, not a cartoon.",
      },
    ],
  },
  {
    slug: "toddler-snacks",
    title: "Toddler snacks are an aisle, not a food group",
    kicker: "If it melts, check why",
    lede: "Puffs, melts, yogurt raisins, ‘veggie’ straws. Convenient. Often a starch, a flavour, and a health halo. Real food still fits in a bag.",
    minutes: 4,
    image: "/images/baby.jpg",
    aisle: "baby",
    persona: ["parent"],
    relatedBarcodes: [],
    relatedIngredients: ["e102", "sugar", "natural-flavour"],
    sections: [
      {
        heading: "Melts and puffs",
        body: "They dissolve so they are ‘safe’. They also teach a flavour of salt and sweetness that fruit does not have. A piece of banana, cheese, a toast strip: slower, and they still eat.",
      },
      {
        heading: "Yogurt in a pouch",
        body: "Often a dairy dessert with concentrate. Plain yogurt and a spoon still exist. Scan the pouch. If sugar is in the first three, it is a treat.",
      },
      {
        heading: "How to shop it",
        body: "One emergency puff for the bag is fine. A cupboard of them is a vending machine. The baby aisle is not a nutritionist. The disc is.",
      },
    ],
  },
];
