import type { HazardLevel, RiskClass } from "@/lib/scoring/types";
import { MORE_INGREDIENTS } from "./ingredients-more";

export type IngredientDef = {
  id: string;
  name: string;
  aliases: string[];
  inciCode?: string;
  eNumber?: string;
  hazard: HazardLevel;
  riskClass: RiskClass;
  kind: "food" | "cosmetic" | "both";
  isAdditive: boolean;
  description: string;
};

export const BASE_INGREDIENTS: IngredientDef[] = [
  // —— Food additives (E-numbers) ——
  {
    id: "e102",
    name: "Tartrazine",
    aliases: ["e102", "fd&c yellow 5", "yellow 5", "yellow 5 lake", "ci 19140", "fd and c yellow 5"],
    eNumber: "E102",
    hazard: "orange",
    riskClass: "moderate",
    kind: "both",
    isAdditive: true,
    description: "Azo dye linked to hyperactivity in sensitive children. EFSA ADI 7.5 mg/kg.",
  },
  {
    id: "e104",
    name: "Quinoline yellow",
    aliases: ["e104"],
    eNumber: "E104",
    hazard: "orange",
    riskClass: "moderate",
    kind: "food",
    isAdditive: true,
    description: "Synthetic dye. Southampton six colour; restricted in some markets.",
  },
  {
    id: "e110",
    name: "Sunset yellow FCF",
    aliases: ["e110", "yellow 6", "fd&c yellow 6", "yellow 6 lake", "fd and c yellow 6"],
    eNumber: "E110",
    hazard: "orange",
    riskClass: "moderate",
    kind: "food",
    isAdditive: true,
    description: "Azo dye associated with hypersensitivity and hyperactivity.",
  },
  {
    id: "e122",
    name: "Azorubine",
    aliases: ["e122", "carmoisine"],
    eNumber: "E122",
    hazard: "orange",
    riskClass: "moderate",
    kind: "food",
    isAdditive: true,
    description: "Red azo dye. Banned in some countries; Southampton six.",
  },
  {
    id: "e124",
    name: "Ponceau 4R",
    aliases: ["e124", "cochineal red a"],
    eNumber: "E124",
    hazard: "orange",
    riskClass: "moderate",
    kind: "food",
    isAdditive: true,
    description: "Synthetic red dye. Potential allergen; Southampton six.",
  },
  {
    id: "e129",
    name: "Allura red AC",
    aliases: ["e129", "red 40", "fd&c red 40", "red 40 lake", "fd and c red 40"],
    eNumber: "E129",
    hazard: "orange",
    riskClass: "moderate",
    kind: "food",
    isAdditive: true,
    description: "Widely used azo dye. Hyperactivity concern in children.",
  },
  {
    id: "e150c",
    name: "Ammonia caramel",
    aliases: ["e150c", "caramel color", "caramel colour", "e150d", "sulphite ammonia caramel"],
    eNumber: "E150c",
    hazard: "yellow",
    riskClass: "low",
    kind: "food",
    isAdditive: true,
    description: "May contain 4-methylimidazole (4-MEI), a possible carcinogen at high doses.",
  },
  {
    id: "e200",
    name: "Sorbic acid",
    aliases: ["e200"],
    eNumber: "E200",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Preservative considered low concern at authorised levels.",
  },
  {
    id: "e202",
    name: "Potassium sorbate",
    aliases: ["e202"],
    eNumber: "E202",
    hazard: "green",
    riskClass: "low",
    kind: "food",
    isAdditive: true,
    description: "Common preservative. Rare contact allergy; generally accepted.",
  },
  {
    id: "e211",
    name: "Sodium benzoate",
    aliases: ["e211", "benzoate"],
    eNumber: "E211",
    hazard: "orange",
    riskClass: "moderate",
    kind: "food",
    isAdditive: true,
    description: "Can form benzene with ascorbic acid. Hyperactivity concern with azo dyes.",
  },
  {
    id: "e220",
    name: "Sulphur dioxide",
    aliases: ["e220", "sulfur dioxide", "sulphites", "sulfites", "e221", "e222", "e223", "e224"],
    eNumber: "E220",
    hazard: "orange",
    riskClass: "moderate",
    kind: "food",
    isAdditive: true,
    description: "Allergen. Asthma trigger. Mandatory labelling above 10 mg/kg.",
  },
  {
    id: "e250",
    name: "Sodium nitrite",
    aliases: ["e250", "nitrite"],
    eNumber: "E250",
    hazard: "red",
    riskClass: "high",
    kind: "food",
    isAdditive: true,
    description: "Forms nitrosamines (IARC Group 1 in processed meat). Used to cure meat.",
  },
  {
    id: "e251",
    name: "Sodium nitrate",
    aliases: ["e251", "e252", "potassium nitrate", "nitrate"],
    eNumber: "E251",
    hazard: "red",
    riskClass: "high",
    kind: "food",
    isAdditive: true,
    description: "Converts to nitrite; associated with colorectal cancer in processed meat.",
  },
  {
    id: "e300",
    name: "Ascorbic acid",
    aliases: ["e300", "vitamin c", "ascorbate"],
    eNumber: "E300",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Vitamin C. Antioxidant with no toxicological concern at food levels.",
  },
  {
    id: "e322",
    name: "Lecithin",
    aliases: ["e322", "soya lecithin", "soy lecithin", "sunflower lecithin"],
    eNumber: "E322",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Emulsifier from soy or sunflower. Generally recognised as safe.",
  },
  {
    id: "e330",
    name: "Citric acid",
    aliases: ["e330"],
    eNumber: "E330",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Naturally occurring acidulant. No health concern at typical use.",
  },
  {
    id: "e338",
    name: "Phosphoric acid",
    aliases: ["e338", "phosphates", "e339", "e340", "e341"],
    eNumber: "E338",
    hazard: "yellow",
    riskClass: "low",
    kind: "food",
    isAdditive: true,
    description: "High phosphate load is associated with bone and kidney stress.",
  },
  {
    id: "e407",
    name: "Carrageenan",
    aliases: ["e407", "e407a"],
    eNumber: "E407",
    hazard: "orange",
    riskClass: "moderate",
    kind: "food",
    isAdditive: true,
    description: "Degraded carrageenan is inflammatory in animal studies. Debate continues.",
  },
  {
    id: "e415",
    name: "Xanthan gum",
    aliases: ["e415"],
    eNumber: "E415",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Fermentation gum. Well tolerated except in very high doses.",
  },
  {
    id: "e440",
    name: "Pectin",
    aliases: ["e440"],
    eNumber: "E440",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Fruit fiber gelling agent. Beneficial soluble fibre.",
  },
  {
    id: "e471",
    name: "Mono- and diglycerides of fatty acids",
    aliases: ["e471", "mono and diglycerides", "emulsifier"],
    eNumber: "E471",
    hazard: "yellow",
    riskClass: "low",
    kind: "food",
    isAdditive: true,
    description: "May contain residual processing contaminants. Nutritional quality is low.",
  },
  {
    id: "e500",
    name: "Sodium carbonates",
    aliases: ["e500", "sodium bicarbonate", "baking soda"],
    eNumber: "E500",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Raising agent. No toxicological concern.",
  },
  {
    id: "e621",
    name: "Monosodium glutamate",
    aliases: ["e621", "msg", "monosodium glutamate"],
    eNumber: "E621",
    hazard: "yellow",
    riskClass: "low",
    kind: "food",
    isAdditive: true,
    description: "Flavour enhancer. Safe for most; a subset reports sensitivity.",
  },
  {
    id: "e950",
    name: "Acesulfame K",
    aliases: ["e950", "acesulfame potassium", "ace-k"],
    eNumber: "E950",
    hazard: "orange",
    riskClass: "moderate",
    kind: "food",
    isAdditive: true,
    description: "Intense sweetener. Limited long-term data; gut microbiome questions.",
  },
  {
    id: "e951",
    name: "Aspartame",
    aliases: ["e951"],
    eNumber: "E951",
    hazard: "orange",
    riskClass: "moderate",
    kind: "food",
    isAdditive: true,
    description: "IARC Group 2B (possibly carcinogenic). Unsafe for PKU. EFSA ADI 40 mg/kg.",
  },
  {
    id: "e954",
    name: "Saccharin",
    aliases: ["e954"],
    eNumber: "E954",
    hazard: "yellow",
    riskClass: "low",
    kind: "food",
    isAdditive: true,
    description: "Oldest intense sweetener. Historical bladder-cancer concern not confirmed in humans.",
  },
  {
    id: "e955",
    name: "Sucralose",
    aliases: ["e955", "splenda"],
    eNumber: "E955",
    hazard: "yellow",
    riskClass: "low",
    kind: "food",
    isAdditive: true,
    description: "Chlorinated sweetener. Heat-degradation products are a concern in baking.",
  },
  {
    id: "e960",
    name: "Steviol glycosides",
    aliases: ["e960", "stevia", "stevia leaf extract"],
    eNumber: "E960",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Plant-derived sweetener. EFSA-approved, no notable risk at ADI.",
  },
  {
    id: "e320",
    name: "BHA",
    aliases: ["e320", "butylated hydroxyanisole", "bha"],
    eNumber: "E320",
    hazard: "red",
    riskClass: "high",
    kind: "both",
    isAdditive: true,
    description: "IARC Group 2B antioxidant. Endocrine activity suspected.",
  },
  {
    id: "e321",
    name: "BHT",
    aliases: ["e321", "butylated hydroxytoluene", "bht"],
    eNumber: "E321",
    hazard: "red",
    riskClass: "high",
    kind: "both",
    isAdditive: true,
    description: "Synthetic antioxidant. Endocrine disruptor concern; banned in some cosmetics.",
  },
  {
    id: "e1505",
    name: "Triethyl citrate",
    aliases: ["e1505"],
    eNumber: "E1505",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Foam stabiliser used in egg white. Low concern.",
  },
  {
    id: "sugar",
    name: "Sugar",
    aliases: ["sugar", "sucrose", "glucose-fructose syrup", "invert sugar", "cane sugar"],
    hazard: "yellow",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Nutritional concern captured by Nutri-Score, not an additive risk.",
  },
  {
    id: "hfcs",
    name: "Glucose-fructose syrup",
    aliases: ["high fructose corn syrup", "hfcs", "glucose-fructose", "isoglucose"],
    hazard: "yellow",
    riskClass: "low",
    kind: "food",
    isAdditive: false,
    description: "Metabolic load similar to sugar. Scored via the nutrition panel.",
  },
  {
    id: "palm-oil",
    name: "Palm oil",
    aliases: ["palm oil", "palm fat", "palmitic"],
    hazard: "yellow",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "High in saturated fat. Process contaminants (3-MCPD, glycidyl esters) in refined oils.",
  },
  {
    id: "water",
    name: "Water",
    aliases: ["water", "aqua", "purified water", "eau"],
    inciCode: "Aqua",
    hazard: "green",
    riskClass: "none",
    kind: "both",
    isAdditive: false,
    description: "Risk-free solvent and nutrient.",
  },
  {
    id: "salt",
    name: "Salt",
    aliases: ["salt", "sea salt", "sodium chloride"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Scored through the sodium axis of Nutri-Score.",
  },
  {
    id: "wheat-flour",
    name: "Wheat flour",
    aliases: ["wheat flour", "enriched flour", "flour"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Staple carbohydrate. Contains gluten.",
  },
  {
    id: "oats",
    name: "Oats",
    aliases: ["oats", "rolled oats", "oatmeal", "whole grain oats"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Whole grain with beta-glucan fibre.",
  },
  {
    id: "cocoa",
    name: "Cocoa",
    aliases: ["cocoa", "cocoa mass", "cocoa powder", "cocoa butter"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Source of flavanols. Fat content varies by product.",
  },
  {
    id: "milk",
    name: "Milk",
    aliases: ["milk", "skimmed milk powder", "whole milk", "milk powder", "whey", "whey powder", "butter"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Protein and calcium source. Allergen.",
  },
  {
    id: "hazelnut",
    name: "Hazelnuts",
    aliases: ["hazelnut", "hazelnuts"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Nut. Allergen. Favourable fat profile.",
  },
  {
    id: "almond",
    name: "Almonds",
    aliases: ["almond", "almonds", "almond butter"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Tree nut. Allergen. High in vitamin E and fibre.",
  },
  {
    id: "olive-oil",
    name: "Olive oil",
    aliases: ["olive oil", "extra virgin olive oil", "olea europaea"],
    inciCode: "Olea Europaea Fruit Oil",
    hazard: "green",
    riskClass: "none",
    kind: "both",
    isAdditive: false,
    description: "Monounsaturated fat. Extra-virgin retains polyphenols.",
  },
  {
    id: "yogurt-cultures",
    name: "Live cultures",
    aliases: ["yogurt cultures", "streptococcus thermophilus", "lactobacillus"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Fermentation cultures with no toxicological concern.",
  },
  {
    id: "tomato",
    name: "Tomato",
    aliases: ["tomato", "tomato paste", "tomatoes"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Fruit/vegetable contribution to Nutri-Score positive points.",
  },
  {
    id: "pork",
    name: "Pork",
    aliases: ["pork", "pork meat"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Muscle meat. Processing (nitrites, smoking) drives risk, not the meat itself.",
  },
  {
    id: "coffee",
    name: "Coffee",
    aliases: ["coffee", "caffeine"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Caffeine is a stimulant; not scored as a toxic additive.",
  },
  {
    id: "tea",
    name: "Tea",
    aliases: ["tea", "black tea", "green tea", "camellia sinensis"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Infusion. Polyphenols; no additive risk.",
  },
  {
    id: "carbon-dioxide",
    name: "Carbon dioxide",
    aliases: ["carbon dioxide", "e290", "co2"],
    eNumber: "E290",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Carbonation gas. No health concern.",
  },
  {
    id: "natural-flavour",
    name: "Natural flavouring",
    aliases: ["natural flavouring", "natural flavor", "flavouring", "flavoring"],
    hazard: "yellow",
    riskClass: "low",
    kind: "food",
    isAdditive: true,
    description: "Undisclosed mixture. Usually low toxicological risk, poor transparency.",
  },
  {
    id: "coconut-oil",
    name: "Coconut oil",
    aliases: ["coconut oil", "virgin coconut oil", "organic raw virgin coconut oil", "organic coconut oil"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "A saturated fat. Scored through the nutrition box, not as an extra.",
  },
  {
    id: "cashew",
    name: "Cashews",
    aliases: ["cashew", "cashews"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Tree nut. Allergen. Useful protein and fat.",
  },
  {
    id: "sunflower-seed",
    name: "Sunflower seeds",
    aliases: ["sunflower seeds", "sunflower seed", "organic sunflower seeds"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Seed. Fibre, fat, a little protein.",
  },
  {
    id: "pumpkin-seed",
    name: "Pumpkin seeds",
    aliases: ["pumpkin seeds", "pepitas", "organic pumpkin seeds"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Seed. Magnesium, fat, protein.",
  },
  {
    id: "chia",
    name: "Chia seeds",
    aliases: ["chia", "chia seeds", "organic chia seeds"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Seed. Fibre and omega-3 ALA.",
  },
  {
    id: "quinoa",
    name: "Quinoa",
    aliases: ["quinoa", "quinoa flakes", "organic quinoa flakes"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Ancient grain. Protein and fibre. A keep.",
  },
  {
    id: "cinnamon",
    name: "Cinnamon",
    aliases: ["cinnamon", "organic cinnamon"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Spice. Flavour, not a concern.",
  },
  {
    id: "potassium-bicarbonate",
    name: "Potassium bicarbonate",
    aliases: ["potassium bicarbonate"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "A mineral salt used to alkalinise water. Not a health extra and not a concern.",
  },
  {
    id: "magnesium-sulfate",
    name: "Magnesium sulfate",
    aliases: ["magnesium sulfate", "magnesium sulphate", "epsom"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "A mineral salt. Trace electrolyte, not a sugar or an additive risk.",
  },
  {
    id: "calcium-chloride",
    name: "Calcium chloride",
    aliases: ["calcium chloride"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "A mineral salt. Trace electrolyte in some waters; a firming agent in some tins.",
  },

  // —— Cosmetics ——
  {
    id: "methylparaben",
    name: "Methylparaben",
    aliases: ["methylparaben", "methyl paraben"],
    inciCode: "Methylparaben",
    hazard: "red",
    riskClass: "high",
    kind: "cosmetic",
    isAdditive: false,
    description: "Preservative with endocrine-disrupting activity. SCCS restricts longer-chain parabens.",
  },
  {
    id: "propylparaben",
    name: "Propylparaben",
    aliases: ["propylparaben", "propyl paraben"],
    inciCode: "Propylparaben",
    hazard: "red",
    riskClass: "high",
    kind: "cosmetic",
    isAdditive: false,
    description: "Endocrine disruptor. Restricted in EU leave-on products for children.",
  },
  {
    id: "butylparaben",
    name: "Butylparaben",
    aliases: ["butylparaben"],
    inciCode: "Butylparaben",
    hazard: "red",
    riskClass: "high",
    kind: "cosmetic",
    isAdditive: false,
    description: "Stronger endocrine activity than methylparaben. Tightly restricted.",
  },
  {
    id: "lilial",
    name: "Lilial",
    aliases: ["lilial", "butylphenyl methylpropional", "bmhca"],
    inciCode: "Butylphenyl Methylpropional",
    hazard: "red",
    riskClass: "high",
    kind: "cosmetic",
    isAdditive: false,
    description: "Banned in the EU (2022) as a reproductive toxicant.",
  },
  {
    id: "triclosan",
    name: "Triclosan",
    aliases: ["triclosan"],
    inciCode: "Triclosan",
    hazard: "red",
    riskClass: "high",
    kind: "cosmetic",
    isAdditive: false,
    description: "Antibacterial. Endocrine disruptor; banned in many wash-off products.",
  },
  {
    id: "dmdm",
    name: "DMDM hydantoin",
    aliases: ["dmdm hydantoin", "imidazolidinyl urea", "dmdm"],
    inciCode: "DMDM Hydantoin",
    hazard: "red",
    riskClass: "high",
    kind: "cosmetic",
    isAdditive: false,
    description: "Formaldehyde releaser. Sensitiser and possible carcinogen concern.",
  },
  {
    id: "mit",
    name: "Methylisothiazolinone",
    aliases: ["methylisothiazolinone", "mit", "kathon", "methylchloroisothiazolinone"],
    inciCode: "Methylisothiazolinone",
    hazard: "red",
    riskClass: "high",
    kind: "cosmetic",
    isAdditive: false,
    description: "Extreme contact allergen. Banned in leave-on EU cosmetics.",
  },
  {
    id: "oxybenzone",
    name: "Oxybenzone",
    aliases: ["oxybenzone", "benzophenone-3"],
    inciCode: "Benzophenone-3",
    hazard: "red",
    riskClass: "high",
    kind: "cosmetic",
    isAdditive: false,
    description: "UV filter. Endocrine activity and coral-reef toxicity. Restricted in several regions.",
  },
  {
    id: "octinoxate",
    name: "Octinoxate",
    aliases: ["octinoxate", "ethylhexyl methoxycinnamate"],
    inciCode: "Ethylhexyl Methoxycinnamate",
    hazard: "orange",
    riskClass: "moderate",
    kind: "cosmetic",
    isAdditive: false,
    description: "Chemical UV filter with endocrine activity signals.",
  },
  {
    id: "homosalate",
    name: "Homosalate",
    aliases: ["homosalate"],
    inciCode: "Homosalate",
    hazard: "orange",
    riskClass: "moderate",
    kind: "cosmetic",
    isAdditive: false,
    description: "UV filter. SCCS has recommended concentration limits.",
  },
  {
    id: "phenoxyethanol",
    name: "Phenoxyethanol",
    aliases: ["phenoxyethanol"],
    inciCode: "Phenoxyethanol",
    hazard: "orange",
    riskClass: "moderate",
    kind: "cosmetic",
    isAdditive: false,
    description: "Preservative. SCCS cap 1%. Irritant and possible neurotoxicity in infants at high dose.",
  },
  {
    id: "peg-40",
    name: "PEG-40 hydrogenated castor oil",
    aliases: ["peg-40 hydrogenated castor oil", "peg-40", "pegs", "peg-"],
    inciCode: "PEG-40 Hydrogenated Castor Oil",
    hazard: "orange",
    riskClass: "moderate",
    kind: "cosmetic",
    isAdditive: false,
    description: "May be contaminated with 1,4-dioxane. Barrier disruption on compromised skin.",
  },
  {
    id: "cyclopentasiloxane",
    name: "Cyclopentasiloxane",
    aliases: ["cyclopentasiloxane", "d5", "cyclomethicone"],
    inciCode: "Cyclopentasiloxane",
    hazard: "orange",
    riskClass: "moderate",
    kind: "cosmetic",
    isAdditive: false,
    description: "Volatile silicone. PBT environmental concern; wash-off restrictions in the EU.",
  },
  {
    id: "sls",
    name: "Sodium lauryl sulfate",
    aliases: ["sodium lauryl sulfate", "sls", "sodium dodecyl sulfate"],
    inciCode: "Sodium Lauryl Sulfate",
    hazard: "orange",
    riskClass: "moderate",
    kind: "cosmetic",
    isAdditive: false,
    description: "Harsh surfactant. Skin and eye irritant, especially in leave-on or high %. ",
  },
  {
    id: "sles",
    name: "Sodium laureth sulfate",
    aliases: ["sodium laureth sulfate", "sles"],
    inciCode: "Sodium Laureth Sulfate",
    hazard: "yellow",
    riskClass: "low",
    kind: "cosmetic",
    isAdditive: false,
    description: "Milder than SLS. 1,4-dioxane contamination possible if poorly purified.",
  },
  {
    id: "ci19140",
    name: "CI 19140",
    aliases: ["ci 19140", "yellow 5", "fd&c yellow no. 5"],
    inciCode: "CI 19140",
    hazard: "orange",
    riskClass: "moderate",
    kind: "cosmetic",
    isAdditive: false,
    description: "Tartrazine colourant. Sensitiser in cosmetics.",
  },
  {
    id: "fragrance",
    name: "Fragrance",
    aliases: ["fragrance", "parfum", "aroma", "perfume"],
    inciCode: "Parfum",
    hazard: "yellow",
    riskClass: "low",
    kind: "cosmetic",
    isAdditive: false,
    description: "Undisclosed mixture. Common contact allergen; may hide sensitising constituents.",
  },
  {
    id: "linalool",
    name: "Linalool",
    aliases: ["linalool"],
    inciCode: "Linalool",
    hazard: "yellow",
    riskClass: "low",
    kind: "cosmetic",
    isAdditive: false,
    description: "Fragrance allergen (EU 26). Oxidises to more allergenic hydroperoxides.",
  },
  {
    id: "limonene",
    name: "Limonene",
    aliases: ["limonene"],
    inciCode: "Limonene",
    hazard: "yellow",
    riskClass: "low",
    kind: "cosmetic",
    isAdditive: false,
    description: "Citrus terpene allergen. Forms allergenic oxides on air exposure.",
  },
  {
    id: "citronellol",
    name: "Citronellol",
    aliases: ["citronellol"],
    inciCode: "Citronellol",
    hazard: "yellow",
    riskClass: "low",
    kind: "cosmetic",
    isAdditive: false,
    description: "Declared fragrance allergen.",
  },
  {
    id: "geraniol",
    name: "Geraniol",
    aliases: ["geraniol"],
    inciCode: "Geraniol",
    hazard: "yellow",
    riskClass: "low",
    kind: "cosmetic",
    isAdditive: false,
    description: "Declared fragrance allergen, common in rose and geranium oils.",
  },
  {
    id: "benzyl-alcohol",
    name: "Benzyl alcohol",
    aliases: ["benzyl alcohol"],
    inciCode: "Benzyl Alcohol",
    hazard: "yellow",
    riskClass: "low",
    kind: "cosmetic",
    isAdditive: false,
    description: "Fragrance allergen and mild preservative.",
  },
  {
    id: "alcohol-denat",
    name: "Alcohol denat.",
    aliases: ["alcohol denat", "alcohol denat.", "ethanol"],
    inciCode: "Alcohol Denat.",
    hazard: "yellow",
    riskClass: "low",
    kind: "cosmetic",
    isAdditive: false,
    description: "Drying and potentially irritating on compromised skin.",
  },
  {
    id: "glycerin",
    name: "Glycerin",
    aliases: ["glycerin", "glycerol", "glycerine"],
    inciCode: "Glycerin",
    hazard: "green",
    riskClass: "none",
    kind: "both",
    isAdditive: false,
    description: "Humectant. Excellent safety profile.",
  },
  {
    id: "aloe",
    name: "Aloe vera",
    aliases: ["aloe vera", "aloe barbadensis", "aloe barbadensis leaf juice"],
    inciCode: "Aloe Barbadensis Leaf Juice",
    hazard: "green",
    riskClass: "none",
    kind: "cosmetic",
    isAdditive: false,
    description: "Soothing botanical. Rare allergy to latex-containing preparations.",
  },
  {
    id: "shea",
    name: "Shea butter",
    aliases: ["shea butter", "butyrospermum parkii", "vitellaria"],
    inciCode: "Butyrospermum Parkii Butter",
    hazard: "green",
    riskClass: "none",
    kind: "cosmetic",
    isAdditive: false,
    description: "Emollient rich in unsaponifiables. Risk-free.",
  },
  {
    id: "tocopherol",
    name: "Tocopherol",
    aliases: ["tocopherol", "vitamin e", "tocopheryl acetate"],
    inciCode: "Tocopherol",
    hazard: "green",
    riskClass: "none",
    kind: "both",
    isAdditive: false,
    description: "Antioxidant vitamin E. Excellent safety.",
  },
  {
    id: "niacinamide",
    name: "Niacinamide",
    aliases: ["niacinamide", "vitamin b3", "nicotinamide"],
    inciCode: "Niacinamide",
    hazard: "green",
    riskClass: "none",
    kind: "cosmetic",
    isAdditive: false,
    description: "Well-studied barrier-supporting vitamin.",
  },
  {
    id: "hyaluronic",
    name: "Hyaluronic acid",
    aliases: ["hyaluronic acid", "sodium hyaluronate"],
    inciCode: "Sodium Hyaluronate",
    hazard: "green",
    riskClass: "none",
    kind: "cosmetic",
    isAdditive: false,
    description: "Humectant glycosaminoglycan. Non-irritating.",
  },
  {
    id: "panthenol",
    name: "Panthenol",
    aliases: ["panthenol", "pro-vitamin b5"],
    inciCode: "Panthenol",
    hazard: "green",
    riskClass: "none",
    kind: "cosmetic",
    isAdditive: false,
    description: "Pro-vitamin B5. Soothing, well tolerated.",
  },
  {
    id: "squalane",
    name: "Squalane",
    aliases: ["squalane", "squalene"],
    inciCode: "Squalane",
    hazard: "green",
    riskClass: "none",
    kind: "cosmetic",
    isAdditive: false,
    description: "Skin-identical emollient, usually plant-derived.",
  },
  {
    id: "caprylic",
    name: "Caprylic/capric triglyceride",
    aliases: ["caprylic/capric triglyceride", "cct"],
    inciCode: "Caprylic/Capric Triglyceride",
    hazard: "green",
    riskClass: "none",
    kind: "cosmetic",
    isAdditive: false,
    description: "Fractionated coconut emollient. Excellent safety.",
  },
  {
    id: "cetearyl",
    name: "Cetearyl alcohol",
    aliases: ["cetearyl alcohol"],
    inciCode: "Cetearyl Alcohol",
    hazard: "green",
    riskClass: "none",
    kind: "cosmetic",
    isAdditive: false,
    description: "Fatty alcohol (not drying ethanol). Stabiliser and emollient.",
  },
  {
    id: "zinc-oxide",
    name: "Zinc oxide",
    aliases: ["zinc oxide"],
    inciCode: "Zinc Oxide",
    hazard: "green",
    riskClass: "none",
    kind: "cosmetic",
    isAdditive: false,
    description: "Mineral UV filter. Preferred over chemical filters for systemic exposure.",
  },
  {
    id: "titanium-dioxide",
    name: "Titanium dioxide",
    aliases: ["titanium dioxide", "ci 77891"],
    inciCode: "Titanium Dioxide",
    hazard: "yellow",
    riskClass: "low",
    kind: "cosmetic",
    isAdditive: false,
    description: "Mineral UV filter/pigment. Inhalation of powders is the main concern, not leave-on cream.",
  },
  {
    id: "cocamidopropyl",
    name: "Cocamidopropyl betaine",
    aliases: ["cocamidopropyl betaine"],
    inciCode: "Cocamidopropyl Betaine",
    hazard: "yellow",
    riskClass: "low",
    kind: "cosmetic",
    isAdditive: false,
    description: "Mild amphoteric surfactant. Impurity (amidoamine) can sensitise.",
  },
  {
    id: "decyl-glucoside",
    name: "Decyl glucoside",
    aliases: ["decyl glucoside", "coco glucoside", "lauryl glucoside"],
    inciCode: "Decyl Glucoside",
    hazard: "green",
    riskClass: "none",
    kind: "cosmetic",
    isAdditive: false,
    description: "Mild sugar-derived surfactant. Preferred over sulfates.",
  },
  {
    id: "dimethicone",
    name: "Dimethicone",
    aliases: ["dimethicone"],
    inciCode: "Dimethicone",
    hazard: "green",
    riskClass: "none",
    kind: "cosmetic",
    isAdditive: false,
    description: "Non-volatile silicone. Low human hazard; environmental persistence.",
  },
  {
    id: "cetyl-alcohol",
    name: "Cetyl alcohol",
    aliases: ["cetyl alcohol"],
    inciCode: "Cetyl Alcohol",
    hazard: "green",
    riskClass: "none",
    kind: "cosmetic",
    isAdditive: false,
    description: "Fatty alcohol emollient.",
  },
  {
    id: "e100",
    name: "Curcumin",
    aliases: ["e100", "curcumin"],
    eNumber: "E100",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Turmeric colour. No notable risk at authorised levels.",
  },
  {
    id: "e120",
    name: "Carmine",
    aliases: ["e120", "cochineal", "carminic acid"],
    eNumber: "E120",
    hazard: "yellow",
    riskClass: "low",
    kind: "food",
    isAdditive: true,
    description: "Insect-derived colour. Allergen reports exist; not vegan.",
  },
  {
    id: "e160a",
    name: "Carotenes",
    aliases: ["e160a", "beta-carotene"],
    eNumber: "E160a",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Pro-vitamin A colour. No toxicological concern.",
  },
  {
    id: "e200b",
    name: "Natamycin",
    aliases: ["e235", "natamycin"],
    eNumber: "E235",
    hazard: "yellow",
    riskClass: "low",
    kind: "food",
    isAdditive: true,
    description: "Antifungal used on cheese rinds.",
  },
  {
    id: "e420",
    name: "Sorbitol",
    aliases: ["e420", "sorbitol"],
    eNumber: "E420",
    hazard: "yellow",
    riskClass: "low",
    kind: "food",
    isAdditive: true,
    description: "Polyol sweetener. Laxative in high doses.",
  },
  {
    id: "e422",
    name: "Glycerol",
    aliases: ["e422", "glycerol"],
    eNumber: "E422",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Humectant identical to cosmetic glycerin.",
  },
  {
    id: "e428",
    name: "Gelatine",
    aliases: ["e428", "gelatine", "gelatin"],
    eNumber: "E428",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Animal protein. Not vegan or vegetarian for many consumers.",
  },
  {
    id: "e450",
    name: "Diphosphates",
    aliases: ["e450", "e451", "e452", "polyphosphates", "disodium diphosphate", "sodium acid pyrophosphate"],
    eNumber: "E450",
    hazard: "yellow",
    riskClass: "low",
    kind: "food",
    isAdditive: true,
    description: "Phosphate salts. High dietary phosphate is a kidney-load concern.",
  },
  {
    id: "e503",
    name: "Ammonium carbonates",
    aliases: ["e503", "ammonium bicarbonate", "ammonium carbonates"],
    eNumber: "E503",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Raising agent. No health concern.",
  },
  {
    id: "e952",
    name: "Cyclamate",
    aliases: ["e952", "cyclamate"],
    eNumber: "E952",
    hazard: "orange",
    riskClass: "moderate",
    kind: "food",
    isAdditive: true,
    description: "Intense sweetener banned in the US; authorised in the EU with an ADI.",
  },
  {
    id: "propylene-glycol",
    name: "Propylene glycol",
    aliases: ["propylene glycol", "e1520"],
    eNumber: "E1520",
    hazard: "orange",
    riskClass: "moderate",
    kind: "both",
    isAdditive: true,
    description: "Humectant. Controversial in pet food; generally accepted in human food.",
  },
  {
    id: "chicken",
    name: "Chicken",
    aliases: ["chicken", "chicken meal", "poultry"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Muscle meat. Quality depends on named-meat vs generic meal.",
  },
  {
    id: "honey",
    name: "Honey",
    aliases: ["honey"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Not vegan. Sugars captured by Nutri-Score.",
  },
  {
    id: "e260",
    name: "Acetic acid",
    aliases: ["e260", "spirit vinegar", "vinegar"],
    eNumber: "E260",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Vinegar acidulant. No toxicological concern at food levels.",
  },
  {
    id: "e301",
    name: "Sodium ascorbate",
    aliases: ["e301", "sodium ascorbate"],
    eNumber: "E301",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Vitamin C salt. Antioxidant used in cured meats.",
  },
  {
    id: "e331",
    name: "Sodium citrates",
    aliases: ["e331", "sodium citrate"],
    eNumber: "E331",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Acidity regulator. No notable risk.",
  },
  {
    id: "e412",
    name: "Guar gum",
    aliases: ["e412", "guar gum"],
    eNumber: "E412",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Seed-derived thickener. Well tolerated.",
  },
  {
    id: "e466",
    name: "Carboxymethyl cellulose",
    aliases: ["e466", "cellulose gum", "cmc"],
    eNumber: "E466",
    hazard: "yellow",
    riskClass: "low",
    kind: "food",
    isAdditive: true,
    description: "Emulsifier. Some evidence of gut-mucosa effects at high dose.",
  },
  {
    id: "e476",
    name: "Polyglycerol polyricinoleate",
    aliases: ["e476", "pgpr"],
    eNumber: "E476",
    hazard: "yellow",
    riskClass: "low",
    kind: "food",
    isAdditive: true,
    description: "Chocolate emulsifier. Low concern at authorised use.",
  },
  {
    id: "e141",
    name: "Copper chlorophyll",
    aliases: ["e141", "chlorophyllin"],
    eNumber: "E141",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Green colour from chlorophyll. Low concern.",
  },
  {
    id: "e163",
    name: "Anthocyanins",
    aliases: ["e163"],
    eNumber: "E163",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Fruit pigment colour. No notable risk.",
  },
  {
    id: "e501",
    name: "Potassium carbonates",
    aliases: ["e501"],
    eNumber: "E501",
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: true,
    description: "Raising agent. No health concern.",
  },
  {
    id: "e339",
    name: "Sodium phosphates",
    aliases: ["e339"],
    eNumber: "E339",
    hazard: "yellow",
    riskClass: "low",
    kind: "food",
    isAdditive: true,
    description: "Phosphate salt. Dietary phosphate load is a kidney concern at high intake.",
  },
  {
    id: "e150d",
    name: "Sulphite ammonia caramel",
    aliases: ["e150d"],
    eNumber: "E150d",
    hazard: "yellow",
    riskClass: "low",
    kind: "food",
    isAdditive: true,
    description: "Caramel colour used in colas. 4-MEI impurity is the main concern.",
  },
  {
    id: "spice",
    name: "Spice extract",
    aliases: ["spice", "spices", "herb extracts", "spice and herb extracts"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Culinary spices. Allergen risk depends on the plant (celery, mustard, sesame).",
  },
  {
    id: "vanilla",
    name: "Vanilla",
    aliases: ["vanilla", "vanillin", "vanilla extract"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Flavour. Synthetic vanillin is nutritionally empty but low-risk.",
  },
  {
    id: "sesame",
    name: "Sesame",
    aliases: ["sesame", "sesame seeds", "tahini", "sesame oil"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Seed. EU major allergen.",
  },
  {
    id: "celery",
    name: "Celery",
    aliases: ["celery", "celery extract", "celeriac"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "EU major allergen, often hidden in spice mixes.",
  },
  {
    id: "mustard",
    name: "Mustard",
    aliases: ["mustard", "mustard seed"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "EU major allergen.",
  },
  {
    id: "egg",
    name: "Egg",
    aliases: ["egg", "eggs", "egg white", "albumin"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "EU major allergen. Protein source.",
  },
  {
    id: "peanut",
    name: "Peanut",
    aliases: ["peanut", "peanuts", "groundnut"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "EU major allergen. Tree-nut-adjacent but labelled separately.",
  },
  {
    id: "fish",
    name: "Fish",
    aliases: ["fish", "fish oil", "anchovy"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "EU major allergen. Omega-3 source; mercury depends on species.",
  },
  {
    id: "sunflower-oil",
    name: "Sunflower oil",
    aliases: ["sunflower oil", "sunflower", "rapeseed oil", "canola oil"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Seed oil. Nutritional quality depends on refinement and omega-6 load.",
  },
  {
    id: "potato",
    name: "Potato",
    aliases: ["potato", "potatoes"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Staple starch. Acrylamide forms in high-heat frying.",
  },
  {
    id: "cheddar",
    name: "Cheddar",
    aliases: ["cheddar", "cheddar cheese", "cheese"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Aged cheese. Protein always counts in Nutri-Score 2023.",
  },
  {
    id: "beef",
    name: "Beef",
    aliases: ["beef", "beef mince", "steak"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Red meat. Nutri-Score 2023 caps protein points.",
  },
  {
    id: "retinol",
    name: "Retinol",
    aliases: ["retinol", "retinyl palmitate", "vitamin a"],
    inciCode: "Retinol",
    hazard: "orange",
    riskClass: "moderate",
    kind: "cosmetic",
    isAdditive: false,
    description: "Vitamin A derivative. Avoid high-strength leave-on during pregnancy.",
  },
  {
    id: "salicylic",
    name: "Salicylic acid",
    aliases: ["salicylic acid", "bha acid"],
    inciCode: "Salicylic Acid",
    hazard: "orange",
    riskClass: "moderate",
    kind: "cosmetic",
    isAdditive: false,
    description: "Beta-hydroxy acid. Not recommended in high % during pregnancy.",
  },
  {
    id: "sodium-fluoride",
    name: "Sodium fluoride",
    aliases: ["sodium fluoride"],
    inciCode: "Sodium Fluoride",
    hazard: "yellow",
    riskClass: "low",
    kind: "cosmetic",
    isAdditive: false,
    description: "Caries prevention at toothpaste doses. Do not swallow.",
  },
  {
    id: "hydroxyapatite",
    name: "Hydroxyapatite",
    aliases: ["hydroxyapatite", "nano-hydroxyapatite"],
    inciCode: "Hydroxyapatite",
    hazard: "green",
    riskClass: "none",
    kind: "cosmetic",
    isAdditive: false,
    description: "Tooth-mineral analogue used in fluoride-free pastes.",
  },
  {
    id: "corn",
    name: "Corn",
    aliases: ["corn", "maize", "corn meal", "corn flour", "milled corn"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Staple grain. Fine as food; the extras around it usually decide the score.",
  },
  {
    id: "soy",
    name: "Soy",
    aliases: ["soy", "soya", "soybean", "soy protein", "soy sauce"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "EU major allergen. Protein source; isolate and concentrate are factory ingredients.",
  },
  {
    id: "rice",
    name: "Rice",
    aliases: ["rice", "rice flour", "brown rice", "white rice"],
    hazard: "green",
    riskClass: "none",
    kind: "food",
    isAdditive: false,
    description: "Staple grain. Whole grain is the better neighbour of white rice.",
  },
  {
    id: "e171",
    name: "Titanium dioxide",
    aliases: ["e171", "titanium dioxide", "ci 77891"],
    eNumber: "E171",
    hazard: "red",
    riskClass: "high",
    kind: "both",
    isAdditive: true,
    description: "Whitener. Banned as a food additive in the EU. Genotoxicity concerns at the nanoparticle size used in food.",
  },
  {
    id: "e319",
    name: "TBHQ",
    aliases: ["e319", "tbhq", "tertiary butylhydroquinone"],
    eNumber: "E319",
    hazard: "orange",
    riskClass: "moderate",
    kind: "food",
    isAdditive: true,
    description: "Synthetic antioxidant in frying oils and packaged snacks. EFSA ADI is tight; we flag it.",
  },
  {
    id: "e133",
    name: "Brilliant blue FCF",
    aliases: ["e133", "blue 1", "fd&c blue 1"],
    eNumber: "E133",
    hazard: "orange",
    riskClass: "moderate",
    kind: "food",
    isAdditive: true,
    description: "Synthetic dye. Hyperactivity concern in sensitive children when stacked with other azo colours.",
  },
  {
    id: "e127",
    name: "Erythrosine",
    aliases: ["e127", "red 3", "fd&c red 3"],
    eNumber: "E127",
    hazard: "red",
    riskClass: "high",
    kind: "food",
    isAdditive: true,
    description: "Red dye. FDA moved to revoke authorisation after thyroid-tumour evidence in animals.",
  },
  {
    id: "e433",
    name: "Polysorbate 80",
    aliases: ["e433", "polysorbate 80", "tween 80"],
    eNumber: "E433",
    hazard: "orange",
    riskClass: "moderate",
    kind: "both",
    isAdditive: true,
    description: "Emulsifier used in ice cream and injections. Gut-barrier research is enough for us to mark it.",
  },
];

export const INGREDIENTS: IngredientDef[] = (() => {
  const seen = new Set<string>();
  const out: IngredientDef[] = [];
  for (const ing of [...BASE_INGREDIENTS, ...MORE_INGREDIENTS]) {
    if (seen.has(ing.id)) continue;
    seen.add(ing.id);
    out.push(ing);
  }
  return out;
})();
export const INGREDIENT_BY_ID = new Map(INGREDIENTS.map((i) => [i.id, i]));
