import type { Nutrition, ProductType } from "@/lib/scoring/types";
import { MORE_PRODUCTS } from "./products-more";
import { WORLD_PRODUCTS } from "./products-world";
import { SHELF_PRODUCTS } from "./products-shelf";
import { CART_PRODUCTS } from "./products-cart";
import { AISLE_PRODUCTS } from "./products-aisles";
import { EXTRA_PRODUCTS } from "./products-extra";
import { PREMIUM_PRODUCTS } from "./products-premium";
import { DENSE_PRODUCTS } from "./products-dense";
import { isDemoBarcode, isDemoBrand } from "./quality";

export type ProductDef = {
  barcode: string;
  title: string;
  brand: string;
  type: ProductType;
  categoryPath: string;
  isOrganic: boolean;
  isBeverage?: boolean;
  isWater?: boolean;
  ingredientIds: string[];
  ingredientsText: string;
  nutrition?: Nutrition;
  imageUrl?: string;
  novaGroup?: number;
};

const CORE_PRODUCTS: ProductDef[] = [
  {
    barcode: "5449000000996",
    title: "Coca-Cola Classic",
    brand: "Coca-Cola",
    type: "food",
    categoryPath: "beverages",
    isOrganic: false,
    isBeverage: true,
    ingredientIds: ["water", "sugar", "e330", "e150c", "e338", "natural-flavour", "carbon-dioxide"],
    ingredientsText:
      "Carbonated water, sugar, colour (E150d), phosphoric acid (E338), natural flavourings including caffeine.",
    nutrition: {
      energyKj: 180,
      sugars: 10.6,
      saturatedFat: 0,
      salt: 0,
      fiber: 0,
      protein: 0,
      fruitsVegetables: 0,
    },
    imageUrl: "/images/beverages.jpg",
    novaGroup: 4,
  },
  {
    barcode: "8002270014901",
    title: "S.Pellegrino Sparkling Mineral Water",
    brand: "S.Pellegrino",
    type: "food",
    categoryPath: "beverages",
    isOrganic: false,
    isBeverage: true,
    isWater: true,
    ingredientIds: ["water", "carbon-dioxide"],
    ingredientsText: "Natural mineral water, carbon dioxide.",
    nutrition: {
      energyKj: 0,
      sugars: 0,
      saturatedFat: 0,
      salt: 0.03,
      fiber: 0,
      protein: 0,
      fruitsVegetables: 0,
    },
    imageUrl: "/images/beverages.jpg",
    novaGroup: 1,
  },
  {
    barcode: "3274080005003",
    title: "Evian Natural Mineral Water",
    brand: "Evian",
    type: "food",
    categoryPath: "beverages",
    isOrganic: false,
    isBeverage: true,
    isWater: true,
    ingredientIds: ["water"],
    ingredientsText: "Natural mineral water.",
    nutrition: {
      energyKj: 0,
      sugars: 0,
      saturatedFat: 0,
      salt: 0.001,
      fiber: 0,
      protein: 0,
      fruitsVegetables: 0,
    },
    novaGroup: 1,
  },
  {
    barcode: "5010029214439",
    title: "Pure Leaf Unsweetened Iced Tea",
    brand: "Pure Leaf",
    type: "food",
    categoryPath: "beverages",
    isOrganic: false,
    isBeverage: true,
    ingredientIds: ["water", "tea"],
    ingredientsText: "Brewed tea, water.",
    nutrition: {
      energyKj: 4,
      sugars: 0,
      saturatedFat: 0,
      salt: 0.01,
      fiber: 0,
      protein: 0,
      fruitsVegetables: 0,
    },
    novaGroup: 1,
  },
  {
    barcode: "9002490100070",
    title: "Red Bull Energy Drink",
    brand: "Red Bull",
    type: "food",
    categoryPath: "beverages",
    isOrganic: false,
    isBeverage: true,
    ingredientIds: ["water", "sugar", "e330", "e202", "e950", "e951", "e300", "natural-flavour"],
    ingredientsText:
      "Water, sucrose, glucose, acid (E330), carbon dioxide, taurine, acidity regulator (E331), caffeine, flavourings, inositol, colours, vitamins, sweeteners (E950, E951).",
    nutrition: {
      energyKj: 192,
      sugars: 11,
      saturatedFat: 0,
      salt: 0.1,
      fiber: 0,
      protein: 0,
      fruitsVegetables: 0,
    },
    novaGroup: 4,
  },
  {
    barcode: "3017620422003",
    title: "Nutella",
    brand: "Ferrero",
    type: "food",
    categoryPath: "spreads",
    isOrganic: false,
    ingredientIds: ["sugar", "palm-oil", "hazelnut", "cocoa", "milk", "e322", "e500"],
    ingredientsText:
      "Sugar, palm oil, hazelnuts (13%), skimmed milk powder (8.7%), fat-reduced cocoa (7.4%), emulsifier: lecithins (soya) (E322), vanillin.",
    nutrition: {
      energyKj: 2252,
      sugars: 56.3,
      saturatedFat: 10.6,
      salt: 0.107,
      fiber: 0,
      protein: 6.3,
      fruitsVegetables: 13,
      fat: 30.9,
    },
    novaGroup: 4,
  },
  {
    barcode: "8500108320157",
    title: "Organic Almond Butter",
    brand: "Healthie Pantry",
    type: "food",
    categoryPath: "spreads",
    isOrganic: true,
    ingredientIds: ["almond"],
    ingredientsText: "Organic dry-roasted almonds.",
    nutrition: {
      energyKj: 2500,
      sugars: 4.4,
      saturatedFat: 3.7,
      salt: 0,
      fiber: 10.3,
      protein: 21,
      fruitsVegetables: 100,
      fat: 53,
    },
    novaGroup: 1,
  },
  {
    barcode: "8500108320164",
    title: "Stone-Ground Tahini",
    brand: "Healthie Pantry",
    type: "food",
    categoryPath: "spreads",
    isOrganic: true,
    ingredientIds: ["sesame"],
    ingredientsText: "Organic sesame seeds.",
    nutrition: {
      energyKj: 2480,
      sugars: 0.5,
      saturatedFat: 7.5,
      salt: 0.05,
      fiber: 9.3,
      protein: 17,
      fruitsVegetables: 100,
      fat: 54,
    },
    novaGroup: 1,
  },
  {
    barcode: "5000328722751",
    title: "Walkers Ready Salted",
    brand: "Walkers",
    type: "food",
    categoryPath: "snacks",
    isOrganic: false,
    ingredientIds: ["potato", "sunflower-oil", "salt"],
    ingredientsText: "Potatoes, vegetable oils (sunflower, rapeseed), salt.",
    nutrition: {
      energyKj: 2193,
      sugars: 0.4,
      saturatedFat: 2.4,
      salt: 1.3,
      fiber: 4.3,
      protein: 6.1,
      fruitsVegetables: 0,
      fat: 32,
    },
    novaGroup: 4,
  },
  {
    barcode: "8500108320171",
    title: "Dry-Roasted Mixed Nuts",
    brand: "Healthie Pantry",
    type: "food",
    categoryPath: "snacks",
    isOrganic: true,
    ingredientIds: ["almond", "hazelnut"],
    ingredientsText: "Organic almonds, hazelnuts, cashews, walnuts.",
    nutrition: {
      energyKj: 2500,
      sugars: 4.2,
      saturatedFat: 6.5,
      salt: 0,
      fiber: 8.5,
      protein: 18,
      fruitsVegetables: 100,
      fat: 52,
    },
    novaGroup: 1,
  },
  {
    barcode: "7622300336738",
    title: "Oreo Original",
    brand: "Mondelez",
    type: "food",
    categoryPath: "snacks",
    isOrganic: false,
    ingredientIds: ["wheat-flour", "sugar", "palm-oil", "e322", "e500", "e150c", "salt"],
    ingredientsText:
      "Wheat flour, sugar, palm oil, fat-reduced cocoa powder, wheat starch, glucose-fructose syrup, raising agents (E503, E500, E501), salt, emulsifier (soya lecithin E322), flavouring.",
    nutrition: {
      energyKj: 1998,
      sugars: 38,
      saturatedFat: 5.2,
      salt: 0.74,
      fiber: 2.7,
      protein: 5.3,
      fruitsVegetables: 0,
      fat: 20,
    },
    novaGroup: 4,
  },
  {
    barcode: "3033490004521",
    title: "Activia Strawberry Yogurt",
    brand: "Danone",
    type: "food",
    categoryPath: "dairy",
    isOrganic: false,
    ingredientIds: ["milk", "sugar", "e440", "yogurt-cultures", "natural-flavour"],
    ingredientsText:
      "Yogurt (milk), sugar, strawberry (8%), thickeners (E440, E412), flavourings, colour (E163), bifidobacterium.",
    nutrition: {
      energyKj: 405,
      sugars: 13.4,
      saturatedFat: 1.7,
      salt: 0.13,
      fiber: 0.2,
      protein: 3.7,
      fruitsVegetables: 8,
      fat: 2.9,
    },
    novaGroup: 4,
  },
  {
    barcode: "8500108320188",
    title: "Plain Greek Yogurt 0%",
    brand: "Healthie Dairy",
    type: "food",
    categoryPath: "dairy",
    isOrganic: true,
    ingredientIds: ["milk", "yogurt-cultures"],
    ingredientsText: "Organic skimmed milk, live cultures.",
    nutrition: {
      energyKj: 243,
      sugars: 4,
      saturatedFat: 0.1,
      salt: 0.1,
      fiber: 0,
      protein: 10,
      fruitsVegetables: 0,
      fat: 0.2,
    },
    novaGroup: 1,
  },
  {
    barcode: "5000159407236",
    title: "Coco Pops",
    brand: "Kellogg's",
    type: "food",
    categoryPath: "breakfast",
    isOrganic: false,
    ingredientIds: ["sugar", "cocoa", "salt", "e322", "natural-flavour"],
    ingredientsText:
      "Rice, sugar, cocoa (3%), salt, barley malt flavouring, vitamins and minerals. May contain gluten.",
    nutrition: {
      energyKj: 1617,
      sugars: 30,
      saturatedFat: 0.9,
      salt: 0.65,
      fiber: 1.8,
      protein: 5.5,
      fruitsVegetables: 0,
      fat: 1.9,
    },
    novaGroup: 4,
  },
  {
    barcode: "8500108320195",
    title: "Organic Rolled Oats",
    brand: "Healthie Pantry",
    type: "food",
    categoryPath: "breakfast",
    isOrganic: true,
    ingredientIds: ["oats"],
    ingredientsText: "Organic whole grain rolled oats.",
    nutrition: {
      energyKj: 1543,
      sugars: 1.1,
      saturatedFat: 1.3,
      salt: 0.01,
      fiber: 10,
      protein: 13.5,
      fruitsVegetables: 0,
      fat: 7,
    },
    imageUrl: "/images/hero.jpg",
    novaGroup: 1,
  },
  {
    barcode: "8715700110622",
    title: "Heinz Tomato Ketchup",
    brand: "Heinz",
    type: "food",
    categoryPath: "condiments",
    isOrganic: false,
    ingredientIds: ["tomato", "sugar", "salt", "e260", "spice", "celery"],
    ingredientsText:
      "Tomatoes (148 g per 100 ml), spirit vinegar, sugar, salt, spice and herb extracts (contain celery), spice.",
    nutrition: {
      energyKj: 435,
      sugars: 22.8,
      saturatedFat: 0,
      salt: 1.8,
      fiber: 0.7,
      protein: 1.2,
      fruitsVegetables: 80,
      fat: 0.1,
    },
    novaGroup: 4,
  },
  {
    barcode: "8500108320201",
    title: "Crushed Tomato Passata",
    brand: "Healthie Pantry",
    type: "food",
    categoryPath: "condiments",
    isOrganic: true,
    ingredientIds: ["tomato", "salt"],
    ingredientsText: "Organic tomatoes, sea salt.",
    nutrition: {
      energyKj: 140,
      sugars: 4.2,
      saturatedFat: 0,
      salt: 0.3,
      fiber: 1.5,
      protein: 1.4,
      fruitsVegetables: 100,
      fat: 0.2,
    },
    novaGroup: 1,
  },
  {
    barcode: "4000417025005",
    title: "Haribo Goldbears",
    brand: "Haribo",
    type: "food",
    categoryPath: "snacks",
    isOrganic: false,
    ingredientIds: ["sugar", "e330", "e422", "e428", "e102", "e110", "e129", "e104"],
    ingredientsText:
      "Glucose syrup, sugar, gelatine, dextrose, fruit juice from concentrate, acid (E330), flavouring, fruit and plant concentrates, colours (E100, E120, E141), glazing agents, citric acid.",
    nutrition: {
      energyKj: 1456,
      sugars: 56,
      saturatedFat: 0.1,
      salt: 0.07,
      fiber: 0,
      protein: 6.9,
      fruitsVegetables: 2,
      fat: 0.5,
    },
    novaGroup: 4,
  },
  {
    barcode: "3046920029759",
    title: "Lindt Excellence 85% Cocoa",
    brand: "Lindt",
    type: "food",
    categoryPath: "chocolate",
    isOrganic: false,
    ingredientIds: ["cocoa", "sugar", "e322", "vanilla"],
    ingredientsText: "Cocoa mass, cocoa powder, cocoa butter, sugar, vanilla, soy lecithin (E322).",
    nutrition: {
      energyKj: 2410,
      sugars: 11,
      saturatedFat: 26,
      salt: 0.02,
      fiber: 13,
      protein: 12.5,
      fruitsVegetables: 0,
      fat: 46,
    },
    novaGroup: 3,
  },
  {
    barcode: "8500108320218",
    title: "Organic 90% Dark Chocolate",
    brand: "Healthie Pantry",
    type: "food",
    categoryPath: "chocolate",
    isOrganic: true,
    ingredientIds: ["cocoa", "sugar"],
    ingredientsText: "Organic cocoa mass, organic cocoa butter, organic cane sugar.",
    nutrition: {
      energyKj: 2500,
      sugars: 6,
      saturatedFat: 22,
      salt: 0.01,
      fiber: 16,
      protein: 12,
      fruitsVegetables: 0,
      fat: 50,
    },
    novaGroup: 2,
  },
  {
    barcode: "3181232140562",
    title: "Herta Parisian Ham",
    brand: "Herta",
    type: "food",
    categoryPath: "staples",
    isOrganic: false,
    ingredientIds: ["pork", "salt", "e250", "e301", "e407", "e621"],
    ingredientsText:
      "Pork, salt, dextrose, flavourings, antioxidant (E301), preservative (sodium nitrite E250), fermented rice.",
    nutrition: {
      energyKj: 460,
      sugars: 0.5,
      saturatedFat: 1.3,
      salt: 1.8,
      fiber: 0,
      protein: 19,
      fruitsVegetables: 0,
      fat: 3.2,
    },
    novaGroup: 4,
  },
  {
    barcode: "8076809513724",
    title: "Barilla Spaghetti n.5",
    brand: "Barilla",
    type: "food",
    categoryPath: "staples",
    isOrganic: false,
    ingredientIds: ["wheat-flour"],
    ingredientsText: "Durum wheat semolina, water.",
    nutrition: {
      energyKj: 1521,
      sugars: 3.5,
      saturatedFat: 0.5,
      salt: 0.013,
      fiber: 3,
      protein: 13,
      fruitsVegetables: 0,
      fat: 2,
    },
    novaGroup: 1,
  },
  {
    barcode: "8500108320300",
    title: "Bloom Daily Lotion",
    brand: "Maison Bloom",
    type: "cosmetic",
    categoryPath: "skincare",
    isOrganic: false,
    ingredientIds: [
      "water",
      "glycerin",
      "fragrance",
      "methylparaben",
      "propylparaben",
      "phenoxyethanol",
      "peg-40",
      "linalool",
      "limonene",
      "ci19140",
    ],
    ingredientsText:
      "Aqua, Glycerin, Parfum, PEG-40 Hydrogenated Castor Oil, Methylparaben, Propylparaben, Phenoxyethanol, Linalool, Limonene, CI 19140.",
    imageUrl: "/images/skincare.jpg",
  },
  {
    barcode: "8500108320317",
    title: "Shea Leaf Balm",
    brand: "Grove Atelier",
    type: "cosmetic",
    categoryPath: "skincare",
    isOrganic: true,
    ingredientIds: ["shea", "olive-oil", "tocopherol", "squalane", "caprylic"],
    ingredientsText:
      "Butyrospermum Parkii Butter, Olea Europaea Fruit Oil, Squalane, Caprylic/Capric Triglyceride, Tocopherol.",
    imageUrl: "/images/skincare.jpg",
  },
  {
    barcode: "8500108320324",
    title: "Clear Niacinamide Serum",
    brand: "Grove Atelier",
    type: "cosmetic",
    categoryPath: "skincare",
    isOrganic: false,
    ingredientIds: ["water", "glycerin", "niacinamide", "hyaluronic", "panthenol", "tocopherol"],
    ingredientsText:
      "Aqua, Glycerin, Niacinamide, Sodium Hyaluronate, Panthenol, Tocopherol.",
    imageUrl: "/images/skincare.jpg",
  },
  {
    barcode: "8500108320331",
    title: "SilkShine Shampoo",
    brand: "Maison Bloom",
    type: "cosmetic",
    categoryPath: "hair",
    isOrganic: false,
    ingredientIds: ["water", "sls", "sles", "dmdm", "mit", "fragrance", "ci19140", "peg-40"],
    ingredientsText:
      "Aqua, Sodium Lauryl Sulfate, Sodium Laureth Sulfate, Cocamidopropyl Betaine, DMDM Hydantoin, Methylisothiazolinone, Parfum, PEG-40 Hydrogenated Castor Oil, CI 19140.",
  },
  {
    barcode: "8500108320348",
    title: "Oat Milk Shampoo",
    brand: "Grove Atelier",
    type: "cosmetic",
    categoryPath: "hair",
    isOrganic: true,
    ingredientIds: ["water", "decyl-glucoside", "glycerin", "aloe", "panthenol", "tocopherol"],
    ingredientsText:
      "Aqua, Decyl Glucoside, Glycerin, Aloe Barbadensis Leaf Juice, Panthenol, Tocopherol.",
  },
  {
    barcode: "8500108320355",
    title: "Sunburst SPF 30",
    brand: "Maison Bloom",
    type: "cosmetic",
    categoryPath: "sun",
    isOrganic: false,
    ingredientIds: [
      "water",
      "oxybenzone",
      "octinoxate",
      "homosalate",
      "fragrance",
      "cyclopentasiloxane",
      "phenoxyethanol",
    ],
    ingredientsText:
      "Aqua, Homosalate, Ethylhexyl Methoxycinnamate, Benzophenone-3, Cyclopentasiloxane, Parfum, Phenoxyethanol.",
  },
  {
    barcode: "8500108320362",
    title: "Mineral Shield SPF 30",
    brand: "Grove Atelier",
    type: "cosmetic",
    categoryPath: "sun",
    isOrganic: true,
    ingredientIds: ["zinc-oxide", "caprylic", "shea", "tocopherol", "cetearyl"],
    ingredientsText:
      "Zinc Oxide, Caprylic/Capric Triglyceride, Butyrospermum Parkii Butter, Cetearyl Alcohol, Tocopherol.",
  },
  {
    barcode: "8500108320379",
    title: "Citrus Body Wash",
    brand: "Maison Bloom",
    type: "cosmetic",
    categoryPath: "body",
    isOrganic: false,
    ingredientIds: ["water", "sls", "fragrance", "lilial", "limonene", "linalool", "mit"],
    ingredientsText:
      "Aqua, Sodium Lauryl Sulfate, Parfum, Butylphenyl Methylpropional, Limonene, Linalool, Methylisothiazolinone.",
  },
  {
    barcode: "8500108320386",
    title: "Olive Castile Wash",
    brand: "Grove Atelier",
    type: "cosmetic",
    categoryPath: "body",
    isOrganic: true,
    ingredientIds: ["water", "olive-oil", "glycerin", "tocopherol", "aloe"],
    ingredientsText:
      "Aqua, Potassium Olivate, Glycerin, Aloe Barbadensis Leaf Juice, Tocopherol.",
  },
  {
    barcode: "8500108320409",
    title: "Yard Kibble Chicken",
    brand: "Maison Bloom Pets",
    type: "pet",
    categoryPath: "pet",
    isOrganic: false,
    ingredientIds: ["chicken", "wheat-flour", "e320", "e102", "propylene-glycol", "e407", "salt"],
    ingredientsText:
      "Chicken by-product meal, wheat flour, animal fat, propylene glycol, BHA (E320), tartrazine (E102), carrageenan (E407), salt.",
    nutrition: {
      energyKj: 1450,
      sugars: 2,
      saturatedFat: 6,
      salt: 1.1,
      fiber: 2,
      protein: 18,
      fruitsVegetables: 0,
      fat: 12,
    },
    novaGroup: 4,
  },
  {
    barcode: "8500108320416",
    title: "Open Pasture Dog Food",
    brand: "Grove Atelier Pets",
    type: "pet",
    categoryPath: "pet",
    isOrganic: true,
    ingredientIds: ["chicken", "oats", "tocopherol"],
    ingredientsText: "Organic chicken, organic oats, mixed tocopherols.",
    nutrition: {
      energyKj: 1600,
      sugars: 1.2,
      saturatedFat: 3.5,
      salt: 0.4,
      fiber: 3.5,
      protein: 32,
      fruitsVegetables: 0,
      fat: 14,
    },
    novaGroup: 1,
  },
  {
    barcode: "8002270001234",
    title: "Extra Virgin Olive Oil",
    brand: "Healthie Pantry",
    type: "food",
    categoryPath: "spreads",
    isOrganic: true,
    ingredientIds: ["olive-oil"],
    ingredientsText: "Organic extra virgin olive oil.",
    nutrition: {
      energyKj: 3389,
      sugars: 0,
      saturatedFat: 14,
      salt: 0,
      fiber: 0,
      protein: 0,
      fruitsVegetables: 100,
      fat: 91,
    },
    novaGroup: 2,
  },
  {
    barcode: "8500108320508",
    title: "Clothbound Cheddar",
    brand: "Healthie Dairy",
    type: "food",
    categoryPath: "dairy",
    isOrganic: true,
    ingredientIds: ["cheddar", "milk", "salt"],
    ingredientsText: "Organic milk, salt, cultures, vegetarian rennet.",
    nutrition: {
      energyKj: 1700,
      sugars: 0.1,
      saturatedFat: 21,
      salt: 1.8,
      fiber: 0,
      protein: 25,
      fruitsVegetables: 0,
      fat: 34,
    },
    novaGroup: 3,
  },
  {
    barcode: "5010029000000",
    title: "Tropicana Pure Premium",
    brand: "Tropicana",
    type: "food",
    categoryPath: "beverages",
    isOrganic: false,
    isBeverage: true,
    ingredientIds: ["water", "sugar", "e300"],
    ingredientsText: "Orange juice from concentrate, ascorbic acid (E300).",
    nutrition: {
      energyKj: 183,
      sugars: 9.8,
      saturatedFat: 0,
      salt: 0,
      fiber: 0.3,
      protein: 0.6,
      fruitsVegetables: 100,
    },
    novaGroup: 1,
  },
  {
    barcode: "8500108320515",
    title: "Pressed Orange Juice",
    brand: "Healthie Pantry",
    type: "food",
    categoryPath: "beverages",
    isOrganic: true,
    isBeverage: true,
    ingredientIds: ["water"],
    ingredientsText: "Organic orange juice, not from concentrate.",
    nutrition: {
      energyKj: 170,
      sugars: 8.5,
      saturatedFat: 0,
      salt: 0,
      fiber: 0.4,
      protein: 0.7,
      fruitsVegetables: 100,
    },
    novaGroup: 1,
    imageUrl: "/images/beverages.jpg",
  },
  {
    barcode: "8500108320423",
    title: "Yard Pate Cat Food",
    brand: "Maison Bloom Pets",
    type: "pet",
    categoryPath: "pet",
    isOrganic: false,
    ingredientIds: ["chicken", "e407", "e102", "propylene-glycol", "e320", "salt"],
    ingredientsText:
      "Chicken by-product, carrageenan (E407), tartrazine (E102), propylene glycol, BHA (E320), salt.",
    nutrition: {
      energyKj: 420,
      sugars: 1,
      saturatedFat: 4,
      salt: 1.2,
      fiber: 0.5,
      protein: 8,
      fruitsVegetables: 0,
      fat: 6,
    },
    novaGroup: 4,
  },
  {
    barcode: "8500108320430",
    title: "Open Pasture Cat Food",
    brand: "Grove Atelier Pets",
    type: "pet",
    categoryPath: "pet",
    isOrganic: true,
    ingredientIds: ["chicken", "fish", "tocopherol"],
    ingredientsText: "Organic chicken, sardine, mixed tocopherols.",
    nutrition: {
      energyKj: 540,
      sugars: 0.4,
      saturatedFat: 2.2,
      salt: 0.3,
      fiber: 0.8,
      protein: 18,
      fruitsVegetables: 0,
      fat: 8,
    },
    novaGroup: 1,
  },
  {
    barcode: "8500108320447",
    title: "BrightWhite Toothpaste",
    brand: "Maison Bloom",
    type: "cosmetic",
    categoryPath: "body",
    isOrganic: false,
    ingredientIds: ["water", "sls", "sodium-fluoride", "e102", "fragrance", "triclosan"],
    ingredientsText:
      "Aqua, Sodium Lauryl Sulfate, Sodium Fluoride, CI 19140, Parfum, Triclosan.",
  },
  {
    barcode: "8500108320454",
    title: "Mineral Toothpaste",
    brand: "Grove Atelier",
    type: "cosmetic",
    categoryPath: "body",
    isOrganic: true,
    ingredientIds: ["glycerin", "hydroxyapatite", "tocopherol"],
    ingredientsText: "Glycerin, Hydroxyapatite, Tocopherol.",
  },
  {
    barcode: "8500108320461",
    title: "Night Retinol Serum",
    brand: "Maison Bloom",
    type: "cosmetic",
    categoryPath: "skincare",
    isOrganic: false,
    ingredientIds: ["water", "retinol", "phenoxyethanol", "fragrance", "peg-40"],
    ingredientsText: "Aqua, Retinol, Phenoxyethanol, Parfum, PEG-40 Hydrogenated Castor Oil.",
    imageUrl: "/images/skincare.jpg",
  },
  {
    barcode: "8500108320607",
    title: "Cloud White Sandwich Bread",
    brand: "Maison Bloom Bakery",
    type: "food",
    categoryPath: "staples",
    isOrganic: false,
    ingredientIds: ["wheat-flour", "sugar", "salt", "e471", "e300"],
    ingredientsText:
      "Wheat flour, water, sugar, vegetable oil, salt, emulsifier (E471), preservative, ascorbic acid (E300).",
    nutrition: {
      energyKj: 1025,
      sugars: 4.5,
      saturatedFat: 0.6,
      salt: 1.1,
      fiber: 2.1,
      protein: 7.8,
      fruitsVegetables: 0,
      fat: 3.2,
    },
    novaGroup: 4,
  },
  {
    barcode: "8500108320614",
    title: "Country Sourdough",
    brand: "Healthie Pantry",
    type: "food",
    categoryPath: "staples",
    isOrganic: true,
    ingredientIds: ["wheat-flour", "salt"],
    ingredientsText: "Organic wheat flour, water, sea salt, sourdough culture.",
    nutrition: {
      energyKj: 980,
      sugars: 1.1,
      saturatedFat: 0.3,
      salt: 1.0,
      fiber: 3.8,
      protein: 9.2,
      fruitsVegetables: 0,
      fat: 1.4,
    },
    novaGroup: 3,
  },
  {
    barcode: "8500108320621",
    title: "Honey Oat Granola Clusters",
    brand: "Maison Bloom",
    type: "food",
    categoryPath: "breakfast",
    isOrganic: false,
    ingredientIds: ["oats", "sugar", "sunflower-oil", "honey", "salt"],
    ingredientsText: "Oats, sugar, sunflower oil, honey, salt, flavouring.",
    nutrition: {
      energyKj: 1880,
      sugars: 22,
      saturatedFat: 2.1,
      salt: 0.45,
      fiber: 6.2,
      protein: 8.1,
      fruitsVegetables: 0,
      fat: 16,
    },
    novaGroup: 4,
  },
  {
    barcode: "8500108320638",
    title: "Trail Protein Bar",
    brand: "Maison Bloom",
    type: "food",
    categoryPath: "snacks",
    isOrganic: false,
    ingredientIds: ["wheat-flour", "sugar", "palm-oil", "e322", "salt", "natural-flavour"],
    ingredientsText:
      "Brown rice syrup, oats, soy protein, palm oil, sugar, chocolate chips, soy lecithin (E322), flavouring, salt.",
    nutrition: {
      energyKj: 1650,
      sugars: 21,
      saturatedFat: 4.2,
      salt: 0.7,
      fiber: 4,
      protein: 10,
      fruitsVegetables: 0,
      fat: 12,
    },
    novaGroup: 4,
  },
  {
    barcode: "8500108320645",
    title: "Skipjack Tuna in Olive Oil",
    brand: "Healthie Pantry",
    type: "food",
    categoryPath: "staples",
    isOrganic: true,
    ingredientIds: ["fish", "olive-oil", "salt"],
    ingredientsText: "Skipjack tuna, organic extra virgin olive oil, sea salt.",
    nutrition: {
      energyKj: 820,
      sugars: 0,
      saturatedFat: 2.4,
      salt: 0.8,
      fiber: 0,
      protein: 24,
      fruitsVegetables: 0,
      fat: 10,
    },
    novaGroup: 3,
  },
  {
    barcode: "8500108320652",
    title: "Stone-Baked Margherita Pizza",
    brand: "Maison Bloom",
    type: "food",
    categoryPath: "staples",
    isOrganic: false,
    ingredientIds: ["wheat-flour", "cheddar", "tomato", "palm-oil", "salt", "e471", "sugar"],
    ingredientsText:
      "Wheat flour, mozzarella, tomato, palm oil, sugar, salt, emulsifier (E471), oregano, flavouring.",
    nutrition: {
      energyKj: 1020,
      sugars: 3.4,
      saturatedFat: 5.5,
      salt: 1.4,
      fiber: 1.8,
      protein: 9.5,
      fruitsVegetables: 12,
      fat: 11,
    },
    novaGroup: 4,
  },
  {
    barcode: "8500108320669",
    title: "Instant Chicken Noodles",
    brand: "Maison Bloom",
    type: "food",
    categoryPath: "staples",
    isOrganic: false,
    ingredientIds: ["wheat-flour", "palm-oil", "salt", "e621", "e102", "e320"],
    ingredientsText:
      "Wheat flour, palm oil, salt, flavour enhancer (E621), colour (E102), antioxidant (E320), flavouring.",
    nutrition: {
      energyKj: 1880,
      sugars: 2.1,
      saturatedFat: 10,
      salt: 4.2,
      fiber: 1.2,
      protein: 8,
      fruitsVegetables: 0,
      fat: 20,
    },
    novaGroup: 4,
  },
  {
    barcode: "8500108320676",
    title: "Sweetened Almond Drink",
    brand: "Maison Bloom",
    type: "food",
    categoryPath: "beverages",
    isOrganic: false,
    isBeverage: true,
    ingredientIds: ["water", "almond", "sugar", "e322", "natural-flavour"],
    ingredientsText: "Water, almonds (2%), sugar, calcium, emulsifier (E322), flavouring, salt.",
    nutrition: {
      energyKj: 100,
      sugars: 3.1,
      saturatedFat: 0.1,
      salt: 0.14,
      fiber: 0.3,
      protein: 0.4,
      fruitsVegetables: 0,
      fat: 1.1,
    },
    novaGroup: 4,
  },
  {
    barcode: "8500108320683",
    title: "Unsweetened Oat Drink",
    brand: "Healthie Pantry",
    type: "food",
    categoryPath: "beverages",
    isOrganic: true,
    isBeverage: true,
    ingredientIds: ["water", "oats", "sunflower-oil", "salt"],
    ingredientsText: "Water, organic oats (10%), organic sunflower oil, sea salt.",
    nutrition: {
      energyKj: 160,
      sugars: 2.8,
      saturatedFat: 0.2,
      salt: 0.1,
      fiber: 0.8,
      protein: 0.6,
      fruitsVegetables: 0,
      fat: 1.5,
    },
    novaGroup: 3,
  },
  {
    barcode: "8500108320690",
    title: "Creamy Peanut Spread",
    brand: "Maison Bloom",
    type: "food",
    categoryPath: "spreads",
    isOrganic: false,
    ingredientIds: ["peanut", "sugar", "palm-oil", "salt"],
    ingredientsText: "Peanuts, sugar, palm oil, salt.",
    nutrition: {
      energyKj: 2500,
      sugars: 9,
      saturatedFat: 8.5,
      salt: 1.0,
      fiber: 6,
      protein: 22,
      fruitsVegetables: 0,
      fat: 50,
    },
    novaGroup: 4,
  },
  {
    barcode: "8500108320706",
    title: "Crunchy Peanut Butter",
    brand: "Healthie Pantry",
    type: "food",
    categoryPath: "spreads",
    isOrganic: true,
    ingredientIds: ["peanut", "salt"],
    ingredientsText: "Organic peanuts, sea salt.",
    nutrition: {
      energyKj: 2480,
      sugars: 4.2,
      saturatedFat: 6.8,
      salt: 0.4,
      fiber: 8,
      protein: 26,
      fruitsVegetables: 0,
      fat: 49,
    },
    novaGroup: 1,
  },
  {
    barcode: "8500108320713",
    title: "Sparkling Limonata",
    brand: "Maison Bloom",
    type: "food",
    categoryPath: "beverages",
    isOrganic: false,
    isBeverage: true,
    ingredientIds: ["water", "sugar", "e330", "natural-flavour", "carbon-dioxide"],
    ingredientsText: "Sparkling water, sugar, lemon juice from concentrate, citric acid (E330), natural flavouring.",
    nutrition: {
      energyKj: 170,
      sugars: 9.5,
      saturatedFat: 0,
      salt: 0,
      fiber: 0,
      protein: 0,
      fruitsVegetables: 4,
    },
    novaGroup: 4,
  },
  {
    barcode: "8500108320805",
    title: "Radiance Foundation",
    brand: "Maison Bloom",
    type: "cosmetic",
    categoryPath: "skincare",
    isOrganic: false,
    ingredientIds: ["water", "cyclopentasiloxane", "fragrance", "methylparaben", "peg-40", "ci19140", "dimethicone"],
    ingredientsText:
      "Aqua, Cyclopentasiloxane, Dimethicone, PEG-40 Hydrogenated Castor Oil, Parfum, Methylparaben, CI 19140.",
  },
  {
    barcode: "8500108320812",
    title: "Tinted Mineral Veil",
    brand: "Grove Atelier",
    type: "cosmetic",
    categoryPath: "skincare",
    isOrganic: true,
    ingredientIds: ["zinc-oxide", "caprylic", "tocopherol", "shea", "cetearyl"],
    ingredientsText:
      "Zinc Oxide, Caprylic/Capric Triglyceride, Butyrospermum Parkii Butter, Cetearyl Alcohol, Tocopherol.",
  },
  {
    barcode: "8500108320829",
    title: "Cloud Deodorant Spray",
    brand: "Maison Bloom",
    type: "cosmetic",
    categoryPath: "body",
    isOrganic: false,
    ingredientIds: ["water", "fragrance", "triclosan", "peg-40", "linalool", "alcohol-denat"],
    ingredientsText: "Aqua, Alcohol Denat., Parfum, Triclosan, PEG-40 Hydrogenated Castor Oil, Linalool.",
  },
  {
    barcode: "8500108320836",
    title: "Salt Stone Deodorant",
    brand: "Grove Atelier",
    type: "cosmetic",
    categoryPath: "body",
    isOrganic: true,
    ingredientIds: ["salt", "glycerin"],
    ingredientsText: "Mineral salts, glycerin.",
  },
  {
    barcode: "8500108320843",
    title: "Glass Lip Gloss",
    brand: "Maison Bloom",
    type: "cosmetic",
    categoryPath: "body",
    isOrganic: false,
    ingredientIds: ["dimethicone", "fragrance", "peg-40", "ci19140", "methylparaben", "linalool"],
    ingredientsText: "Dimethicone, PEG-40 Hydrogenated Castor Oil, Parfum, Methylparaben, Linalool, CI 19140.",
  },
  {
    barcode: "8500108320850",
    title: "Plain Lip Balm",
    brand: "Grove Atelier",
    type: "cosmetic",
    categoryPath: "body",
    isOrganic: true,
    ingredientIds: ["shea", "olive-oil", "tocopherol", "caprylic"],
    ingredientsText: "Butyrospermum Parkii Butter, Olea Europaea Fruit Oil, Caprylic/Capric Triglyceride, Tocopherol.",
  },
  {
    barcode: "8500108320904",
    title: "Yard Dental Sticks",
    brand: "Maison Bloom Pets",
    type: "pet",
    categoryPath: "pet",
    isOrganic: false,
    ingredientIds: ["wheat-flour", "chicken", "e320", "e102", "propylene-glycol", "salt"],
    ingredientsText:
      "Wheat flour, chicken by-product, propylene glycol, BHA (E320), tartrazine (E102), salt, flavouring.",
    nutrition: {
      energyKj: 1400,
      sugars: 4,
      saturatedFat: 3,
      salt: 1.4,
      fiber: 1.5,
      protein: 10,
      fruitsVegetables: 0,
      fat: 6,
    },
    novaGroup: 4,
  },
  {
    barcode: "8500108320911",
    title: "Air-Dried Chicken Chews",
    brand: "Grove Atelier Pets",
    type: "pet",
    categoryPath: "pet",
    isOrganic: true,
    ingredientIds: ["chicken", "tocopherol"],
    ingredientsText: "Organic chicken, mixed tocopherols.",
    nutrition: {
      energyKj: 1500,
      sugars: 0.2,
      saturatedFat: 2.5,
      salt: 0.3,
      fiber: 0.4,
      protein: 38,
      fruitsVegetables: 0,
      fat: 8,
    },
    novaGroup: 1,
  },
];

const SEED = [...CORE_PRODUCTS, ...MORE_PRODUCTS, ...WORLD_PRODUCTS, ...SHELF_PRODUCTS, ...CART_PRODUCTS, ...AISLE_PRODUCTS, ...EXTRA_PRODUCTS, ...PREMIUM_PRODUCTS, ...DENSE_PRODUCTS];
const seen = new Set<string>();
export const PRODUCTS: ProductDef[] = SEED.filter((p) => {
  if (seen.has(p.barcode)) return false;
  if (isDemoBarcode(p.barcode) || isDemoBrand(p.brand)) return false;
  seen.add(p.barcode);
  return true;
});
export const PRODUCT_BY_BARCODE = new Map(PRODUCTS.map((p) => [p.barcode, p]));

export function aisleShelfCounts(): Map<string, number> {
  const map = new Map<string, number>();
  for (const p of PRODUCTS) {
    map.set(p.categoryPath, (map.get(p.categoryPath) ?? 0) + 1);
  }
  return map;
}
