import type { ProductDef } from "./products";
import type { Nutrition } from "@/lib/scoring/types";

function n(
  energyKj: number,
  sugars: number,
  sat: number,
  salt: number,
  fiber: number,
  protein: number,
  fv: number,
  fat?: number,
): Nutrition {
  return { energyKj, sugars, saturatedFat: sat, salt, fiber, protein, fruitsVegetables: fv, fat };
}

let seq = 0;
function code(): string {
  seq += 1;
  const body = `2092${String(seq).padStart(8, "0")}`;
  let sum = 0;
  for (let i = 0; i < 12; i += 1) sum += Number(body[i]) * (i % 2 === 0 ? 1 : 3);
  return body + String((10 - (sum % 10)) % 10);
}

function food(
  title: string,
  brand: string,
  categoryPath: string,
  ingredientIds: string[],
  ingredientsText: string,
  nutrition: Nutrition,
  extra?: { organic?: boolean; beverage?: boolean; water?: boolean; nova?: number },
): ProductDef {
  return {
    barcode: code(),
    title,
    brand,
    type: "food",
    categoryPath,
    isOrganic: Boolean(extra?.organic),
    isBeverage: extra?.beverage,
    isWater: extra?.water,
    ingredientIds,
    ingredientsText,
    nutrition,
    novaGroup: extra?.nova,
  };
}

function cos(
  title: string,
  brand: string,
  categoryPath: string,
  ingredientIds: string[],
  ingredientsText: string,
): ProductDef {
  return {
    barcode: code(),
    title,
    brand,
    type: "cosmetic",
    categoryPath,
    isOrganic: false,
    ingredientIds,
    ingredientsText,
  };
}

function pet(
  title: string,
  brand: string,
  ingredientIds: string[],
  ingredientsText: string,
  nutrition: Nutrition,
  extra?: { nova?: number },
): ProductDef {
  return {
    barcode: code(),
    title,
    brand,
    type: "pet",
    categoryPath: "pet",
    isOrganic: false,
    ingredientIds,
    ingredientsText,
    nutrition,
    novaGroup: extra?.nova,
  };
}

/** Thin aisles, stocked for a live shop — worst, middle, and best on the same shelf. */
export const DENSE_PRODUCTS: ProductDef[] = [
  // —— Candy ——
  food("Haribo Goldbears", "Haribo", "candy", ["sugar", "e330", "e100", "e120", "e129"], "Glucose syrup, sugar, gelatine, dextrose, citric acid, flavouring, fruit and plant concentrates, carmine, curcumin.", n(1456, 56, 0.1, 0.07, 0, 6.9, 0, 0.2), { nova: 4 }),
  food("Sour Patch Kids", "Sour Patch Kids", "candy", ["sugar", "e330", "e102", "e129", "e133"], "Sugar, invert sugar, corn syrup, modified corn starch, tartaric acid, citric acid, yellow 5, red 40, blue 1.", n(1480, 70, 0, 0.05, 0, 0, 0, 0), { nova: 4 }),
  food("Skittles Original", "Skittles", "candy", ["sugar", "palm-oil", "e102", "e110", "e129", "e133"], "Sugar, corn syrup, hydrogenated palm kernel oil, fruit juice, citric acid, yellow 5, yellow 6, red 40, blue 1.", n(1680, 76, 8, 0.02, 0, 0, 0, 8), { nova: 4 }),
  food("Starburst Original", "Starburst", "candy", ["sugar", "palm-oil", "e330", "e102", "e129"], "Corn syrup, sugar, palm oil, citric acid, yellow 5, red 40, blue 1, natural and artificial flavours.", n(1700, 64, 7, 0.02, 0, 0, 0, 8), { nova: 4 }),
  food("Twizzlers Strawberry", "Twizzlers", "candy", ["sugar", "wheat-flour", "e129", "e330"], "Corn syrup, wheat flour, sugar, cornstarch, palm oil, salt, red 40, citric acid, natural flavour.", n(1460, 40, 1, 0.5, 0, 2, 0, 2), { nova: 4 }),
  food("Nerds Grape & Strawberry", "Nerds", "candy", ["sugar", "e330", "e102", "e129", "e133"], "Dextrose, sugar, malic acid, citric acid, yellow 5, red 40, blue 1.", n(1600, 88, 0, 0, 0, 0, 0, 0), { nova: 4 }),
  food("Jolly Rancher Hard Candy", "Jolly Rancher", "candy", ["sugar", "e330", "e102", "e129", "e133"], "Corn syrup, sugar, malic acid, natural and artificial flavour, yellow 5, red 40, blue 1.", n(1640, 70, 0, 0, 0, 0, 0, 0), { nova: 4 }),
  food("Reese's Pieces", "Reese's", "candy", ["sugar", "peanut", "palm-oil", "e102", "e110"], "Sugar, peanuts, hydrogenated vegetable oil, dextrose, yellow 5 lake, yellow 6 lake, red 40 lake.", n(2070, 53, 12, 0.2, 3, 10, 0, 24), { nova: 4 }),
  food("M&M's Milk Chocolate", "M&M's", "candy", ["sugar", "cocoa", "milk", "e322", "e102", "e129", "e133"], "Milk chocolate, sugar, cocoa butter, milk, soy lecithin, yellow 5, red 40, blue 1, yellow 6.", n(2010, 65, 12, 0.1, 2, 5, 0, 22), { nova: 4 }),
  food("Airheads White Mystery", "Airheads", "candy", ["sugar", "palm-oil", "e330", "e171"], "Sugar, corn syrup, palm oil, citric acid, titanium dioxide, artificial flavour.", n(1560, 62, 2, 0.1, 0, 0, 0, 4), { nova: 4 }),
  food("Swedish Fish", "Swedish Fish", "candy", ["sugar", "e330", "e129"], "Sugar, invert sugar, corn syrup, modified corn starch, citric acid, red 40, natural and artificial flavours.", n(1490, 66, 0, 0.08, 0, 0, 0, 0), { nova: 4 }),
  food("Life Savers 5 Flavors", "Life Savers", "candy", ["sugar", "e330", "e102", "e129"], "Sugar, corn syrup, citric acid, natural and artificial flavours, yellow 5, red 40.", n(1590, 72, 0, 0, 0, 0, 0, 0), { nova: 4 }),
  food("Tootsie Roll", "Tootsie Roll", "candy", ["sugar", "palm-oil", "cocoa", "soy", "e322"], "Sugar, corn syrup, partially hydrogenated soybean oil, condensed skim milk, cocoa, soy lecithin.", n(1620, 56, 3, 0.1, 1, 2, 0, 8), { nova: 4 }),
  food("Mike and Ike Original", "Mike and Ike", "candy", ["sugar", "e330", "e102", "e129", "e133"], "Sugar, corn syrup, modified food starch, citric acid, yellow 5, red 40, blue 1.", n(1520, 70, 0, 0.05, 0, 0, 0, 0), { nova: 4 }),
  food("Runts", "Runts", "candy", ["sugar", "e330", "e102", "e110", "e129"], "Dextrose, maltodextrin, malic acid, yellow 5, yellow 6, red 40.", n(1580, 86, 0, 0, 0, 0, 0, 0), { nova: 4 }),
  food("Smarties Candy", "Smarties", "candy", ["sugar", "e102", "e110", "e129", "e133"], "Dextrose, citric acid, calcium stearate, yellow 5, yellow 6, red 40, blue 1.", n(1560, 88, 0, 0, 0, 0, 0, 0), { nova: 4 }),
  food("Warheads Extreme Sour", "Warheads", "candy", ["sugar", "e330", "e102", "e129"], "Sugar, corn syrup, malic acid, citric acid, yellow 5, red 40, artificial flavour.", n(1470, 64, 0, 0, 0, 0, 0, 0), { nova: 4 }),
  food("Hot Tamales", "Hot Tamales", "candy", ["sugar", "e330", "e129", "e102"], "Sugar, corn syrup, modified food starch, citric acid, red 40, yellow 5, artificial flavour.", n(1520, 68, 0, 0.04, 0, 0, 0, 0), { nova: 4 }),
  food("Unreal Dark Chocolate Crispy Gems", "Unreal", "candy", ["cocoa", "sugar", "rice", "e322"], "Cacao, cane sugar, crisp rice, cocoa butter, sunflower lecithin.", n(1880, 28, 10, 0.05, 6, 6, 0, 22), { organic: true, nova: 3 }),
  food("YumEarth Organic Giggles", "YumEarth", "candy", ["sugar", "e440", "e330", "e160a"], "Organic cane sugar, organic rice syrup, pectin, citric acid, organic fruit juice, beta carotene.", n(1400, 62, 0, 0.04, 1, 0, 4, 0), { organic: true, nova: 3 }),

  // —— Meat & deli ——
  food("Applegate Organic Roast Turkey", "Applegate", "meat", ["chicken", "salt"], "Organic turkey breast, water, sea salt.", n(440, 0, 0.4, 0.9, 0, 22, 0, 2), { organic: true, nova: 1 }),
  food("Applegate Naturals Uncured Ham", "Applegate", "meat", ["pork", "salt", "e300"], "Pork, water, sea salt, organic sugar, celery powder, cherry powder.", n(480, 1, 1.5, 1.2, 0, 18, 0, 4), { nova: 3 }),
  food("Oscar Mayer Bologna", "Oscar Mayer", "meat", ["pork", "e250", "e621", "e129"], "Mechanically separated chicken, pork, corn syrup, salt, sodium nitrite, MSG, red 40, flavour.", n(1290, 4, 8, 2.1, 0, 10, 0, 28), { nova: 4 }),
  food("Oscar Mayer Classic Wieners", "Oscar Mayer", "meat", ["pork", "e250", "e621"], "Mechanically separated chicken, pork, water, corn syrup, salt, sodium nitrite, flavour.", n(1210, 2, 7, 1.8, 0, 11, 0, 26), { nova: 4 }),
  food("Hebrew National Beef Franks", "Hebrew National", "meat", ["beef", "salt", "e250", "e621"], "Beef, water, salt, spice, sodium nitrite, flavour, paprika.", n(1250, 1, 8, 1.7, 0, 12, 0, 26), { nova: 4 }),
  food("Hillshire Farm Smoked Sausage", "Hillshire Farm", "meat", ["pork", "e250", "salt", "e621"], "Pork, water, corn syrup, salt, sodium nitrite, flavour, MSG.", n(1180, 3, 8, 1.9, 0, 12, 0, 24), { nova: 4 }),
  food("Boar's Head Ovengold Turkey", "Boar's Head", "meat", ["chicken", "salt"], "Turkey breast, salt, sugar, sodium phosphate.", n(440, 1, 0.3, 1.0, 0, 22, 0, 1), { nova: 3 }),
  food("Hormel Black Label Bacon", "Hormel", "meat", ["pork", "e250", "e252", "sugar", "salt"], "Cured pork belly, water, salt, sugar, sodium phosphates, sodium erythorbate, sodium nitrite.", n(2260, 0, 14, 2.4, 0, 12, 0, 42), { nova: 4 }),
  food("Kirkland Bacon", "Kirkland", "meat", ["pork", "e250", "sugar", "salt"], "Pork, water, salt, sugar, sodium phosphates, sodium erythorbate, sodium nitrite.", n(2200, 0, 13, 2.2, 0, 13, 0, 40), { nova: 4 }),
  food("365 Organic Ground Beef 85%", "365 Whole Foods Market", "meat", ["beef"], "Organic beef.", n(900, 0, 6, 0.15, 0, 18, 0, 15), { organic: true, nova: 1 }),
  food("Good & Gather Rotisserie Chicken", "Good & Gather", "meat", ["chicken", "salt"], "Chicken, water, salt, sodium phosphates.", n(650, 0, 2, 0.8, 0, 24, 0, 8), { nova: 3 }),
  food("Foster Farms Chicken Breast", "Foster Farms", "meat", ["chicken"], "Chicken breast.", n(460, 0, 0.4, 0.15, 0, 23, 0, 2), { nova: 1 }),
  food("Tyson Chicken Nuggets", "Tyson", "meat", ["chicken", "wheat-flour", "palm-oil", "salt", "e621"], "Chicken, water, wheat flour, vegetable oil, salt, MSG, spice, dextrose.", n(1170, 1, 4, 1.3, 1, 14, 0, 16), { nova: 4 }),
  food("Banquet Chicken Fried Beef Steak", "Banquet", "meat", ["beef", "wheat-flour", "palm-oil", "salt", "e621"], "Beef, batter, vegetable oil, salt, MSG, spice.", n(1210, 2, 6, 1.5, 1, 12, 0, 18), { nova: 4 }),
  food("Spam Classic", "Spam", "meat", ["pork", "salt", "e250", "sugar"], "Pork, salt, water, sugar, sodium nitrite.", n(1320, 1, 10, 1.8, 0, 13, 0, 26), { nova: 4 }),
  food("Buddig Original Turkey", "Buddig", "meat", ["chicken", "salt", "e250", "e621"], "Turkey, salt, dextrose, sodium phosphates, sodium nitrite, flavour.", n(540, 1, 1, 1.6, 0, 16, 0, 4), { nova: 4 }),
  food("Columbus Italian Dry Salame", "Columbus", "meat", ["pork", "salt", "e250", "e252"], "Pork, salt, dextrose, sodium nitrite, sodium nitrate, lactic acid starter culture, spice.", n(1550, 1, 10, 2.2, 0, 20, 0, 30), { nova: 4 }),
  food("Simple Truth Organic Chicken Thighs", "Simple Truth", "meat", ["chicken"], "Organic chicken thighs.", n(700, 0, 3, 0.16, 0, 18, 0, 10), { organic: true, nova: 1 }),

  // —— Bakery ——
  food("Dave's Killer Bread 21 Whole Grains", "Dave's Killer Bread", "bakery", ["wheat-flour", "oats", "sugar", "salt"], "Organic whole wheat, water, organic cane sugar, organic oats, organic flax, sea salt, yeast.", n(1050, 6, 0.5, 0.7, 5, 6, 0, 3), { organic: true, nova: 3 }),
  food("Ezekiel 4:9 Sprouted Whole Grain", "Food for Life", "bakery", ["wheat-flour", "salt"], "Organic sprouted wheat, water, organic sprouted barley, organic sprouted millet, sea salt, yeast.", n(920, 0, 0.3, 0.6, 6, 8, 0, 1), { organic: true, nova: 1 }),
  food("Wonder Classic White", "Wonder", "bakery", ["wheat-flour", "sugar", "e471", "e282", "salt"], "Enriched flour, water, sugar, soybean oil, salt, calcium propionate, mono and diglycerides, soy lecithin.", n(1110, 6, 0.5, 1.0, 1, 4, 0, 3), { nova: 4 }),
  food("Sara Lee Honey Wheat", "Sara Lee", "bakery", ["wheat-flour", "sugar", "honey", "e471", "salt"], "Enriched flour, water, whole wheat flour, honey, sugar, soybean oil, salt, calcium propionate.", n(1080, 8, 0.4, 0.9, 2, 4, 0, 2), { nova: 4 }),
  food("Nature's Own Butterbread", "Nature's Own", "bakery", ["wheat-flour", "sugar", "e471", "salt"], "Enriched flour, water, sugar, butter, soybean oil, salt, calcium propionate, soy lecithin.", n(1130, 6, 1, 0.9, 1, 4, 0, 3), { nova: 4 }),
  food("Pepperidge Farm Farmhouse Hearty White", "Pepperidge Farm", "bakery", ["wheat-flour", "sugar", "e471", "salt"], "Enriched wheat flour, water, sugar, soybean oil, salt, yeast, calcium propionate.", n(1170, 5, 0.5, 0.95, 1, 4, 0, 3), { nova: 4 }),
  food("Thomas' Original English Muffins", "Thomas'", "bakery", ["wheat-flour", "sugar", "e282", "salt"], "Enriched wheat flour, water, farina, sugar, salt, yeast, calcium propionate, soy lecithin.", n(960, 2, 0.3, 0.85, 2, 4, 0, 1), { nova: 4 }),
  food("Thomas' Light Multi-Grain English Muffins", "Thomas'", "bakery", ["wheat-flour", "oats", "salt"], "Whole wheat flour, water, wheat gluten, oats, yeast, salt, calcium propionate.", n(800, 2, 0.2, 0.7, 4, 6, 0, 1), { nova: 3 }),
  food("Mission Flour Tortillas", "Mission", "bakery", ["wheat-flour", "palm-oil", "salt", "e471"], "Enriched flour, water, vegetable shortening, salt, sodium acid pyrophosphate, mono and diglycerides.", n(1260, 2, 4, 1.1, 1, 4, 0, 8), { nova: 4 }),
  food("Mission Carb Balance Whole Wheat Tortillas", "Mission", "bakery", ["wheat-flour", "salt", "e412"], "Water, modified wheat starch, whole wheat flour, wheat gluten, salt, cellulose gum.", n(630, 0, 1.5, 0.9, 13, 6, 0, 4), { nova: 4 }),
  food("La Brea Bakery Sourdough Loaf", "La Brea", "bakery", ["wheat-flour", "salt"], "Unbleached flour, water, salt, sourdough culture.", n(1050, 1, 0.2, 0.8, 2, 4, 0, 1), { nova: 1 }),
  food("Canyon Bakehouse Mountain White", "Canyon Bakehouse", "bakery", ["rice", "sugar", "e412", "salt"], "Water, brown rice flour, tapioca flour, eggs, sugar, xanthan gum, salt, yeast.", n(1000, 4, 0.3, 0.85, 2, 3, 0, 2), { nova: 4 }),
  food("Udi's Gluten Free White Sandwich", "Udi's", "bakery", ["rice", "sugar", "e412", "salt"], "Water, tapioca starch, brown rice flour, canola oil, egg whites, sugar, xanthan gum, salt, yeast.", n(1080, 5, 0.4, 0.9, 2, 3, 0, 3), { nova: 4 }),
  food("King's Hawaiian Original Rolls", "King's Hawaiian", "bakery", ["wheat-flour", "sugar", "e471", "salt"], "Enriched flour, water, sugar, liquid sugar, butter, eggs, salt, yeast, calcium propionate.", n(1380, 14, 3, 0.8, 1, 5, 0, 6), { nova: 4 }),
  food("Pillsbury Grands! Southern Homestyle Biscuits", "Pillsbury", "bakery", ["wheat-flour", "palm-oil", "sugar", "e500", "salt"], "Enriched flour, water, palm oil, sugar, baking soda, salt, sodium aluminum phosphate.", n(1380, 5, 6, 1.4, 1, 4, 0, 12), { nova: 4 }),
  food("Pillsbury Cinnamon Rolls with Icing", "Pillsbury", "bakery", ["wheat-flour", "sugar", "palm-oil", "e102", "e129"], "Enriched flour, sugar, water, palm oil, cinnamon, yellow 5, red 40, salt, baking soda.", n(1500, 22, 4, 1.1, 1, 4, 0, 10), { nova: 4 }),
  food("Entenmann's Rich Frosted Donuts", "Entenmann's", "bakery", ["wheat-flour", "sugar", "palm-oil", "e322", "e102"], "Enriched flour, sugar, palm oil, water, cocoa, soy lecithin, yellow 5, yellow 6.", n(1880, 28, 10, 0.7, 1, 4, 0, 24), { nova: 4 }),
  food("Hostess Twinkies", "Hostess", "bakery", ["wheat-flour", "sugar", "palm-oil", "e102", "e110", "e471"], "Enriched flour, water, sugar, corn syrup, high fructose corn syrup, tallow, yellow 5, yellow 6.", n(1420, 32, 4, 0.8, 0, 2, 0, 12), { nova: 4 }),

  // —— Coffee & tea ——
  food("Starbucks Pike Place Whole Bean", "Starbucks", "coffee", ["coffee"], "100% arabica coffee.", n(0, 0, 0, 0, 0, 0, 0, 0), { nova: 1 }),
  food("Peet's Major Dickason's Blend", "Peet's", "coffee", ["coffee"], "Arabica coffee.", n(0, 0, 0, 0, 0, 0, 0, 0), { nova: 1 }),
  food("Lavazza Super Crema", "Lavazza", "coffee", ["coffee"], "Arabica and robusta coffee.", n(0, 0, 0, 0, 0, 0, 0, 0), { nova: 1 }),
  food("Trader Joe's Fair Trade Organic Coffee", "Trader Joe's", "coffee", ["coffee"], "Organic arabica coffee.", n(0, 0, 0, 0, 0, 0, 0, 0), { organic: true, nova: 1 }),
  food("Twinings English Breakfast", "Twinings", "coffee", ["tea"], "Black tea.", n(4, 0, 0, 0, 0, 0, 0, 0), { nova: 1 }),
  food("Yogi Ginger Tea", "Yogi", "coffee", ["tea", "spice"], "Ginger, lemongrass, licorice, black pepper, peppermint.", n(8, 0, 0, 0, 0, 0, 0, 0), { organic: true, nova: 1 }),
  food("Traditional Medicinals Chamomile", "Traditional Medicinals", "coffee", ["tea"], "Organic chamomile flower.", n(4, 0, 0, 0, 0, 0, 0, 0), { organic: true, nova: 1 }),
  food("Celestial Seasonings Sleepytime", "Celestial Seasonings", "coffee", ["tea"], "Chamomile, spearmint, lemongrass, tilia, blackberry leaves, hawthorn, orange blossoms, rosebuds.", n(4, 0, 0, 0, 0, 0, 0, 0), { nova: 1 }),
  food("Lipton Iced Tea Mix Lemon", "Lipton", "coffee", ["sugar", "tea", "e330", "e102"], "Sugar, citric acid, instant tea, lemon flavour, yellow 5.", n(1600, 96, 0, 0.02, 0, 0, 0, 0), { beverage: true, nova: 4 }),
  food("Arizona Green Tea with Ginseng and Honey", "Arizona", "coffee", ["water", "sugar", "tea", "honey", "e330"], "Premium brewed green tea, sugar, honey, citric acid, natural flavours, ginseng extract.", n(120, 7.5, 0, 0.02, 0, 0, 0, 0), { beverage: true, nova: 4 }),
  food("Gold Peak Sweet Tea", "Gold Peak", "coffee", ["water", "sugar", "tea"], "Tea, sugar, natural flavour.", n(150, 9, 0, 0.02, 0, 0, 0, 0), { beverage: true, nova: 4 }),
  food("Starbucks Frappuccino Coffee Bottle", "Starbucks", "coffee", ["milk", "sugar", "coffee", "e407"], "Starbucks coffee, reduced fat milk, sugar, maltodextrin, pectin, natural flavour.", n(280, 11, 1, 0.12, 0, 2, 0, 2), { beverage: true, nova: 4 }),
  food("International Delight French Vanilla Creamer", "International Delight", "coffee", ["sugar", "palm-oil", "e471", "e102"], "Water, sugar, palm oil, sodium caseinate, dipotassium phosphate, mono and diglycerides, natural and artificial flavour, yellow 5.", n(1170, 20, 2, 0.1, 0, 0, 0, 10), { nova: 4 }),
  food("Coffee-Mate Original Powder", "Coffee-Mate", "coffee", ["sugar", "palm-oil", "e340", "e551"], "Corn syrup solids, hydrogenated vegetable oil, sodium caseinate, dipotassium phosphate, silicon dioxide.", n(2300, 10, 8, 0.2, 0, 0, 0, 30), { nova: 4 }),
  food("Califia Farms Unsweetened Almond Creamer", "Califia Farms", "coffee", ["almond", "sunflower-oil"], "Almondmilk (water, almonds), sunflower oil, potassium citrate, sea salt, sunflower lecithin.", n(170, 0, 0, 0.15, 0, 0.5, 0, 3), { nova: 3 }),
  food("Numi Organic Gunpowder Green", "Numi", "coffee", ["tea"], "Organic green tea.", n(4, 0, 0, 0, 0, 0, 0, 0), { organic: true, nova: 1 }),

  // —— Protein ——
  food("Orgain Organic Protein Plant Based", "Orgain", "protein", ["pea", "rice", "chia", "e551"], "Organic pea protein, organic brown rice protein, organic chia seed, organic acacia, stevia, silicon dioxide.", n(1550, 4, 1, 0.6, 6, 21, 0, 4), { organic: true, nova: 4 }),
  food("Garden of Life Sport Organic Plant-Based", "Garden of Life", "protein", ["pea", "e551"], "Organic pea protein, organic navy bean, organic lentil, organic garbanzo, organic cranberry protein.", n(1500, 2, 0.5, 0.5, 4, 30, 0, 2), { organic: true, nova: 3 }),
  food("Optimum Nutrition Gold Standard Whey", "Optimum Nutrition", "protein", ["milk", "soy", "e551", "e950", "natural-flavour"], "Whey protein isolate, whey protein concentrate, soy lecithin, natural and artificial flavour, sucralose, acesulfame potassium.", n(1550, 4, 1.5, 0.3, 0, 24, 0, 2), { nova: 4 }),
  food("Quest Chocolate Chip Cookie Dough Bar", "Quest", "protein", ["milk", "e965", "e422", "e551", "natural-flavour"], "Protein blend (milk protein isolate, whey protein isolate), soluble corn fiber, almonds, erythritol, water, natural flavours, sucralose.", n(1380, 1, 2, 0.5, 14, 20, 0, 8), { nova: 4 }),
  food("Clif Builder's Chocolate", "Clif", "protein", ["soy", "sugar", "palm-oil", "e322"], "Soy protein isolate, cane sugar, palm kernel oil, brown rice syrup, rolled oats, cocoa, soy lecithin.", n(1590, 21, 8, 0.5, 2, 20, 0, 12), { nova: 4 }),
  food("RXBAR Chocolate Sea Salt", "RXBAR", "protein", ["egg", "cashew", "cocoa", "salt"], "Dates, egg whites, cashews, almonds, chocolate, cocoa, sea salt, natural flavour.", n(1550, 15, 2, 0.6, 5, 12, 20, 8), { nova: 3 }),
  food("Premier Protein Chocolate Shake", "Premier Protein", "protein", ["milk", "e950", "e551", "e407"], "Water, milk protein concentrate, cocoa, cellulose gel, sucralose, acesulfame potassium, natural flavour.", n(250, 1, 1, 0.2, 2, 10, 0, 3), { beverage: true, nova: 4 }),
  food("Ensure Original Vanilla", "Ensure", "protein", ["milk", "sugar", "e471", "e407"], "Water, corn maltodextrin, sugar, milk protein concentrate, soy oil, canola oil, soy protein isolate.", n(440, 15, 1, 0.2, 0, 4, 0, 6), { beverage: true, nova: 4 }),
  food("Muscle Milk Chocolate", "Muscle Milk", "protein", ["milk", "sugar", "e950", "e407"], "Water, milk protein isolate, calcium caseinate, sugar, cocoa, sucralose, carrageenan.", n(320, 2, 1, 0.25, 1, 8, 0, 4), { beverage: true, nova: 4 }),
  food("Pure Protein Bar Chewy Chocolate Chip", "Pure Protein", "protein", ["milk", "sugar", "palm-oil", "e322", "e950"], "Protein blend, coating (sugar, palm kernel oil), glycerin, hydrolyzed gelatin, sucralose.", n(1550, 14, 6, 0.4, 1, 20, 0, 10), { nova: 4 }),
  food("ONE Bar Birthday Cake", "ONE", "protein", ["milk", "e965", "e551", "natural-flavour"], "Protein blend, maltitol, glycerin, palm kernel oil, natural flavour, sucralose, colors.", n(1420, 1, 7, 0.4, 7, 20, 0, 8), { nova: 4 }),
  food("Gatorade Whey Protein Bar Chocolate", "Gatorade", "protein", ["milk", "sugar", "palm-oil", "e322"], "Soy protein isolate, coating, corn syrup, whey protein, palm oil, sugar, soy lecithin.", n(1630, 20, 6, 0.5, 1, 20, 0, 12), { nova: 4 }),
  food("KIND Protein Dark Chocolate Nut", "KIND", "protein", ["peanut", "almond", "cocoa", "sugar", "e322"], "Peanuts, almonds, soy protein isolate, honey, glucose syrup, dark chocolate, soy lecithin.", n(1880, 16, 4, 0.2, 5, 12, 0, 22), { nova: 3 }),
  food("Aloha Organic Plant-Based Chocolate", "Aloha", "protein", ["pumpkin-seed", "cocoa", "e551"], "Organic pumpkin seed protein, organic brown rice protein, organic chocolate, organic coconut sugar, stevia.", n(1500, 6, 3, 0.3, 4, 18, 0, 8), { organic: true, nova: 3 }),

  // —— Alcohol ——
  food("Bud Light", "Bud Light", "alcohol", ["water", "rice"], "Water, barley malt, rice, hops.", n(120, 0.3, 0, 0.01, 0, 0.3, 0, 0), { beverage: true, nova: 3 }),
  food("Coors Light", "Coors Light", "alcohol", ["water"], "Water, barley malt, corn syrup, hops.", n(115, 0, 0, 0.01, 0, 0.3, 0, 0), { beverage: true, nova: 3 }),
  food("Heineken Lager", "Heineken", "alcohol", ["water"], "Water, malted barley, hop extract.", n(175, 0, 0, 0.01, 0, 0.4, 0, 0), { beverage: true, nova: 3 }),
  food("Guinness Draught Can", "Guinness", "alcohol", ["water"], "Water, malted barley, barley, hops, nitrogen.", n(155, 0.8, 0, 0.02, 0, 0.5, 0, 0), { beverage: true, nova: 3 }),
  food("White Claw Black Cherry", "White Claw", "alcohol", ["water", "sugar", "natural-flavour", "e330"], "Sparkling water, alcohol from sugar, natural flavour, citric acid, sodium citrate, sucralose.", n(80, 2, 0, 0.02, 0, 0, 0, 0), { beverage: true, nova: 4 }),
  food("Truly Wild Berry", "Truly", "alcohol", ["water", "sugar", "natural-flavour", "e330"], "Sparkling water, cane sugar, alcohol, natural flavour, citric acid, sucralose.", n(85, 1, 0, 0.02, 0, 0, 0, 0), { beverage: true, nova: 4 }),
  food("High Noon Pineapple", "High Noon", "alcohol", ["water", "sugar", "natural-flavour"], "Sparkling water, vodka, cane sugar, natural flavour, citric acid.", n(120, 8, 0, 0.01, 0, 0, 4, 0), { beverage: true, nova: 4 }),
  food("Mike's Hard Lemonade", "Mike's Hard", "alcohol", ["water", "sugar", "e330", "e102"], "Water, sugar, malt, citric acid, natural flavour, yellow 5, sodium citrate.", n(220, 11, 0, 0.03, 0, 0, 0, 0), { beverage: true, nova: 4 }),
  food("Smirnoff Ice Original", "Smirnoff", "alcohol", ["water", "sugar", "e330", "e102"], "Carbonated water, sugar, vodka, citric acid, natural flavour, yellow 5.", n(230, 13, 0, 0.03, 0, 0, 0, 0), { beverage: true, nova: 4 }),
  food("Barefoot Moscato", "Barefoot", "alcohol", ["e220"], "Grapes, sulfites.", n(340, 9, 0, 0.01, 0, 0.1, 100, 0), { beverage: true, nova: 3 }),
  food("Kendall-Jackson Vintner's Reserve Chardonnay", "Kendall-Jackson", "alcohol", ["e220"], "Grapes, sulfites.", n(340, 0.5, 0, 0.01, 0, 0.1, 100, 0), { beverage: true, nova: 1 }),
  food("Josh Cellars Cabernet Sauvignon", "Josh Cellars", "alcohol", ["e220"], "Grapes, sulfites.", n(355, 0.4, 0, 0.01, 0, 0.1, 100, 0), { beverage: true, nova: 1 }),
  food("La Marca Prosecco", "La Marca", "alcohol", ["e220"], "Grapes, sulfites.", n(330, 3, 0, 0.01, 0, 0.1, 100, 0), { beverage: true, nova: 3 }),
  food("Modelo Especial", "Modelo", "alcohol", ["water"], "Water, barley malt, hops, corn.", n(180, 0, 0, 0.02, 0, 0.4, 0, 0), { beverage: true, nova: 3 }),
  food("Topo Chico Hard Seltzer Strawberry-Guava", "Topo Chico", "alcohol", ["water", "sugar", "natural-flavour", "e330"], "Sparkling mineral water, alcohol, natural flavour, citric acid, sucralose.", n(80, 1, 0, 0.02, 0, 0, 0, 0), { beverage: true, nova: 4 }),
  food("Twisted Tea Original", "Twisted Tea", "alcohol", ["water", "sugar", "tea", "e330"], "Water, sugar, malt, tea, citric acid, natural flavour.", n(200, 9, 0, 0.02, 0, 0, 0, 0), { beverage: true, nova: 4 }),

  // —— Ice cream ——
  food("Häagen-Dazs Vanilla Ice Cream", "Häagen-Dazs", "icecream", ["milk", "sugar", "egg", "vanilla"], "Cream, skim milk, sugar, egg yolks, vanilla extract.", n(1130, 21, 11, 0.12, 0, 4, 0, 17), { nova: 3 }),
  food("Häagen-Dazs Chocolate Ice Cream Pint", "Häagen-Dazs", "icecream", ["milk", "sugar", "cocoa", "egg"], "Cream, skim milk, sugar, cocoa, egg yolks.", n(1170, 22, 12, 0.15, 2, 4, 0, 18), { nova: 3 }),
  food("Ben & Jerry's Cherry Garcia", "Ben & Jerry's", "icecream", ["milk", "sugar", "egg", "e322"], "Cream, skim milk, sugar, cherries, chocolate chunks, egg yolks, cocoa, vanilla, soy lecithin.", n(1050, 24, 8, 0.12, 1, 4, 4, 14), { nova: 4 }),
  food("Ben & Jerry's Half Baked", "Ben & Jerry's", "icecream", ["milk", "sugar", "wheat-flour", "egg", "e322"], "Cream, skim milk, sugar, wheat flour, cocoa, egg yolks, chocolate chip cookie dough, brownies, soy lecithin.", n(1130, 26, 8, 0.15, 1, 4, 0, 15), { nova: 4 }),
  food("Breyers Natural Vanilla", "Breyers", "icecream", ["milk", "sugar", "e407", "vanilla"], "Milk, cream, sugar, tara gum, vanilla, vitamin A palmitate.", n(880, 18, 5, 0.1, 0, 3, 0, 10), { nova: 3 }),
  food("Breyers Extra Creamy Chocolate", "Breyers", "icecream", ["milk", "sugar", "cocoa", "e407"], "Milk, cream, sugar, cocoa, tara gum, carob bean gum.", n(920, 20, 6, 0.12, 1, 3, 0, 11), { nova: 3 }),
  food("Tillamook Old-Fashioned Vanilla", "Tillamook", "icecream", ["milk", "sugar", "egg", "vanilla"], "Cream, milk, sugar, egg yolks, vanilla, tara gum.", n(1000, 20, 8, 0.1, 0, 4, 0, 14), { nova: 3 }),
  food("Halo Top Vanilla Bean", "Halo Top", "icecream", ["milk", "e965", "e406", "e950"], "Skim milk, eggs, erythritol, prebiotic fiber, milk protein isolate, organic cane sugar, vanilla, stevia, sucralose.", n(330, 6, 1, 0.2, 5, 6, 0, 2), { nova: 4 }),
  food("Nick's Swedish-Style Vanilla", "Nick's", "icecream", ["milk", "e965", "e412", "e960"], "Milk, cream, soluble corn fiber, erythritol, allulose, stevia, vanilla, guar gum.", n(250, 3, 2, 0.15, 6, 4, 0, 4), { nova: 4 }),
  food("Talenti Mediterranean Mint", "Talenti", "icecream", ["milk", "sugar", "egg"], "Milk, sugar, cream, egg yolk, mint, chocolate flakes, carob bean gum.", n(1050, 24, 8, 0.12, 0, 4, 0, 14), { nova: 3 }),
  food("Magnum Double Chocolate Bar", "Magnum", "icecream", ["milk", "sugar", "cocoa", "palm-oil", "e322"], "Milk chocolate, ice cream (milk, sugar, cream), cocoa, palm oil, soy lecithin.", n(1380, 25, 14, 0.12, 2, 4, 0, 22), { nova: 4 }),
  food("Klondike Original Bar", "Klondike", "icecream", ["milk", "sugar", "palm-oil", "e322", "e471"], "Ice cream, coating (coconut oil, sugar, chocolate liquor, soy lecithin).", n(1300, 22, 14, 0.15, 1, 3, 0, 20), { nova: 4 }),
  food("Drumstick Vanilla Sundae Cone", "Drumstick", "icecream", ["milk", "sugar", "wheat-flour", "palm-oil", "e322"], "Ice cream, cone (wheat flour, sugar), peanuts, cocoa, palm oil, soy lecithin.", n(1260, 20, 8, 0.15, 1, 3, 0, 16), { nova: 4 }),
  food("Good Humor Strawberry Shortcake", "Good Humor", "icecream", ["milk", "sugar", "wheat-flour", "e129", "e102"], "Ice cream, coating (sugar, coconut oil, wheat flour, red 40, yellow 5).", n(1210, 22, 8, 0.14, 0, 2, 0, 14), { nova: 4 }),
  food("Popsicle Rainbow Ice Pops", "Popsicle", "icecream", ["sugar", "e330", "e102", "e129", "e133"], "Water, sugar, corn syrup, citric acid, yellow 5, red 40, blue 1, natural flavour.", n(330, 19, 0, 0.02, 0, 0, 0, 0), { nova: 4 }),
  food("Outshine Strawberry Fruit Bars", "Outshine", "icecream", ["sugar", "e440", "e330"], "Water, strawberries, sugar, citrus pectin, locust bean gum, citric acid, natural flavour, beet juice.", n(330, 18, 0, 0.01, 1, 0, 20, 0), { nova: 3 }),
  food("365 Organic Vanilla Ice Cream", "365 Whole Foods Market", "icecream", ["milk", "sugar", "vanilla"], "Organic milk, organic cream, organic cane sugar, organic vanilla, locust bean gum.", n(920, 18, 7, 0.1, 0, 3, 0, 12), { organic: true, nova: 3 }),
  food("Van Leeuwen Honeycomb", "Van Leeuwen", "icecream", ["milk", "sugar", "egg", "honey"], "Milk, cream, sugar, egg yolks, honey, vanilla.", n(1170, 22, 10, 0.12, 0, 4, 0, 16), { nova: 3 }),

  // —— Seafood ——
  food("Wild Planet Skipjack Wild Tuna", "Wild Planet", "seafood", ["fish", "salt"], "Skipjack tuna, sea salt.", n(480, 0, 0.5, 0.5, 0, 26, 0, 2), { nova: 1 }),
  food("Safe Catch Elite Tuna", "Safe Catch", "seafood", ["fish"], "Skipjack tuna.", n(440, 0, 0.3, 0.3, 0, 25, 0, 1), { nova: 1 }),
  food("Chicken of the Sea Chunk Light Tuna in Water", "Chicken of the Sea", "seafood", ["fish", "salt"], "Skipjack tuna, water, vegetable broth, salt.", n(360, 0, 0.2, 0.7, 0, 19, 0, 1), { nova: 3 }),
  food("StarKist Chunk Light Tuna in Water", "StarKist", "seafood", ["fish", "salt"], "Light tuna, water, vegetable broth, salt.", n(360, 0, 0.2, 0.7, 0, 19, 0, 1), { nova: 3 }),
  food("Bumble Bee Solid White Albacore in Water", "Bumble Bee", "seafood", ["fish", "salt"], "White tuna, water, salt.", n(420, 0, 0.4, 0.6, 0, 23, 0, 1), { nova: 3 }),
  food("King Oscar Sardines in Extra Virgin Olive Oil", "King Oscar", "seafood", ["fish", "olive-oil", "salt"], "Sardines, extra virgin olive oil, salt.", n(1050, 0, 3, 0.8, 0, 22, 0, 18), { nova: 1 }),
  food("Season Brand Skinless Boneless Sardines", "Season", "seafood", ["fish", "olive-oil", "salt"], "Sardines, olive oil, salt.", n(880, 0, 2, 0.7, 0, 21, 0, 12), { nova: 1 }),
  food("Bumble Bee Fancy Whole Smoked Oysters", "Bumble Bee", "seafood", ["fish", "salt"], "Oysters, cottonseed oil, salt, smoke flavour, sodium phosphate.", n(840, 1, 3, 0.9, 0, 12, 0, 12), { nova: 3 }),
  food("Gorton's Beer Battered Fish Fillets", "Gorton's", "seafood", ["fish", "wheat-flour", "palm-oil", "salt", "e500"], "Alaska pollock, wheat flour, vegetable oil, beer, salt, baking powder, spice.", n(1050, 2, 2, 1.1, 1, 10, 0, 12), { nova: 4 }),
  food("Van de Kamp's Crunchy Fish Sticks", "Van de Kamp's", "seafood", ["fish", "wheat-flour", "palm-oil", "e102", "salt"], "Minced pollock, wheat flour, vegetable oil, yellow 5, yellow 6, salt, spice.", n(1130, 2, 2, 1.2, 1, 9, 0, 14), { nova: 4 }),
  food("Mrs Paul's Crunchy Fish Sticks", "Mrs Paul's", "seafood", ["fish", "wheat-flour", "palm-oil", "e102", "salt"], "Minced fish, batter, vegetable oil, yellow 5, salt.", n(1130, 2, 2, 1.2, 1, 9, 0, 14), { nova: 4 }),
  food("Icelandic Haddock Fillets", "Icelandic", "seafood", ["fish"], "Haddock.", n(340, 0, 0.1, 0.15, 0, 18, 0, 1), { nova: 1 }),
  food("Whole Catch Wild Alaskan Salmon", "365 Whole Foods Market", "seafood", ["fish"], "Wild sockeye salmon.", n(590, 0, 1, 0.15, 0, 22, 0, 6), { nova: 1 }),
  food("Trident Seafoods Wild Salmon Burgers", "Trident", "seafood", ["fish", "salt"], "Pink salmon, water, potato extract, salt, lemon juice, spice.", n(500, 0, 1, 0.6, 0, 18, 0, 4), { nova: 3 }),
  food("Chicken of the Sea Salmon in Water", "Chicken of the Sea", "seafood", ["fish", "salt"], "Pink salmon, water, salt.", n(420, 0, 0.8, 0.7, 0, 20, 0, 4), { nova: 3 }),
  food("Crown Prince Natural Brisling Sardines", "Crown Prince", "seafood", ["fish", "olive-oil", "salt"], "Brisling sardines, extra virgin olive oil, salt.", n(1000, 0, 3, 0.7, 0, 22, 0, 16), { nova: 1 }),

  // —— Vitamins ——
  food("Nature Made Vitamin D3 2000 IU", "Nature Made", "vitamins", ["e551"], "Cholecalciferol, cellulose, magnesium stearate, silicon dioxide.", n(0, 0, 0, 0, 0, 0, 0, 0), { nova: 3 }),
  food("Nature Made Vitamin C 500 mg", "Nature Made", "vitamins", ["e330", "e551"], "Ascorbic acid, cellulose, magnesium stearate, silicon dioxide.", n(0, 0, 0, 0, 0, 0, 0, 0), { nova: 3 }),
  food("Nature Made Fish Oil 1200 mg", "Nature Made", "vitamins", ["fish", "e307"], "Fish oil, gelatin, glycerin, water, tocopherol.", n(40, 0, 0, 0, 0, 0, 0, 4), { nova: 3 }),
  food("Kirkland Vitamin D3 50 mcg", "Kirkland", "vitamins", ["e551"], "Cholecalciferol, microcrystalline cellulose, silicon dioxide.", n(0, 0, 0, 0, 0, 0, 0, 0), { nova: 3 }),
  food("Kirkland Super B-Complex", "Kirkland", "vitamins", ["e551"], "B vitamins, cellulose, silicon dioxide, magnesium stearate.", n(0, 0, 0, 0, 0, 0, 0, 0), { nova: 3 }),
  food("Centrum Adults", "Centrum", "vitamins", ["e171", "e129", "e132", "e551"], "Vitamins and minerals, microcrystalline cellulose, titanium dioxide, red 40, blue 2, magnesium stearate.", n(0, 0, 0, 0, 0, 0, 0, 0), { nova: 4 }),
  food("One A Day Women's", "One A Day", "vitamins", ["e171", "e129", "e551"], "Vitamins and minerals, cellulose, titanium dioxide, red 40, magnesium stearate.", n(0, 0, 0, 0, 0, 0, 0, 0), { nova: 4 }),
  food("Flintstones Chewable Complete", "Flintstones", "vitamins", ["sugar", "e129", "e102", "e133"], "Sugar, vitamins, minerals, red 40, yellow 6, blue 1, natural and artificial flavour.", n(80, 4, 0, 0.01, 0, 0, 0, 0), { nova: 4 }),
  food("gummyvites Kids Multi", "L'il Critters", "vitamins", ["sugar", "e440", "e102", "e129"], "Glucose syrup, sugar, gelatin, citric acid, natural flavours, colours (turmeric, black carrot), pectin, vitamins.", n(60, 3, 0, 0.02, 0, 0, 0, 0), { nova: 4 }),
  food("Olly Perfect Women's Multi", "Olly", "vitamins", ["sugar", "e440", "e102"], "Glucose syrup, sugar, gelatin, citric acid, natural flavour, colours, vitamins.", n(50, 2, 0, 0.02, 0, 0, 0, 0), { nova: 4 }),
  food("Vitafusion MultiVites", "Vitafusion", "vitamins", ["sugar", "e440", "e102", "e129"], "Glucose syrup, sugar, water, gelatin, citric acid, natural flavour, colours, vitamins.", n(60, 3, 0, 0.02, 0, 0, 0, 0), { nova: 4 }),
  food("Garden of Life Vitamin Code Women", "Garden of Life", "vitamins", ["e551"], "Vitamin blend from organic fruits and vegetables, Saccharomyces cerevisiae, silicon dioxide.", n(20, 0, 0, 0, 1, 0, 10, 0), { organic: true, nova: 3 }),
  food("MegaFood Blood Builder", "MegaFood", "vitamins", [], "FoodState iron, vitamin C, folate, beet root, organic oranges.", n(10, 0, 0, 0, 0, 0, 20, 0), { organic: true, nova: 3 }),
  food("Ritual Essential for Women 18+", "Ritual", "vitamins", ["e551"], "Omega-3 DHA, vitamin D3, vitamin B12, iron, folate, magnesium, vitamin K2, boron, vegan capsule.", n(20, 0, 0, 0, 0, 0, 0, 2), { nova: 3 }),
  food("Emergen-C Super Orange", "Emergen-C", "vitamins", ["sugar", "e330", "e102", "e160a"], "Fructose, citric acid, ascorbic acid, potassium bicarbonate, orange juice powder, yellow 6, natural flavour, beta carotene.", n(100, 6, 0, 0.06, 0, 0, 0, 0), { nova: 4 }),
  food("Airborne Very Berry Chewable", "Airborne", "vitamins", ["sugar", "e129", "e102", "e330"], "Sorbitol, ascorbic acid, sodium ascorbate, citric acid, natural flavour, red 40, yellow 6.", n(40, 0, 0, 0.05, 0, 0, 0, 0), { nova: 4 }),

  // —— Hair ——
  cos("Pantene Repair & Protect Shampoo", "Pantene", "hair", ["water", "sles", "dimethicone", "fragrance", "methylisothiazolinone"], "Water, sodium laureth sulfate, sodium lauryl sulfate, dimethicone, fragrance, methylisothiazolinone, citric acid."),
  cos("Pantene Repair & Protect Conditioner", "Pantene", "hair", ["water", "cetyl-alcohol", "dimethicone", "fragrance"], "Water, stearyl alcohol, cetyl alcohol, dimethicone, fragrance, histidine, methylchloroisothiazolinone."),
  cos("Head & Shoulders Classic Clean", "Head & Shoulders", "hair", ["water", "sles", "zinc-pyrithione", "fragrance"], "Water, sodium laureth sulfate, sodium lauryl sulfate, zinc pyrithione, fragrance, methylchloroisothiazolinone."),
  cos("Garnier Fructis Sleek & Shine Shampoo", "Garnier", "hair", ["water", "sles", "dimethicone", "fragrance"], "Water, sodium laureth sulfate, coco-betaine, dimethicone, fragrance, methylisothiazolinone, yellow 5."),
  cos("Herbal Essences Bio:Renew Argan Oil Shampoo", "Herbal Essences", "hair", ["water", "sles", "fragrance", "limonene"], "Water, sodium laureth sulfate, sodium lauryl sulfate, fragrance, limonene, linalool, methylisothiazolinone."),
  cos("OGX Renewing Argan Oil of Morocco Shampoo", "OGX", "hair", ["water", "sles", "dimethicone", "fragrance"], "Water, sodium laureth sulfate, dimethicone, argania spinosa kernel oil, fragrance, methylisothiazolinone."),
  cos("TRESemmé Keratin Smooth Shampoo", "TRESemmé", "hair", ["water", "sles", "dimethicone", "fragrance"], "Water, sodium laureth sulfate, dimethicone, fragrance, methylisothiazolinone, linalool."),
  cos("Dove Nutritive Solutions Daily Moisture", "Dove", "hair", ["water", "sles", "dimethicone", "fragrance"], "Water, sodium laureth sulfate, stearyl alcohol, dimethicone, fragrance, methylisothiazolinone."),
  cos("SheaMoisture Coconut & Hibiscus Shampoo", "SheaMoisture", "hair", ["water", "decyl-glucoside", "shea", "fragrance"], "Water, decyl glucoside, shea butter, coconut oil, fragrance, tocopherol."),
  cos("Maui Moisture Heal & Hydrate + Shea Butter", "Maui Moisture", "hair", ["water", "decyl-glucoside", "shea", "fragrance"], "Aloe barbadensis leaf juice, decyl glucoside, shea butter, coconut oil, fragrance."),
  cos("The Ordinary Multi-Peptide Serum for Hair Density", "The Ordinary", "hair", ["water", "panthenol", "caffeine"], "Water, glycerin, butylene glycol, caffeine, panthenol, lactic acid, phenoxyethanol."),
  cos("Olaplex No. 3 Hair Perfector", "Olaplex", "hair", ["water", "phenoxyethanol"], "Water, bis-aminopropyl diglycol dimaleate, phenoxyethanol, sodium benzoate, fragrance."),
  cos("Living Proof Perfect Hair Day Shampoo", "Living Proof", "hair", ["water", "decyl-glucoside", "phenoxyethanol"], "Water, sodium methyl 2-sulfolaurate, decyl glucoside, phenoxyethanol, fragrance."),
  cos("Briogeo Don't Despair, Repair!", "Briogeo", "hair", ["water", "decyl-glucoside", "panthenol", "phenoxyethanol"], "Water, sodium lauroyl methyl isethionate, decyl glucoside, panthenol, rosehip, argan, phenoxyethanol."),
  cos("L'Oréal Elvive Total Repair 5 Shampoo", "L'Oréal", "hair", ["water", "sles", "dimethicone", "fragrance"], "Water, sodium laureth sulfate, dimethicone, fragrance, methylisothiazolinone, linalool, hexyl cinnamal."),
  cos("Aveda Shampure Shampoo", "Aveda", "hair", ["water", "decyl-glucoside", "fragrance", "limonene", "linalool"], "Water, sodium cocoyl isethionate, decyl glucoside, fragrance (essential oils), limonene, linalool."),

  // —— Sun ——
  cos("EltaMD UV Clear Broad-Spectrum SPF 46", "EltaMD", "sun", ["zinc-oxide", "octinoxate", "hyaluronic", "niacinamide"], "Zinc oxide 9%, octinoxate 7.5%, water, niacinamide, hyaluronic acid, octyldodecyl neopentanoate."),
  cos("La Roche-Posay Anthelios Melt-in Milk SPF 60", "La Roche-Posay", "sun", ["avobenzone", "homosalate", "octisalate", "octocrylene"], "Avobenzone 3%, homosalate 10%, octisalate 5%, octocrylene 7%, water, glycerin, dimethicone, phenoxyethanol."),
  cos("Supergoop Unseen Sunscreen SPF 40", "Supergoop", "sun", ["avobenzone", "octisalate", "octocrylene"], "Avobenzone 3%, homosalate 8%, octisalate 5%, octocrylene 4%, dimethicone, silica."),
  cos("Neutrogena Ultra Sheer Dry-Touch SPF 55", "Neutrogena", "sun", ["avobenzone", "homosalate", "octisalate", "oxybenzone"], "Avobenzone, homosalate, octisalate, octocrylene, oxybenzone, acrylate copolymer, fragrance."),
  cos("Coppertone Sport SPF 50", "Coppertone", "sun", ["avobenzone", "homosalate", "octisalate", "octocrylene"], "Avobenzone, homosalate, octisalate, octocrylene, alcohol denat, fragrance."),
  cos("Banana Boat Ultra Sport SPF 50", "Banana Boat", "sun", ["avobenzone", "homosalate", "octocrylene", "oxybenzone"], "Avobenzone, homosalate, octocrylene, oxybenzone, alcohol, fragrance."),
  cos("Hawaiian Tropic Island Sport SPF 30", "Hawaiian Tropic", "sun", ["avobenzone", "homosalate", "octocrylene", "fragrance"], "Avobenzone, homosalate, octocrylene, fragrance, alcohol."),
  cos("CeraVe Hydrating Mineral Sunscreen SPF 50", "CeraVe", "sun", ["zinc-oxide", "titanium-dioxide", "ceramide-np", "hyaluronic"], "Zinc oxide 10%, titanium dioxide 5.5%, ceramides, hyaluronic acid, niacinamide."),
  cos("Thinkbaby Safe Sunscreen SPF 50", "Thinkbaby", "sun", ["zinc-oxide"], "Non-nano zinc oxide 20%, water, aloe, sunflower oil, shea, jojoba."),
  cos("Badger Active Mineral Sunscreen SPF 30", "Badger", "sun", ["zinc-oxide", "sunflower-oil", "beeswax"], "Non-nano zinc oxide 18.75%, organic sunflower oil, beeswax, organic jojoba, vitamin E."),
  cos("Sun Bum Original SPF 30", "Sun Bum", "sun", ["avobenzone", "homosalate", "octocrylene", "fragrance"], "Avobenzone, homosalate, octocrylene, octisalate, water, fragrance."),
  cos("Blue Lizard Australian Sunscreen Sensitive SPF 30+", "Blue Lizard", "sun", ["zinc-oxide", "titanium-dioxide"], "Zinc oxide 10%, titanium dioxide 5%, water, caprylic/capric triglyceride."),
  cos("MDSolarSciences Mineral Moisture Defense SPF 50", "MDSolarSciences", "sun", ["zinc-oxide", "titanium-dioxide", "dimethicone"], "Zinc oxide 5%, titanium dioxide 7.5%, dimethicone, hyaluronic acid."),
  cos("Eucerin Sensitive Mineral SPF 50", "Eucerin", "sun", ["zinc-oxide", "titanium-dioxide"], "Zinc oxide, titanium dioxide, water, glycerin, cetearyl alcohol."),
  cos("Aveeno Protect + Hydrate SPF 50", "Aveeno", "sun", ["avobenzone", "homosalate", "octisalate", "octocrylene"], "Avobenzone, homosalate, octisalate, octocrylene, glycerin, oat kernel extract."),
  cos("Shiseido Ultimate Sun Protector SPF 50+", "Shiseido", "sun", ["avobenzone", "octisalate", "octocrylene", "dimethicone"], "Avobenzone, octisalate, octocrylene, homosalate, dimethicone, alcohol, fragrance."),

  // —— Oral care ——
  cos("Crest Pro-Health Advanced", "Crest", "oral", ["sodium-fluoride", "sles", "e420", "fragrance"], "Sodium fluoride, water, sorbitol, hydrated silica, sodium lauryl sulfate, flavour, sodium saccharin, titanium dioxide."),
  cos("Colgate Total SF", "Colgate", "oral", ["sodium-fluoride", "sles", "e420"], "Sodium fluoride, water, glycerin, hydrated silica, sodium lauryl sulfate, PVM/MA copolymer, flavour, titanium dioxide."),
  cos("Sensodyne Pronamel Gentle Whitening", "Sensodyne", "oral", ["sodium-fluoride", "sles", "e420"], "Potassium nitrate, sodium fluoride, water, sorbitol, hydrated silica, sodium lauryl sulfate, flavour."),
  cos("Tom's of Maine Antiplaque & Whitening", "Tom's of Maine", "oral", ["glycerin", "e420", "e551"], "Calcium carbonate, water, glycerin, hydrated silica, xylitol, sodium lauryl sulfate, flavour, zinc citrate."),
  cos("Hello Naturally Friendly Fluoride", "Hello", "oral", ["sodium-fluoride", "glycerin", "e420"], "Sodium fluoride, water, hydrated silica, glycerin, xylitol, sorbitol, flavour, cocamidopropyl betaine."),
  cos("Burt's Bees Fluoride Toothpaste", "Burt's Bees", "oral", ["sodium-fluoride", "glycerin", "e420"], "Sodium fluoride, glycerin, water, hydrated silica, xylitol, flavour, sodium bicarbonate."),
  cos("Sensodyne Repair & Protect", "Sensodyne", "oral", ["sodium-fluoride", "sles", "e420"], "NovaMin, sodium fluoride, glycerin, PEG-8, hydrated silica, sodium lauryl sulfate, flavour."),
  cos("Listerine Cool Mint Antiseptic", "Listerine", "oral", ["alcohol-denat", "e420", "fragrance", "e133"], "Eucalyptol, menthol, methyl salicylate, thymol, alcohol, water, sorbitol, poloxamer 407, benzoic acid, green 3."),
  cos("Crest Pro-Health Multi-Protection Mouthwash", "Crest", "oral", ["cetylpyridinium", "e420", "e133"], "Cetylpyridinium chloride, water, glycerin, flavour, sucralose, blue 1, yellow 5."),
  cos("TheraBreath Fresh Breath Oral Rinse", "TheraBreath", "oral", ["e420", "e330"], "Purified water, PEG-40 hydrogenated castor oil, sodium benzoate, sodium chlorite, sodium bicarbonate, citric acid, flavour."),
  cos("CloSYS Unflavored Rinse", "CloSYS", "oral", ["e420"], "Water, sodium chlorite, sodium bicarbonate, flavour-free."),
  cos("Oral-B Glide Pro-Health Floss", "Oral-B", "oral", [], "PTFE floss, flavour, microcrystalline wax."),
  cos("Cocofloss Mint", "Cocofloss", "oral", ["coconut-oil", "fragrance"], "Polyester floss, coconut oil, beeswax, flavour, xylitol."),
  cos("Boka Ela Mint Toothpaste", "Boka", "oral", ["hydroxyapatite", "glycerin", "e420"], "Hydrated silica, glycerin, water, xylitol, nano-hydroxyapatite, cocos nucifera oil, flavour."),
  cos("RiseWell Mineral Toothpaste", "RiseWell", "oral", ["hydroxyapatite", "glycerin"], "Hydroxyapatite, glycerin, silica, xylitol, calcium carbonate, flavour."),
  cos("Marvis Whitening Mint", "Marvis", "oral", ["sles", "e420", "e171", "fragrance"], "Sorbitol, water, hydrated silica, PEG-32, sodium lauryl sulfate, aroma, titanium dioxide, sodium saccharin."),

  // —— Makeup ——
  cos("Maybelline Fit Me Matte + Poreless Foundation", "Maybelline", "makeup", ["water", "dimethicone", "ci-77891", "ci-77499", "phenoxyethanol"], "Water, dimethicone, isododecane, alcohol denat, titanium dioxide, iron oxides, phenoxyethanol, fragrance."),
  cos("Maybelline Lash Sensational Mascara", "Maybelline", "makeup", ["water", "beeswax", "ci-77499", "phenoxyethanol"], "Water, paraffin, potassium cetyl phosphate, beeswax, acacia, iron oxides, phenoxyethanol."),
  cos("L'Oréal True Match Foundation", "L'Oréal", "makeup", ["water", "dimethicone", "ci-77891", "ci-77499", "phenoxyethanol"], "Water, dimethicone, isododecane, glycerin, titanium dioxide, iron oxides, phenoxyethanol."),
  cos("CoverGirl Clean Fresh Skin Milk", "CoverGirl", "makeup", ["water", "dimethicone", "ci-77891", "phenoxyethanol"], "Water, glycerin, dimethicone, titanium dioxide, iron oxides, phenoxyethanol."),
  cos("e.l.f. Flawless Finish Foundation", "e.l.f.", "makeup", ["water", "dimethicone", "ci-77891", "ci-77499", "phenoxyethanol"], "Water, dimethicone, isododecane, titanium dioxide, iron oxides, phenoxyethanol."),
  cos("NYX Professional Makeup Soft Matte Lip Cream", "NYX", "makeup", ["dimethicone", "ci-77499", "phenoxyethanol"], "Dimethicone, isododecane, silica, iron oxides, red 7 lake, phenoxyethanol, fragrance."),
  cos("Revlon ColorStay Foundation", "Revlon", "makeup", ["water", "dimethicone", "ci-77891", "phenoxyethanol"], "Water, dimethicone, isododecane, trimethylsiloxysilicate, titanium dioxide, iron oxides, phenoxyethanol."),
  cos("Milani Conceal + Perfect Foundation", "Milani", "makeup", ["water", "dimethicone", "ci-77891", "phenoxyethanol"], "Water, dimethicone, glycerin, titanium dioxide, iron oxides, phenoxyethanol."),
  cos("Rare Beauty Soft Pinch Liquid Blush", "Rare Beauty", "makeup", ["water", "dimethicone", "phenoxyethanol"], "Water, dimethicone, glycerin, silica, iron oxides, phenoxyethanol."),
  cos("Fenty Beauty Pro Filt'r Soft Matte", "Fenty Beauty", "makeup", ["water", "dimethicone", "ci-77891", "ci-77499", "phenoxyethanol"], "Water, dimethicone, isododecane, trimethylsiloxysilicate, titanium dioxide, iron oxides, phenoxyethanol."),
  cos("NARS Radiant Creamy Concealer", "NARS", "makeup", ["water", "dimethicone", "ci-77891", "phenoxyethanol"], "Water, dimethicone, hydrogenated polydecene, titanium dioxide, iron oxides, phenoxyethanol."),
  cos("Charlotte Tilbury Pillow Talk Lipstick", "Charlotte Tilbury", "makeup", ["dimethicone", "ci-77499", "phenoxyethanol"], "Dimethicone, octyldodecanol, iron oxides, red 7 lake, fragrance, phenoxyethanol."),
  cos("Glossier Cloud Paint", "Glossier", "makeup", ["water", "dimethicone", "phenoxyethanol"], "Water, dimethicone, glycerin, iron oxides, phenoxyethanol."),
  cos("Saie Dew Blush", "Saie", "makeup", ["water", "jojoba", "phenoxyethanol"], "Water, jojoba esters, glycerin, iron oxides, phenoxyethanol, ethylhexylglycerin."),
  cos("ILIA Limitless Lash Mascara", "ILIA", "makeup", ["water", "beeswax", "ci-77499", "phenoxyethanol"], "Water, beeswax, glycerin, acacia senegal, iron oxides, phenoxyethanol."),
  cos("Tower 28 BeachPlease Lip + Cheek", "Tower 28", "makeup", ["water", "jojoba", "phenoxyethanol"], "Water, jojoba, glycerin, iron oxides, phenoxyethanol."),

  // —— Body / bath ——
  cos("Dove White Beauty Bar", "Dove", "body", ["sodium-stearate", "water", "fragrance", "stearic-acid"], "Sodium lauroyl isethionate, stearic acid, sodium tallowate, water, sodium isethionate, fragrance, titanium dioxide."),
  cos("Dove Deep Moisture Body Wash", "Dove", "body", ["water", "sles", "fragrance", "stearic-acid"], "Water, sodium laureth sulfate, glycerin, fragrance, stearic acid, methylisothiazolinone."),
  cos("Irish Spring Original Bar", "Irish Spring", "body", ["sodium-stearate", "fragrance", "e102", "e133"], "Sodium tallowate, water, fragrance, titanium dioxide, yellow 5, green 3, BHT."),
  cos("Old Spice Fiji Body Wash", "Old Spice", "body", ["water", "sles", "fragrance", "e102"], "Water, sodium laureth sulfate, fragrance, yellow 5, methylisothiazolinone, linalool, limonene."),
  cos("Degree UltraClear Black + White", "Degree", "body", ["aluminum-zirconium", "fragrance", "cyclopentasiloxane"], "Aluminum zirconium tetrachlorohydrex gly, cyclopentasiloxane, fragrance, dimethicone."),
  cos("Secret Outlast Completely Clean", "Secret", "body", ["aluminum-zirconium", "fragrance", "cyclopentasiloxane"], "Aluminum zirconium tetrachlorohydrex gly, cyclopentasiloxane, fragrance, dimethicone."),
  cos("Native Deodorant Coconut & Vanilla", "Native", "body", ["shea", "fragrance", "caprylic"], "Caprylic/capric triglyceride, tapioca starch, sodium bicarbonate, shea, fragrance, coconut oil."),
  cos("Schmidt's Lavender + Sage Deodorant", "Schmidt's", "body", ["shea", "fragrance", "caprylic"], "Maranta arundinacea root, sodium bicarbonate, shea, coconut oil, lavender oil, sage oil."),
  cos("Dr. Bronner's Baby Unscented Pure-Castile", "Dr. Bronner's", "body", ["water", "olive-oil", "coconut-oil", "e270"], "Water, organic coconut oil, potassium hydroxide, organic olive oil, organic hemp oil, citric acid, tocopherol."),
  cos("Cetaphil Gentle Skin Cleanser", "Cetaphil", "body", ["water", "cetyl-alcohol", "e410", "propylparaben", "methylparaben"], "Water, cetyl alcohol, propylene glycol, sodium lauryl sulfate, stearyl alcohol, methylparaben, propylparaben."),
  cos("CeraVe Hydrating Body Wash", "CeraVe", "body", ["water", "ceramide-np", "hyaluronic", "phenoxyethanol"], "Water, glycerin, ceramides, hyaluronic acid, niacinamide, phenoxyethanol, ethylhexylglycerin."),
  cos("Nivea Essentially Enriched Body Lotion", "Nivea", "body", ["water", "mineral-oil", "fragrance", "methylparaben"], "Water, mineral oil, glycerin, fragrance, methylparaben, lanolin alcohol."),
  cos("EOS Shea Better Body Lotion", "eos", "body", ["water", "shea", "fragrance", "phenoxyethanol"], "Water, shea butter, glycerin, fragrance, phenoxyethanol, ethylhexylglycerin."),
  cos("Aveeno Daily Moisturizing Lotion", "Aveeno", "body", ["water", "dimethicone", "phenoxyethanol"], "Water, glycerin, distearyldimonium chloride, petrolatum, isopropyl palmitate, cetyl alcohol, dimethicone, colloidal oatmeal, phenoxyethanol."),

  // —— Household ——
  cos("Seventh Generation Dish Liquid Lemon", "Seventh Generation", "household", ["water", "decyl-glucoside", "e330", "limonene"], "Water, sodium lauryl sulfate, lauryl glucoside, glycerin, sodium chloride, citric acid, lemon oil, limonene."),
  cos("Mrs Meyer's Clean Day Basil Hand Soap", "Mrs Meyer's", "household", ["water", "sles", "fragrance", "limonene", "methylisothiazolinone"], "Water, sodium laureth sulfate, lauryl glucoside, fragrance, limonene, geraniol, methylisothiazolinone."),
  cos("Method Foaming Hand Wash Sweet Water", "Method", "household", ["water", "decyl-glucoside", "fragrance", "phenoxyethanol"], "Water, sodium lauryl sulfate, decyl glucoside, fragrance, phenoxyethanol, ethylhexylglycerin."),
  cos("Palmolive Ultra Original Dish Soap", "Palmolive", "household", ["water", "sles", "fragrance", "e102", "e133"], "Water, sodium laureth sulfate, lauramidopropylamine oxide, fragrance, yellow 5, blue 1, methylisothiazolinone."),
  cos("Dawn Ultra Original", "Dawn", "household", ["water", "sles", "fragrance", "e133"], "Water, sodium lauryl sulfate, sodium laureth sulfate, denatured alcohol, fragrance, blue 1, methylisothiazolinone."),
  cos("Ajax Super Degreaser Dish Liquid", "Ajax", "household", ["water", "sles", "fragrance", "e102"], "Water, sodium laureth sulfate, fragrance, yellow 5, methylisothiazolinone."),
  cos("Lysol Disinfectant Spray Early Morning Breeze", "Lysol", "household", ["water", "fragrance", "e1520"], "Alkyl dimethyl benzyl ammonium saccharinate, ethanol, water, fragrance, propane, isobutane."),
  cos("Febreze Air Heavy Duty Crisp Clean", "Febreze", "household", ["water", "fragrance", "e1520"], "Water, alcohol, fragrance, nitrogen, didecyldimethylammonium chloride."),
  cos("Glade PlugIns Apple Cinnamon", "Glade", "household", ["fragrance", "limonene", "linalool"], "Fragrance, dipropylene glycol, limonene, linalool, hexyl cinnamal, eugenol."),
  cos("Yankee Candle Midsummer's Night", "Yankee Candle", "household", ["fragrance", "limonene", "linalool"], "Paraffin wax, fragrance, limonene, linalool, coumarin, eugenol."),
  cos("Ecover Zero Dish Soap", "Ecover", "household", ["water", "decyl-glucoside", "e330"], "Aqua, sodium lauryl sulfate, lauryl glucoside, sodium chloride, citric acid, sodium citrate."),
  cos("Blueland Dishwasher Tablet", "Blueland", "household", ["e500", "e551"], "Sodium carbonate, citric acid, sodium citrate, sodium silicate, enzymes, sodium polyaspartate."),
  cos("Dropps Stain & Odor Laundry Pods", "Dropps", "household", ["e1520", "e551"], "Sodium carbonate, sodium citrate, sodium silicate, enzymes, polyvinyl alcohol film."),
  cos("Attitude Nature+ Laundry Detergent", "Attitude", "household", ["water", "decyl-glucoside", "e330"], "Aqua, sodium coco-sulfate, caprylyl glucoside, sodium gluconate, sodium citrate, sodium chloride."),
  cos("Dr. Bronner's Sal Suds", "Dr. Bronner's", "household", ["water", "e330"], "Water, sodium lauryl sulfate from botanical sources, sodium cocoate, fir needle oil, spruce oil."),
  cos("Better Life Dish It Out", "Better Life", "household", ["water", "decyl-glucoside", "e330"], "Water, sodium lauryl sulfate, decyl glucoside, glycerin, citric acid, lemon oil."),

  // —— Baby extras ——
  food("Happy Baby Organics Clearly Crafted Pears", "Happy Baby", "baby", [], "Organic pears.", n(250, 12, 0, 0.02, 2, 0.5, 100, 0), { organic: true, nova: 1 }),
  food("Once Upon a Farm Cold-Pressed Wild Rumpus", "Once Upon a Farm", "baby", [], "Organic apple, organic banana, organic strawberry, organic lemon.", n(230, 11, 0, 0, 2, 0.5, 100, 0), { organic: true, nova: 1 }),
  food("Gerber Lil' Crunchies Mild Cheddar", "Gerber", "baby", ["corn", "cheddar", "salt", "e330"], "Whole grain sorghum flour, dried potatoes, degermed yellow corn meal, cheddar, salt, mixed tocopherols.", n(1800, 2, 1, 0.6, 2, 6, 0, 6), { nova: 4 }),
  food("Happy Baby Organic Teethers Banana Beet", "Happy Baby", "baby", ["rice", "e330"], "Organic rice flour, organic banana, organic beet, mixed tocopherols.", n(1600, 4, 0, 0.1, 1, 4, 8, 1), { organic: true, nova: 3 }),
  food("Plum Organics Mighty 4 Pumpkin", "Plum Organics", "baby", [], "Organic pumpkin, organic apple, organic Greek yogurt, organic quinoa, organic cinnamon.", n(280, 8, 0.3, 0.05, 2, 3, 80, 1), { organic: true, nova: 3 }),
  food("Beech-Nut Naturals Stage 1 Peas", "Beech-Nut", "baby", [], "Peas, water.", n(220, 3, 0, 0.04, 3, 3, 100, 0), { nova: 1 }),
  food("Gerber Banana Cookie", "Gerber", "baby", ["wheat-flour", "sugar", "palm-oil"], "Wheat flour, banana flakes, sugar, palm oil, mixed tocopherols.", n(1750, 22, 4, 0.3, 2, 5, 8, 10), { nova: 4 }),
  food("Little Bellies Organic Pea Puffs", "Little Bellies", "baby", ["pea", "rice"], "Organic pea flour, organic rice flour, organic sunflower oil.", n(1700, 2, 0.5, 0.2, 4, 8, 0, 6), { organic: true, nova: 3 }),

  // —— Pet extras ——
  pet("Open Farm Grass-Fed Beef Dry", "Open Farm", ["beef", "rice"], "Beef, ocean whitefish meal, sweet potatoes, peas, herring meal, coconut oil.", n(1550, 3, 4, 0.6, 4, 30, 0, 14), { nova: 3 }),
  pet("The Farmer's Dog Beef Recipe", "The Farmer's Dog", ["beef", "rice"], "USDA beef, sweet potato, lentil, carrot, broccoli, beef liver, spinach.", n(540, 4, 3, 0.3, 3, 12, 20, 8), { nova: 1 }),
  pet("Ollie Fresh Turkey Dish", "Ollie", ["chicken", "rice"], "Turkey, spinach, carrot, pumpkin, turkey liver, kale.", n(520, 3, 2, 0.3, 3, 11, 20, 6), { nova: 1 }),
  pet("Royal Canin Adult Dry", "Royal Canin", ["chicken", "rice", "e621", "e320"], "Chicken by-product meal, corn, wheat, chicken fat, corn gluten meal, natural flavors, BHA.", n(1550, 2, 5, 0.7, 3, 25, 0, 14), { nova: 4 }),
  pet("Hill's Science Diet Adult Chicken", "Hill's Science Diet", ["chicken", "rice", "e320"], "Chicken, whole grain wheat, cracked pearled barley, whole grain sorghum, chicken meal, soybean oil, BHA.", n(1540, 2, 4, 0.6, 3, 24, 0, 14), { nova: 4 }),
  pet("Purina Fancy Feast Grilled Chicken", "Fancy Feast", ["chicken", "e407", "e621"], "Chicken, meat by-products, fish, wheat gluten, soy flour, artificial and natural flavors, carrageenan.", n(380, 0, 1, 0.5, 0, 10, 0, 4), { nova: 4 }),
  pet("Wellness CORE Grain-Free Indoor", "Wellness CORE", ["chicken", "pea"], "Deboned turkey, turkey meal, chicken meal, peas, potatoes, chicken fat.", n(1560, 2, 4, 0.5, 4, 38, 0, 14), { nova: 3 }),
  pet("Stella & Chewy's Freeze-Dried Dinner Patties", "Stella & Chewy's", ["chicken"], "Chicken with ground bone, chicken liver, chicken gizzard, pumpkin seed, organic carrots.", n(1880, 1, 6, 0.4, 2, 45, 4, 18), { nova: 1 }),
];
