import type { ProductDef } from "./products";
import type { Nutrition } from "@/lib/scoring/types";

function n(
  energyKj: number,
  sugars: number,
  sat: number,
  salt: number,
  fiber: number,
  protein: number,
  fv: number,
  fat?: number,
): Nutrition {
  return { energyKj, sugars, saturatedFat: sat, salt, fiber, protein, fruitsVegetables: fv, fat };
}

/** Widely scanned supermarket SKUs. Live Open Food Facts covers the rest of the world. */
export const MORE_PRODUCTS: ProductDef[] = [
  {
    barcode: "0028400090896",
    title: "Doritos Nacho Cheese",
    brand: "Doritos",
    type: "food",
    categoryPath: "snacks",
    isOrganic: false,
    ingredientIds: ["corn", "palm-oil", "salt", "e621", "e631", "e102", "e110", "e129"],
    ingredientsText:
      "Corn, vegetable oil (corn, canola, and/or sunflower), maltodextrin, salt, cheddar cheese, whey, monosodium glutamate, cheddar cheese flavour, yellow 6, yellow 5, red 40, disodium inosinate.",
    nutrition: n(2260, 2.5, 3.5, 1.6, 3.6, 7, 0, 28),
    novaGroup: 4,
  },
  {
    barcode: "5449000054227",
    title: "Coca-Cola Zero Sugar",
    brand: "Coca-Cola",
    type: "food",
    categoryPath: "beverages",
    isOrganic: false,
    isBeverage: true,
    ingredientIds: ["water", "e330", "e150c", "e338", "e950", "e951", "natural-flavour", "carbon-dioxide"],
    ingredientsText:
      "Carbonated water, colour (E150d), phosphoric acid, sweeteners (aspartame E951, acesulfame K E950), natural flavourings including caffeine.",
    nutrition: n(1, 0, 0, 0.02, 0, 0, 0, 0),
    novaGroup: 4,
  },
  {
    barcode: "5000112637939",
    title: "Diet Coke",
    brand: "Coca-Cola",
    type: "food",
    categoryPath: "beverages",
    isOrganic: false,
    isBeverage: true,
    ingredientIds: ["water", "e330", "e150c", "e338", "e951", "e950", "natural-flavour", "carbon-dioxide"],
    ingredientsText:
      "Carbonated water, colour (E150d), sweeteners (aspartame, acesulfame K), natural flavourings including caffeine, phosphoric acid.",
    nutrition: n(2, 0, 0, 0.02, 0, 0, 0, 0),
    novaGroup: 4,
  },
  {
    barcode: "5449000011527",
    title: "Sprite",
    brand: "Coca-Cola",
    type: "food",
    categoryPath: "beverages",
    isOrganic: false,
    isBeverage: true,
    ingredientIds: ["water", "sugar", "e330", "e331", "natural-flavour", "carbon-dioxide"],
    ingredientsText: "Carbonated water, sugar, citric acid, natural lemon and lime flavourings.",
    nutrition: n(131, 6.6, 0, 0.04, 0, 0, 0, 0),
    novaGroup: 4,
  },
  {
    barcode: "5449000050632",
    title: "Fanta Orange",
    brand: "Coca-Cola",
    type: "food",
    categoryPath: "beverages",
    isOrganic: false,
    isBeverage: true,
    ingredientIds: ["water", "sugar", "e330", "e160a", "e445", "natural-flavour", "carbon-dioxide"],
    ingredientsText: "Carbonated water, sugar, orange juice from concentrate, citric acid, natural flavourings, colour (carotenes).",
    nutrition: n(160, 8.7, 0, 0, 0, 0, 3, 0),
    novaGroup: 4,
  },
  {
    barcode: "012000161155",
    title: "Pepsi",
    brand: "Pepsi",
    type: "food",
    categoryPath: "beverages",
    isOrganic: false,
    isBeverage: true,
    ingredientIds: ["water", "sugar", "e330", "e150c", "e338", "natural-flavour", "carbon-dioxide"],
    ingredientsText: "Carbonated water, high fructose corn syrup, caramel colour, sugar, phosphoric acid, caffeine, citric acid, natural flavour.",
    nutrition: n(175, 11, 0, 0.02, 0, 0, 0, 0),
    novaGroup: 4,
  },
  {
    barcode: "5060335634414",
    title: "Perrier Sparkling Natural Mineral Water",
    brand: "Perrier",
    type: "food",
    categoryPath: "beverages",
    isOrganic: false,
    isBeverage: true,
    isWater: true,
    ingredientIds: ["water", "carbon-dioxide"],
    ingredientsText: "Natural mineral water, carbon dioxide.",
    nutrition: n(0, 0, 0, 0.01, 0, 0, 0, 0),
    novaGroup: 1,
  },
  {
    barcode: "0007800012344",
    title: "Gatorade Lemon-Lime",
    brand: "Gatorade",
    type: "food",
    categoryPath: "beverages",
    isOrganic: false,
    isBeverage: true,
    ingredientIds: ["water", "sugar", "e330", "e331", "e102", "salt", "natural-flavour"],
    ingredientsText: "Water, sugar, dextrose, citric acid, salt, sodium citrate, monopotassium phosphate, flavouring, yellow 5.",
    nutrition: n(103, 6, 0, 0.11, 0, 0, 0, 0),
    novaGroup: 4,
  },
  {
    barcode: "7622210477776",
    title: "KitKat",
    brand: "Nestlé",
    type: "food",
    categoryPath: "chocolate",
    isOrganic: false,
    ingredientIds: ["sugar", "cocoa", "wheat-flour", "milk", "palm-oil", "e322", "e500"],
    ingredientsText:
      "Sugar, wheat flour, cocoa butter, skimmed milk powder, cocoa mass, palm oil, butterfat, whey, emulsifier (lecithin), raising agent (E500), flavouring.",
    nutrition: n(2180, 49, 18, 0.24, 2.2, 6.5, 0, 26),
    novaGroup: 4,
  },
  {
    barcode: "5000159400084",
    title: "Mars Bar",
    brand: "Mars",
    type: "food",
    categoryPath: "chocolate",
    isOrganic: false,
    ingredientIds: ["sugar", "cocoa", "milk", "palm-oil", "e322", "e471"],
    ingredientsText: "Sugar, glucose syrup, skimmed milk powder, cocoa butter, cocoa mass, sunflower oil, milk fat, lactose, whey, palm fat, barley malt extract, emulsifier (soya lecithin).",
    nutrition: n(1883, 59.9, 8.3, 0.42, 1.2, 4.5, 0, 17),
    novaGroup: 4,
  },
  {
    barcode: "5000159461122",
    title: "Frosties",
    brand: "Kellogg's",
    type: "food",
    categoryPath: "breakfast",
    isOrganic: false,
    ingredientIds: ["sugar", "salt", "natural-flavour"],
    ingredientsText: "Maize, sugar, barley malt flavouring, salt, vitamins and minerals.",
    nutrition: n(1606, 37, 0.3, 0.83, 2, 5, 0, 0.6),
    novaGroup: 4,
  },
  {
    barcode: "5050083321393",
    title: "Weetabix",
    brand: "Weetabix",
    type: "food",
    categoryPath: "breakfast",
    isOrganic: false,
    ingredientIds: ["wheat-flour", "salt", "e322", "sugar"],
    ingredientsText: "Wholegrain wheat (95%), malted barley extract, sugar, salt, niacin, iron, riboflavin, thiamin, folic acid.",
    nutrition: n(1531, 4.4, 0.3, 0.28, 10, 12, 0, 2),
    novaGroup: 3,
  },
  {
    barcode: "5000108022497",
    title: "Special K Original",
    brand: "Kellogg's",
    type: "food",
    categoryPath: "breakfast",
    isOrganic: false,
    ingredientIds: ["wheat-flour", "sugar", "salt", "e322"],
    ingredientsText: "Rice, wheat (wholewheat, wheat flour), sugar, wheat gluten, defatted wheat germ, salt, barley malt flavouring, vitamins and minerals.",
    nutrition: n(1583, 15, 0.4, 1, 2.3, 8.5, 0, 1.5),
    novaGroup: 4,
  },
  {
    barcode: "0038000231254",
    title: "Cheerios Original",
    brand: "General Mills",
    type: "food",
    categoryPath: "breakfast",
    isOrganic: false,
    ingredientIds: ["oats", "sugar", "salt", "e322"],
    ingredientsText: "Whole grain oats, corn starch, sugar, salt, tripotassium phosphate, vitamin E (mixed tocopherols).",
    nutrition: n(1548, 4, 0.8, 0.63, 10, 12, 0, 6.5),
    novaGroup: 3,
  },
  {
    barcode: "038000138016",
    title: "Pringles Original",
    brand: "Pringles",
    type: "food",
    categoryPath: "snacks",
    isOrganic: false,
    ingredientIds: ["palm-oil", "salt", "e471", "e621"],
    ingredientsText: "Dehydrated potatoes, vegetable oils (sunflower, corn), rice flour, wheat starch, maltodextrin, emulsifier (E471), salt, flavouring.",
    nutrition: n(2235, 1.4, 2.8, 1.3, 2.8, 4, 0, 33),
    novaGroup: 4,
  },
  {
    barcode: "028400064011",
    title: "Doritos Nacho Cheese",
    brand: "Doritos",
    type: "food",
    categoryPath: "snacks",
    isOrganic: false,
    ingredientIds: ["salt", "e621", "e102", "e110", "palm-oil"],
    ingredientsText: "Corn, vegetable oil, maltodextrin, salt, cheddar cheese, whey, monosodium glutamate, cheddar cheese flavour, yellow 6, yellow 5.",
    nutrition: n(2092, 2.2, 3.5, 1.6, 4.4, 7.1, 0, 26.8),
    novaGroup: 4,
  },
  {
    barcode: "028400097040",
    title: "Lay's Classic",
    brand: "Lay's",
    type: "food",
    categoryPath: "snacks",
    isOrganic: false,
    ingredientIds: ["sunflower-oil", "salt"],
    ingredientsText: "Potatoes, vegetable oil (sunflower, corn, and/or canola), salt.",
    nutrition: n(2247, 0.4, 3, 1.3, 3.6, 6.6, 0, 35),
    novaGroup: 3,
  },
  {
    barcode: "041196010310",
    title: "Philadelphia Original",
    brand: "Philadelphia",
    type: "food",
    categoryPath: "dairy",
    isOrganic: false,
    ingredientIds: ["milk", "salt", "e410"],
    ingredientsText: "Milk, cream, salt, locust bean gum, citric acid.",
    nutrition: n(1046, 4.5, 17, 0.8, 0, 5.4, 0, 26),
    novaGroup: 3,
  },
  {
    barcode: "3033491236012",
    title: "Actimel Original",
    brand: "Danone",
    type: "food",
    categoryPath: "dairy",
    isOrganic: false,
    ingredientIds: ["milk", "sugar", "yogurt-cultures", "e440"],
    ingredientsText: "Yogurt (milk), sugar, dextrose, milk mineral concentrate, flavouring, Streptococcus thermophilus, Lactobacillus casei.",
    nutrition: n(310, 11.5, 1.1, 0.1, 0, 2.8, 0, 1.6),
    novaGroup: 4,
  },
  {
    barcode: "8000500037687",
    title: "Ferrero Rocher",
    brand: "Ferrero",
    type: "food",
    categoryPath: "chocolate",
    isOrganic: false,
    ingredientIds: ["sugar", "palm-oil", "hazelnut", "cocoa", "milk", "e322", "wheat-flour"],
    ingredientsText: "Milk chocolate, hazelnuts, sugar, palm oil, wheat flour, whey, fat-reduced cocoa, emulsifier lecithin, flavouring.",
    nutrition: n(2506, 39.9, 14.1, 0.15, 3.5, 8.2, 0, 42.7),
    novaGroup: 4,
  },
  {
    barcode: "7613035974685",
    title: "Nesquik Chocolate Powder",
    brand: "Nestlé",
    type: "food",
    categoryPath: "breakfast",
    isOrganic: false,
    ingredientIds: ["sugar", "cocoa", "e322", "salt", "natural-flavour"],
    ingredientsText: "Sugar, cocoa powder (16%), emulsifier (soya lecithin), cinnamon, salt, flavouring, vitamins.",
    nutrition: n(1594, 80, 2, 0.2, 6.5, 5.3, 0, 3.5),
    novaGroup: 4,
  },
  {
    barcode: "8712561610111",
    title: "Magnum Classic",
    brand: "Magnum",
    type: "food",
    categoryPath: "snacks",
    isOrganic: false,
    ingredientIds: ["sugar", "milk", "cocoa", "e471", "e410", "natural-flavour"],
    ingredientsText: "Reconstituted skimmed milk, sugar, cocoa butter, cocoa mass, coconut oil, glucose syrup, butter oil, whey, emulsifiers, stabilisers, flavouring.",
    nutrition: n(1272, 24, 14, 0.11, 1.2, 3.2, 0, 20),
    novaGroup: 4,
  },
  {
    barcode: "8714100905652",
    title: "Hellmann's Real Mayonnaise",
    brand: "Hellmann's",
    type: "food",
    categoryPath: "condiments",
    isOrganic: false,
    ingredientIds: ["sunflower-oil", "egg", "e260", "sugar", "salt", "e415"],
    ingredientsText: "Rapeseed oil (78%), water, pasteurised free range egg & egg yolk (8.9%), spirit vinegar, sugar, salt, lemon juice, flavourings, antioxidant, paprika extract.",
    nutrition: n(2941, 1.3, 6.1, 1.3, 0, 1.1, 0, 79),
    novaGroup: 4,
  },
  {
    barcode: "8715700422479",
    title: "Heinz Baked Beans",
    brand: "Heinz",
    type: "food",
    categoryPath: "staples",
    isOrganic: false,
    ingredientIds: ["tomato", "sugar", "salt", "e330", "spice"],
    ingredientsText: "Beans (51%), tomatoes (36%), water, sugar, spirit vinegar, modified cornflour, salt, spice extracts, herb extract.",
    nutrition: n(339, 4.7, 0.1, 0.6, 3.7, 4.7, 36, 0.2),
    novaGroup: 3,
  },
  {
    barcode: "5014271400145",
    title: "Marmite",
    brand: "Marmite",
    type: "food",
    categoryPath: "spreads",
    isOrganic: false,
    ingredientIds: ["salt", "e150c", "spice"],
    ingredientsText: "Yeast extract (contains BARLEY, WHEAT, OATS, RYE), salt, vegetable juice concentrate, vitamins, natural flavouring (contains CELERY).",
    nutrition: n(1107, 1.2, 0.1, 10.8, 3.1, 34, 0, 0.5),
    novaGroup: 3,
  },
  {
    barcode: "8001505005707",
    title: "Nutella & Go",
    brand: "Ferrero",
    type: "food",
    categoryPath: "spreads",
    isOrganic: false,
    ingredientIds: ["sugar", "palm-oil", "hazelnut", "cocoa", "milk", "e322", "wheat-flour"],
    ingredientsText: "Sugar, palm oil, hazelnuts, skimmed milk powder, fat-reduced cocoa, breadsticks (wheat flour), lecithin, vanillin.",
    nutrition: n(2146, 47, 9.8, 0.8, 2.4, 8, 8, 26),
    novaGroup: 4,
  },
  {
    barcode: "4011104001017",
    title: "Nivea Creme",
    brand: "Nivea",
    type: "cosmetic",
    categoryPath: "skincare",
    isOrganic: false,
    ingredientIds: ["water", "glycerin", "fragrance", "linalool", "citronellol", "e321"],
    ingredientsText:
      "Aqua, Paraffinum Liquidum, Cera Microcristallina, Glycerin, Lanolin Alcohol, Paraffin, Panthenol, Decyl Oleate, Octyldodecanol, Aluminum Stearates, Citric Acid, Magnesium Sulfate, Calcium Chloride, Magnesium Stearate, Parfum, Limonene, Geraniol, Hydroxycitronellal, Linalool, Citronellol, Benzyl Benzoate, Benzyl Alcohol.",
  },
  {
    barcode: "3337875597210",
    title: "CeraVe Moisturising Lotion",
    brand: "CeraVe",
    type: "cosmetic",
    categoryPath: "skincare",
    isOrganic: false,
    ingredientIds: ["water", "glycerin", "cetearyl", "hyaluronic", "tocopherol", "phenoxyethanol", "cetyl-alcohol"],
    ingredientsText:
      "Aqua, Glycerin, Caprylic/Capric Triglyceride, Cetearyl Alcohol, Cetyl Alcohol, Phenoxyethanol, Ceramide NP, Ceramide AP, Ceramide EOP, Carbomer, Dimethicone, Sodium Hyaluronate, Cholesterol, Sodium Lauroyl Lactylate, Tocopherol.",
  },
  {
    barcode: "3600541252574",
    title: "Garnier Micellar Water",
    brand: "Garnier",
    type: "cosmetic",
    categoryPath: "skincare",
    isOrganic: false,
    ingredientIds: ["water", "glycerin", "peg-40", "phenoxyethanol", "fragrance"],
    ingredientsText: "Aqua, Hexylene Glycol, Glycerin, Disodium Cocoamphodiacetate, Disodium EDTA, Poloxamer 184, Polyaminopropyl Biguanide.",
  },
  {
    barcode: "3600523191228",
    title: "L'Oréal Elvive Shampoo",
    brand: "L'Oréal",
    type: "cosmetic",
    categoryPath: "hair",
    isOrganic: false,
    ingredientIds: ["water", "sles", "cocamidopropyl", "fragrance", "linalool", "limonene", "ci19140"],
    ingredientsText:
      "Aqua, Sodium Laureth Sulfate, Dimethicone, Coco-Betaine, Sodium Chloride, Glycol Distearate, Parfum, Linalool, Limonene, CI 19140, CI 15985.",
  },
  {
    barcode: "4084500012342",
    title: "Head & Shoulders Classic",
    brand: "Head & Shoulders",
    type: "cosmetic",
    categoryPath: "hair",
    isOrganic: false,
    ingredientIds: ["water", "sles", "fragrance", "linalool", "ci19140"],
    ingredientsText: "Aqua, Sodium Laureth Sulfate, Sodium Lauryl Sulfate, Glycol Distearate, Zinc Pyrithione, Cocamidopropyl Betaine, Parfum, Linalool, CI 19140.",
  },
  {
    barcode: "305994034568",
    title: "Colgate Total",
    brand: "Colgate",
    type: "cosmetic",
    categoryPath: "body",
    isOrganic: false,
    ingredientIds: ["glycerin", "peg-40", "sodium-fluoride", "sles", "titanium-dioxide"],
    ingredientsText: "Aqua, Sorbitol, Hydrated Silica, Sodium Lauryl Sulfate, PVM/MA Copolymer, Aroma, Cellulose Gum, Sodium Fluoride, Sodium Saccharin, Titanium Dioxide, Triclosan.",
  },
  {
    barcode: "011111118518",
    title: "Dove Original Beauty Bar",
    brand: "Dove",
    type: "cosmetic",
    categoryPath: "body",
    isOrganic: false,
    ingredientIds: ["water", "glycerin", "fragrance", "titanium-dioxide", "citronellol"],
    ingredientsText: "Sodium Lauroyl Isethionate, Stearic Acid, Sodium Tallowate, Sodium Palmitate, Lauric Acid, Aqua, Sodium Isethionate, Parfum, Titanium Dioxide, Tetrasodium EDTA.",
  },
  {
    barcode: "071249307416",
    title: "Neutrogena Hydro Boost",
    brand: "Neutrogena",
    type: "cosmetic",
    categoryPath: "skincare",
    isOrganic: false,
    ingredientIds: ["water", "glycerin", "hyaluronic", "dimethicone", "phenoxyethanol", "fragrance"],
    ingredientsText: "Aqua, Dimethicone, Glycerin, Dimethicone/Vinyl Dimethicone Crosspolymer, Phenoxyethanol, Cetearyl Olivate, Sorbitan Olivate, Sodium Hyaluronate.",
  },
  {
    barcode: "3337872413999",
    title: "La Roche-Posay Anthelios SPF 50",
    brand: "La Roche-Posay",
    type: "cosmetic",
    categoryPath: "sun",
    isOrganic: false,
    ingredientIds: ["water", "homosalate", "octinoxate", "glycerin", "dimethicone", "phenoxyethanol"],
    ingredientsText:
      "Aqua, Homosalate, Ethylhexyl Salicylate, Octocrylene, Ethylhexyl Triazone, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Glycerin, Dimethicone, Phenoxyethanol.",
  },
  {
    barcode: "5900020012348",
    title: "Whiskas Adult Beef",
    brand: "Whiskas",
    type: "pet",
    categoryPath: "pet",
    isOrganic: false,
    ingredientIds: ["chicken", "wheat-flour", "e320", "e407", "e102", "salt"],
    ingredientsText: "Cereals, meat and animal derivatives (including beef), oils and fats, vegetable protein extracts, derivatives of vegetable origin, minerals, colourants, antioxidants (including BHA).",
    nutrition: n(1550, 1.5, 5, 1.2, 2, 30, 0, 12),
    novaGroup: 4,
  },
  {
    barcode: "3229820129488",
    title: "Pedigree Adult Complete",
    brand: "Pedigree",
    type: "pet",
    categoryPath: "pet",
    isOrganic: false,
    ingredientIds: ["chicken", "wheat-flour", "e320", "e407", "salt"],
    ingredientsText: "Cereals, meat and animal derivatives (including chicken), oils and fats, vegetables, minerals, antioxidants.",
    nutrition: n(1480, 2, 5.5, 1.1, 2.2, 21, 0, 10),
    novaGroup: 4,
  },
  {
    barcode: "5010029220000",
    title: "Quaker Oat So Simple",
    brand: "Quaker",
    type: "food",
    categoryPath: "breakfast",
    isOrganic: false,
    ingredientIds: ["oats"],
    ingredientsText: "Rolled oats.",
    nutrition: n(1557, 1.1, 1.3, 0.01, 9, 11, 0, 8),
    novaGroup: 1,
  },
  {
    barcode: "8000500026781",
    title: "Kinder Bueno",
    brand: "Kinder",
    type: "food",
    categoryPath: "chocolate",
    isOrganic: false,
    ingredientIds: ["sugar", "palm-oil", "hazelnut", "milk", "cocoa", "e322", "wheat-flour"],
    ingredientsText: "Milk chocolate, sugar, palm oil, hazelnuts, wheat flour, skimmed milk powder, fat-reduced cocoa, lecithin, vanillin.",
    nutrition: n(2384, 41.2, 17.3, 0.27, 1.8, 8.6, 0, 37.3),
    novaGroup: 4,
  },
];
