/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IngredientsRouteImport } from './routes/ingredients'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LensRouteImport } from './routes/lens'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MethodRouteImport } from './routes/method'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as YouRouteImport } from './routes/you'
import { Route as AisleSlugRouteImport } from './routes/aisle.$slug'
import { Route as BrandSlugRouteImport } from './routes/brand.$slug'
import { Route as GuidesIndexRouteImport } from './routes/guides.index'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as IngredientIdRouteImport } from './routes/ingredient.$id'
import { Route as ProductBarcodeRouteImport } from './routes/product.$barcode'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiProductsBarcodeRouteImport } from './routes/api/products.$barcode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsRoute = IngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LensRoute = LensRouteImport.update({
  id: '/lens',
  path: '/lens',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const YouRoute = YouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => rootRouteImport,
} as any)
const AisleSlugRoute = AisleSlugRouteImport.update({
  id: '/aisle/$slug',
  path: '/aisle/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSlugRoute = BrandSlugRouteImport.update({
  id: '/brand/$slug',
  path: '/brand/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const IngredientIdRoute = IngredientIdRouteImport.update({
  id: '/ingredient/$id',
  path: '/ingredient/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductBarcodeRoute = ProductBarcodeRouteImport.update({
  id: '/product/$barcode',
  path: '/product/$barcode',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsBarcodeRoute = ApiProductsBarcodeRouteImport.update({
  id: '/api/products/$barcode',
  path: '/api/products/$barcode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/compare': typeof CompareRoute
  '/guides': typeof GuidesRouteWithChildren
  '/history': typeof HistoryRoute
  '/ingredients': typeof IngredientsRoute
  '/insights': typeof InsightsRoute
  '/lens': typeof LensRoute
  '/lists': typeof ListsRoute
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/saved': typeof SavedRoute
  '/scan': typeof ScanRoute
  '/you': typeof YouRoute
  '/aisle/$slug': typeof AisleSlugRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/ingredient/$id': typeof IngredientIdRoute
  '/product/$barcode': typeof ProductBarcodeRoute
  '/guides/': typeof GuidesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/products/$barcode': typeof ApiProductsBarcodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/compare': typeof CompareRoute
  '/history': typeof HistoryRoute
  '/ingredients': typeof IngredientsRoute
  '/insights': typeof InsightsRoute
  '/lens': typeof LensRoute
  '/lists': typeof ListsRoute
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/saved': typeof SavedRoute
  '/scan': typeof ScanRoute
  '/you': typeof YouRoute
  '/aisle/$slug': typeof AisleSlugRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/ingredient/$id': typeof IngredientIdRoute
  '/product/$barcode': typeof ProductBarcodeRoute
  '/guides': typeof GuidesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/products/$barcode': typeof ApiProductsBarcodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRoute
  '/compare': typeof CompareRoute
  '/guides': typeof GuidesRouteWithChildren
  '/history': typeof HistoryRoute
  '/ingredients': typeof IngredientsRoute
  '/insights': typeof InsightsRoute
  '/lens': typeof LensRoute
  '/lists': typeof ListsRoute
  '/login': typeof LoginRoute
  '/method': typeof MethodRoute
  '/saved': typeof SavedRoute
  '/scan': typeof ScanRoute
  '/you': typeof YouRoute
  '/aisle/$slug': typeof AisleSlugRoute
  '/brand/$slug': typeof BrandSlugRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/ingredient/$id': typeof IngredientIdRoute
  '/product/$barcode': typeof ProductBarcodeRoute
  '/guides/': typeof GuidesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/products/$barcode': typeof ApiProductsBarcodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/compare'
    | '/guides'
    | '/history'
    | '/ingredients'
    | '/insights'
    | '/lens'
    | '/lists'
    | '/login'
    | '/method'
    | '/saved'
    | '/scan'
    | '/you'
    | '/aisle/$slug'
    | '/brand/$slug'
    | '/guides/$slug'
    | '/ingredient/$id'
    | '/product/$barcode'
    | '/guides/'
    | '/api/auth/$'
    | '/api/products/$barcode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/compare'
    | '/history'
    | '/ingredients'
    | '/insights'
    | '/lens'
    | '/lists'
    | '/login'
    | '/method'
    | '/saved'
    | '/scan'
    | '/you'
    | '/aisle/$slug'
    | '/brand/$slug'
    | '/guides/$slug'
    | '/ingredient/$id'
    | '/product/$barcode'
    | '/guides'
    | '/api/auth/$'
    | '/api/products/$barcode'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/compare'
    | '/guides'
    | '/history'
    | '/ingredients'
    | '/insights'
    | '/lens'
    | '/lists'
    | '/login'
    | '/method'
    | '/saved'
    | '/scan'
    | '/you'
    | '/aisle/$slug'
    | '/brand/$slug'
    | '/guides/$slug'
    | '/ingredient/$id'
    | '/product/$barcode'
    | '/guides/'
    | '/api/auth/$'
    | '/api/products/$barcode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRoute: typeof CatalogRoute
  CompareRoute: typeof CompareRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  IngredientsRoute: typeof IngredientsRoute
  InsightsRoute: typeof InsightsRoute
  LensRoute: typeof LensRoute
  ListsRoute: typeof ListsRoute
  LoginRoute: typeof LoginRoute
  MethodRoute: typeof MethodRoute
  SavedRoute: typeof SavedRoute
  ScanRoute: typeof ScanRoute
  YouRoute: typeof YouRoute
  AisleSlugRoute: typeof AisleSlugRoute
  BrandSlugRoute: typeof BrandSlugRoute
  IngredientIdRoute: typeof IngredientIdRoute
  ProductBarcodeRoute: typeof ProductBarcodeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiProductsBarcodeRoute: typeof ApiProductsBarcodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lens': {
      id: '/lens'
      path: '/lens'
      fullPath: '/lens'
      preLoaderRoute: typeof LensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/you': {
      id: '/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof YouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aisle/$slug': {
      id: '/aisle/$slug'
      path: '/aisle/$slug'
      fullPath: '/aisle/$slug'
      preLoaderRoute: typeof AisleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/$slug': {
      id: '/brand/$slug'
      path: '/brand/$slug'
      fullPath: '/brand/$slug'
      preLoaderRoute: typeof BrandSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/ingredient/$id': {
      id: '/ingredient/$id'
      path: '/ingredient/$id'
      fullPath: '/ingredient/$id'
      preLoaderRoute: typeof IngredientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$barcode': {
      id: '/product/$barcode'
      path: '/product/$barcode'
      fullPath: '/product/$barcode'
      preLoaderRoute: typeof ProductBarcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$barcode': {
      id: '/api/products/$barcode'
      path: '/api/products/$barcode'
      fullPath: '/api/products/$barcode'
      preLoaderRoute: typeof ApiProductsBarcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRoute: CatalogRoute,
  CompareRoute: CompareRoute,
  GuidesRoute: GuidesRouteWithChildren,
  HistoryRoute: HistoryRoute,
  IngredientsRoute: IngredientsRoute,
  InsightsRoute: InsightsRoute,
  LensRoute: LensRoute,
  ListsRoute: ListsRoute,
  LoginRoute: LoginRoute,
  MethodRoute: MethodRoute,
  SavedRoute: SavedRoute,
  ScanRoute: ScanRoute,
  YouRoute: YouRoute,
  AisleSlugRoute: AisleSlugRoute,
  BrandSlugRoute: BrandSlugRoute,
  IngredientIdRoute: IngredientIdRoute,
  ProductBarcodeRoute: ProductBarcodeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiProductsBarcodeRoute: ApiProductsBarcodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
